.github/workflows/buildAndTest.yaml
Adding whole team as reviewers to see what this GitHub Actions thing is all about.
This is a simple build and test example. It has an optional step to enable caching of our (lots of) dependencies.
=> feat(builds): Add GitHub action to build and test

.github/workflows/buildAndTest.yaml
Adds versions 11 (latest LTS) and 14 (latest non-LTS)
=> builds: Adds Java versions to strategy.matrix

.kokoro/promote.cfg, .kokoro/promote.sh
Copy/pasted from https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/tree/master/.kokoro
=> chore(releasing): Add missing promote scripts

.kokoro/stage.sh, pom.xml
Fixes some build warnings I was seeing locally, then fixes the stage.sh script (I hope)
=> Fix Release Process

.kokoro/drop.sh, .kokoro/release_snapshot.sh, pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/spring-cloud-gcp-kotlin-app-sample/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-test/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/pom.xml
Also noticed some sample modules didn't have names or went against the convention.
=> Enable release profile during drop.sh script

.kokoro/release_snapshot.sh
=> fix missing command-line continue-ers

spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-test/src/test/java/com/example/LocalSampleAppIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-test/src/test/resources/logback-test.xml
This test seems to be the most flaky, and there's no logging insight into what part is failing.
=> Add lots of debugging output for LocalSampleAppIntegrationTest

docs/src/main/asciidoc/spring-integration-pubsub.adoc, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandlerTests.java
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/838
=> Add test and docs for pubsub's setTopicExpressionString

docs/src/main/asciidoc/_configprops.adoc, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptions.java
This one is specific to Datastore.
=> fix(deprecated): Remove some more missed deprecations

spring-cloud-gcp-dependencies/pom.xml
Originally from https://github.com/spring-cloud/spring-cloud-gcp/pull/2572
=> chore(bom): Update gcp-bom version

spring-cloud-gcp-pubsub-stream-binder/pom.xml
These are pulled in by the pubsub starter.
=> fix(deps): Remove redundant dependencies

.kokoro/publish_javadoc.sh
Cherrypicked from https://github.com/spring-cloud/spring-cloud-gcp/pull/2585
=> Fix Javadoc Kokoro Job

spring-cloud-gcp-dependencies/pom.xml, spring-cloud-gcp-samples/pom.xml
One of these days I'll learn to get all of the modules on the first go...
=> fix(releases): Activate release profile in -dependencies module too

.github/workflows/buildAndTest.yaml, spring-cloud-gcp-samples/spring-cloud-gcp-vision-ocr-demo/src/test/java/com/example/VisionOcrSampleIntegrationTest.java
take a peek at the "Checks --> (any integration test log) --> target/site/failsafe-report.html"
=> tests(reporting): Generate aggregate test report for easier browsing

docs/src/main/asciidoc/metrics.adoc, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/metrics/GcpStackdriverMetricsAutoConfiguration.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/README.adoc, spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/src/main/java/com/example/ExampleController.java, spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/src/main/resources/application.properties, spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/src/test/java/com/example/MetricsSampleApplicationIntegrationTests.java, spring-cloud-gcp-starters/spring-cloud-gcp-starter-metrics/pom.xml, spring-cloud-gcp-vision/src/main/java/com/google/cloud/spring/vision/OcrPageRange.java
- Updates metrics sample to fix documentation and make it easier to use
- Moves actuator starter into our metrics starter and updates corresponding section in refdoc
- Adds a link to the metrics sample in the refdoc
- Adds header provider to enable usage metrics for the module
=> Metrics module enhancements

pom.xml, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java
Not quite the M5 I was looking for, but since it's newly out, we can and should upgrade to the latest and greatest.
=> chore(build): Update to spring-cloud-build M5

spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/core/BigQueryTemplateIntegrationTests.java
Randomizes the BigQuery Integration test table name to avoid quota hitting quota limits.
Cherrypick from: https://github.com/spring-cloud/spring-cloud-gcp/pull/2594
=> (Cherrypick) Randomize the table name used in BigQuery test

spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java, spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
=> Firestore - remove dead code

.github/workflows/updateDocs.yaml
Seems I didn't do this right before... Bash is hard.
=> fix bash logic

README.adoc, docs/src/main/asciidoc/README.adoc, docs/src/main/asciidoc/cloudfoundry.adoc, docs/src/main/asciidoc/getting-started.adoc, docs/src/main/asciidoc/logging.adoc, docs/src/main/asciidoc/metrics.adoc, docs/src/main/asciidoc/migration-guide-1.x.adoc, docs/src/main/asciidoc/sagan-index.adoc, docs/src/main/asciidoc/spring-cloud-gcp.adoc, docs/src/main/asciidoc/trace.adoc
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/2296
=> Renames a bunch of Stackdriver Trace/Logging to Cloud Trace/Logging

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/entities/Product.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/entities/Store.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/ProductRepository.java
=> add reference fields to query filter

docs/src/main/asciidoc/core.adoc
Backporting from spring-cloud/spring-cloud-gcp#2613.
=> Document how to make beans refreshable (#2613)

.github/workflows/buildAndTest.yaml, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/java/com/example/PubSubJsonPayloadSampleApplicationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/test/java/com/example/PollingReceiverIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/test/java/com/example/ReceiverIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/test/java/com/example/SenderIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-test/src/test/java/com/example/LocalSampleAppIntegrationTest.java
Splits the `pubsub` module up for faster execution. Takes it from ~15min to ~11-12min.
=> feat(tests): Split pubsub integration tests for faster execution

spring-cloud-gcp-samples/spring-cloud-gcp-config-sample/src/main/java/com/example/HelloController.java, spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/main/java/com/example/ExampleController.java, spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample/src/main/java/com/example/ExampleController.java, spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/main/java/com/example/ExampleController.java
The alerts aren't _wrong_, our samples should be a bit tighter, but they're by no means "high priority"
=> fix(sonar): Fix some sonar-flagged 'high priority' issues

docs/src/main/asciidoc/logging.adoc, spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/TraceIdLoggingEnhancer.java, spring-cloud-gcp-logging/src/main/resources/com/google/cloud/spring/logging/logback-appender.xml, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/TraceIdLoggingEnhancerTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/test/resources/logback-test.xml
=> Add support for trace with async logging

CHANGELOG.adoc
Added a new changelog file, following  #194
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/194
=> Added a changelog file.

CHANGELOG.adoc
=> Add 2.0.0 release details to changelog

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfigurationIntegrationTests.java
Tests have been failing over the weekend
=> fix firestore-emulator test

.github/workflows/sonar.yaml, .mvn/wrapper/maven-wrapper.properties, pom.xml
SonarCloud is now consistently failing with a connection timeout to maven central. Maybe splitting up the steps will help?
Also upgrade Maven wrapper to latest version.
=> Update maven version and SonarCloud config

spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTransactionManager.java
=> Cleanup resources when commit is aborted

spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplateAuditingTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateAuditingTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReaderTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImplTests.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorIntegrationTests.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Add at least one assertion to test cases that are missing them
=> Assert ALL the things... at least once!

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java, spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandler.java, spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerIntegrationTests.java
the CloudSqlOne is unreachable code, and the InterruptedException one points here for more information https://www.ibm.com/developerworks/java/library/j-jtp05236/index.html?ca=drs-#2.1
=> Fix a few 'major' smells that were not NPE related

.github/workflows/updateDocs.yaml, docs/src/main/asciidoc/spring-cloud-gcp.adoc
* Add project version at the top
* remove "SNAPSHOT" from version name for releases
=> Reference documentation improvements

spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java, spring-cloud-gcp-security-firebase/src/main/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoder.java
Fixes https://sonarcloud.io/project/issues?id=GoogleCloudPlatform_spring-cloud-gcp&issues=AXZNaeudhMoO4rKzKcD-&open=AXZNaeudhMoO4rKzKcD- in the first commit 
and 
https://sonarcloud.io/project/issues?id=GoogleCloudPlatform_spring-cloud-gcp&issues=AXZNafzahMoO4rKzKcP9&open=AXZNafzahMoO4rKzKcP9 in the second
=> Fix some SonarCloud bugs

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/config/GoogleConfigPropertySourceLocatorTest.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/UserAgentHeaderProviderIntegrationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubChannelAdaptersIntegrationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerBootstrapConfigurationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/security/IapAuthenticationAutoConfigurationTests.java, spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplateTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverterTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQueryTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/SpannerStructReadMethodCoverageTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/SpannerWriteMethodCoverageTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/subscriber/PubSubSubscriberTemplateTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapperTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactoryTests.java, spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/filters/GcsDiscardRecentModifiedFileListFilterTest.java
[Chained AssertJ assertions should be simplified to the corresponding dedicated assertion](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS5838&rule_key=java%3AS5838)
=> Lots of chained AssertJ fixes - part 1

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfigurationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/logging/StackdriverLoggingAutoConfigurationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/ParallelDatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/it/SpannerTemplateIntegrationTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/event/AfterExecuteDmlEventTest.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/event/BeforeExecuteDmlEventTest.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryImplTests.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java, spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsInboundFileSynchronizerTests.java
See [part 1](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/278) for reference
Rule: [Chained AssertJ assertions should be simplified to the corresponding dedicated assertion](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS5838&rule_key=java%3AS5838)
=> Lots of chained AssertJ fixes - part 2

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversions.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTemplate.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/admin/SpannerSchemaUtils.java
[Ternary statements shouldn't be nested](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS3358&rule_key=java%3AS3358) x 4 (major smells)
=> Unwind nested ternary statements

spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerMutationFactoryImpl.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTemplate.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/admin/SpannerSchemaUtils.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReader.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerCompositeKeyProperty.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContext.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImpl.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContextTests.java
Add additional null checks for Spanner module.
=> Add additional null checks for Spanner

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/LazyUtil.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversions.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/admin/SpannerDatabaseAdminTemplate.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategy.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryMethod.java, spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubTemplate.java, spring-cloud-gcp-storage/src/main/java/com/google/cloud/spring/storage/GoogleStorageResource.java
Commit 1: [Collapsible "if" statements should be merged](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS1066&rule_key=java%3AS1066)
Commit 2: ["entrySet()" should be iterated when both the key and value are needed](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS2864&rule_key=java%3AS2864)
Commit 3: [Unused "private" fields should be removed](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS1068&rule_key=java%3AS1068) <-- this one looks bizaare because the mapping context is (was) asserted to be not null and then never used again.
=> Three small-count smells

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java, spring-cloud-gcp-security-firebase/src/main/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoder.java
I think it was a bit of force fitting some Functional magic in where a simpler solution is a little more understandable. Also fixes a SC identified issue.
=> Refactor fancy functional fluent flow

spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/SpannerConverters.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImpl.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategy.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
Fixes the remaining NPE in the Spanner module.
=> Fix remaining Spanner Null Pointer Errors

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/kms/GcpKmsAutoConfiguration.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicator.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java, spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/TraceIdLoggingWebMvcInterceptor.java, spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/PubSubAdmin.java, spring-cloud-gcp-security-iap/src/main/java/com/google/cloud/spring/security/iap/AudienceValidator.java
Removes unnecessary throw exceptions. Or throws a more specific exception if possible.
=> Remove unnecessary `throw exception`

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java, spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreReactiveOperations.java, spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
[Unused type parameters should be removed](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS2326&rule_key=java%3AS2326)
=> Remove unused generic declarations

spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImpl.java, spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
Split them out into their own commits for easier review.
Rule: [Cognitive Complexity of methods should not be too high](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS3776&rule_key=java%3AS3776)
=> Reduce cognitive complexity of a few classes

.github/workflows/sonar.yaml, .github/workflows/unitTests.yaml
Forgot to add these lines that make the retry steps possible
=> add missing continue on error

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TransactionalTemplateService.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubEmulator.java
["Thread.sleep" should not be used in tests](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS2925&rule_key=java%3AS2925)
=> No Thread.sleep() in tests

spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
Fixes [Test methods should not contain too many assertions](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS5961&rule_key=java%3AS5961) (had 39)
=> Fix up ConverterAwareMappingSpannerEntityProcessorTests

spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TransactionalTemplateService.java
[Test methods should not contain too many assertions](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS5961&rule_key=java%3AS5961) - this one had 58.
Glad to be done with these kind of code smells. They're brutal
=> Break up monster Datstore integration test

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/logging/StackdriverLoggingAutoConfiguration.java, spring-cloud-gcp-cloudfoundry/src/main/java/com/google/cloud/spring/cloudfoundry/GcpCloudFoundryEnvironmentPostProcessor.java, spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/DefaultCredentialsProvider.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverter.java, spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntityImpl.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReader.java, spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java, spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/publisher/PubSubPublisherTemplate.java, src/checkstyle/checkstyle-suppressions.xml
This gets some of the ["@Deprecated" code should not be used](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS1874&rule_key=java%3AS1874) violations, but not all of them. I've noted which ones I think are breaking changes for our users in the comments of each one: https://sonarcloud.io/project/issues?id=GoogleCloudPlatform_spring-cloud-gcp&resolved=false&rules=java%3AS1874
=> Reduce usage of deprecated classes

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfiguration.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfiguration.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTransactionManager.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/LazyUtil.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverter.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContext.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/util/SliceUtil.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/AbstractDatastoreQuery.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQuery.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTransactionManager.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/CommitTimestamp.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQuery.java, spring-cloud-gcp-vision/src/main/java/com/google/cloud/spring/vision/DocumentOcrResultSet.java
Bunch of quick fixes for rules that only have a few instances
=> Small n easy fixes

docs/src/main/asciidoc/README.adoc
Addressing https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/264#issuecomment-782169786.
@ttomsu I'm not really sure why we have a readme in /docs and how are we supposed to use it.
=> update BOM version in /docs readme

pom.xml, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTemplate.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java, spring-cloud-gcp-dependencies/pom.xml
Bump up the GCP libraries dependency versions.
=> Upgrade GCP Library Versions

docs/src/main/asciidoc/spring-stream.adoc, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/properties/PubSubConsumerProperties.java, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/resources/application.properties
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/181
=> Allow specifying a custom subscription as a consumer endpoint

.github/workflows/integrationTests.yaml
=> Add IT name to integration test cache

pom.xml
=> Fix SpannerRepositoryInsertIntegrationTests by restoring #92

CHANGELOG.adoc, docs/src/main/asciidoc/spring-integration-pubsub.adoc
I'll copy those into the github release once merged.
=> Add release notes for 2.0.3

docs/src/main/asciidoc/spring-integration-pubsub.adoc, docs/src/main/asciidoc/spring-stream.adoc
Fix broken snippet in Spring Cloud Stream docs for Pub/Sub.
=> Fix pub/sub stream doc

CHANGELOG.adoc, spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java, spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java, spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java, spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java
=> Support OrderBy in method name when querying data in Firestore

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java, spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/CachingPublisherFactory.java, spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/CachingPublisherFactoryTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactoryTests.java
Follow-up to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/548#discussion_r675838380.
=> Refactor DefaultPublisherFactory caching

spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SingerRepository.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/test/java/com/example/DatastoreSampleApplicationIntegrationTests.java
To fix `DatastoreSampleApplicationIntegrationTests` broke by #551.
=> fix broken sample integration test in datastore.

spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/resources/static/index.html
Quick fix in index.html page instruction for sample.
=> fix typo in sample instruction.

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java
Implement deleteAllById() in SimpleDatastoreRepository and add relevant tests.
Resolves #565
=> Implement deleteAllById() in SimpleDatastoreRepository

spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/test/java/com/example/TraceSampleApplicationIntegrationTests.java
This will unblock other work while we investigate #597.
=> Deflake trace test by working around

spring-cloud-gcp-dependencies/pom.xml
Updates sonatype endpoint references that were missed in #616.
=> Update remaining sonatype endpoints

spring-cloud-gcp-samples/pom.xml
I will look into the issue; in the meantime we have pull requests that can't go in because of the broken build.
=> Rollback #681 for nightly build failure

spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
This PR provides a fix for #687
=> Prevents internal NullPointerException and fixes issue #687

pom.xml, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/admin/SpannerDatabaseAdminTemplateTests.java
Migrated _SpannerDatabaseAdminTemplateTests_ from JUnit4 to JUnit5
=> Migrating one test from JUnit4 to JUnit5 as a sample.

spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-basic-sample/src/main/java/com/example/DatastoreBookshelfExample.java
minor correction to cmd line method prompt for datastore sample.
=> minor correction to cmd line method prompt for datastore sample.

pom.xml, spring-cloud-gcp-samples/pom.xml
upgrades:
- spring-boot: 2.6.0-RC1 to [2.6.1](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.1)
- spring-cloud-build: 3.1.0-RC1 to 3.1.0
=> upgrade spring-cloud-build and spring-boot versions to latest release.

pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
spring-cloud-dependencies 2021.0.0-RC1 to 2021.0.0
spring-cloud-config-dependencies 3.1.0-RC1 to 3.1.0
=> upgrade spring cloud and spring cloud config to latest release version 

spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java
Hi guys, can you please review this - [document](https://docs.google.com/document/d/1YBd8rboFqivy4ag1Sgef7xxtxf3RHNI0kCJ-sS7a7EE/edit?usp=sharing&resourcekey=0-vj_nqsu7RA4xRVR4sSNn9Q) ? I'd really appreciate any sort of feedback :)  
As a sample, I've migrated a test using **ExecutionCondition** changes.
=> sample test upgradation from JUnit4 to JUnit5 using ExecutionCondition

docs/src/main/asciidoc/spanner.adoc
Fixes: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/767
=> docs: explaining the restriction on converters

spring-cloud-gcp-samples/spring-cloud-gcp-bigquery-sample/src/test/java/com/example/BigQuerySampleApplicationIntegrationTests.java
Migrated the integration test to JUnit5.
=> Migrating "BigQuerySampleApplicationIntegrationTests.java" to JUnit5

spring-cloud-gcp-dependencies/pom.xml
#781 requires changes to native support before being updated.
=> Revert libraries bom to 24.0.0

README.adoc, docs/src/main/asciidoc/getting-started.adoc
Add compatibility table with Spring Cloud, Spring Boot and Spring Framework versions to readme and documentation.
resolves #789
=> Add compatible version table to readme and documentation.

.github/workflows/integrationTests.yaml, spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample/src/test/java/com/example/MultipleDataModuleIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample/src/test/java/com/example/MultipleNamespaceDatastoreIntegrationTest.java
Migrated the tests to JUnit5 and created a "multisample" integration test suite which is responsible for running "MultipleDataModuleIntegrationTest.java" in GHA.
=> Migrating "MultipleDataModuleIntegrationTest.java" and "MultipleNamespaceDatastoreIntegrationTest.java" to JUnit5

spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/test/java/com/example/PollingReceiverIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/test/java/com/example/ReceiverIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/test/java/com/example/SenderIntegrationTest.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java
1. PollingReceiverIntegrationTest.java
2. ReceiverIntegrationTest.java
3. SenderIntegrationTest.java
=> Migrating spring-cloud-gcp-integration-pubsub-sample's Integration Tests to JUnit5

docs/src/main/asciidoc/getting-started.adoc
=> fix table columns.

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
=> Close Spanner health check ResultSet to prevent session leak (backport)

docs/src/main/asciidoc/spring-integration-pubsub.adoc
=> fix doc link to PatternMatchUtils.smartMatch (backport)

docs/src/main/asciidoc/getting-started.adoc
Fix column mismatch in doc.
Backports #897.
=> fix table columns (backport)

.mvn/maven.config, docs/pom.xml, pom.xml, spring-cloud-gcp-dependencies/pom.xml, spring-cloud-gcp-native-support/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/pom.xml
=> Remove spring repos (backport)

CHANGELOG.adoc
Also adds a mention of changed behavior in #934 .
=> Update changelog for 3.1.0 and 2.0.8

README.adoc
Redoing fix contributed in #959 as the repo submitting the PR is deleted before merged in.
Let this link point to our documentation instead.
=> Fix broken link in readme and point to documentation

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/UserAgentHeaderProviderIntegrationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/environment/OnGcpEnvironmentConditionTests.java
Migrated "UserAgentHeaderProviderIntegrationTests.java" and "OnGcpEnvironmentConditionTests.java" to JUnit5
=> Migrating tests to JUnit5

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/datastore/health/DatastoreHealthIndicatorTests.java
=> Migrating "DatastoreHealthIndicatorTests.java" to JUnit5

spring-cloud-gcp-kms/src/test/java/com/google/cloud/spring/kms/KmsTemplateTests.java
Migrated "KmsTemplateTests.java" to JUnit5.
In both "testEncryptPermissionDenied()" and "testEncryptNotFound()", we have nothing to do with decryption, right? The exception thrown is in encryptText() method and for each of the tests we are setting up a new kmsTemplate, so what is the need for decryption?
I've omitted the decryption part for now, please let me know about your thoughts on this.
=> Migrating "KmsTemplateTests.java" to JUnit5

spring-cloud-gcp-kms/src/test/java/com/google/cloud/spring/kms/it/KmsTemplateIntegrationTests.java
*Includes comments on setting up keys for the test
=> Migrating "KmsTemplateIntegrationTests.java" to JUnit5

spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/PubSubAdminTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubTemplateTests.java
1. PubSubAdminTests.java
2. PubSubTemplateTests.java
=> Migrating pubsub tests to JUnit5

spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/health/HealthTrackerImplTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/health/HealthTrackerRegistryImplTests.java
1. HealthTrackerImplTests.java
2. HealthTrackerRegistryImplTests.java
=> Migrating pubsub health tests to JUnit5

spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerPropertySourceIntegrationTests.java, spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerTemplateIntegrationTests.java
1. SecretManagerPropertySourceIntegrationTests.java
2. SecretManagerTemplateIntegrationTests.java
=> Migrating spring-cloud-gcp-secretmanager tests

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicator.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfiguration.java
I missed sonar feedback in #1018.
=> Add missing sonar checkstyle recommendations

pom.xml
=> Turn off option to append URLs (backport)

CHANGELOG.adoc
=> copied changed logs from release notes

spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-reactive-sample/src/main/java/com/example/ReactiveController.java
- Fixes deprecations from newer project reactor API's.
=> Fixes project reactor deprecations

spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserController.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/java/com/example/FirestoreSampleApplicationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/java/com/example/TestUserClient.java
- Validates that #231 works as intended already by adding tests for checking the behavior - if an entity is added without an id, an id is auto-assigned.
=> Validates that issue #231 works as intended

spring-cloud-gcp-dependencies/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#1221
=> Revert "Bump libraries-bom from 26.0.0 to 26.1.0"

docs/src/main/asciidoc/metrics.adoc, docs/src/main/md/metrics.md
Documents the fix for https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1223
=> add metric disambiguation documentation

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
This PR only intends to remove redundant lines in test code by grouping global parameters in `@BeforeEach`.
=> Test code refactorization

spring-cloud-gcp-samples/spring-cloud-gcp-bigquery-sample/src/test/java/com/example/BigQuerySampleApplicationIntegrationTests.java
fix for flaky BigQuery sample IT testcase. Creating table with random name
=> fix: flaky BigQuery sample IT testcase

.github/workflows/sonar.yaml
I think we do want to run Sonar code quality checks on all PRs, even from external contributors.
=> Remove Sonar GHA condition

.kokoro/publish_javadoc11.sh, pom.xml
Changes to docuploader metadata and java-docfx-doclet argument to stay consistent with updated names.
=> chore: update metadata name and projectname for doc generation.

.github/workflows/integrationTests.yaml, .github/workflows/sonar.yaml
- Integration tests: update path to ignore affected by change in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1394#pullrequestreview-1225235833
- Sonar: also disable sonar workflow for generated modules.
=> chore: update folders to ignore in workflows

.github/workflows/sonar.yaml, pom.xml
Closed #1421 in favor of this change:
- ~~Reverts #1416 ignore path change;~~ Done in #1447
- Instead add file pattern exclusions to sonar properties. Refer to "File exclusion and inclusion" section in sonarcloud guide [here](https://docs.sonarcloud.io/advanced-setup/analysis-scope/). This setup is tested in #1446.
=> chore(codegen): Fix sonar to exclude in jacoco

.kokoro/stage.sh
Triggered a staging without `AUTORELEASE_PR` environment variable (so only staging is done). Will merge this PR if it goes all well.
Job: https://fusion2.corp.google.com/invocations/a7365c1e-1ece-4ad4-82d2-1fbf567168a2/targets
=> chore: Modifying stage job

.github/workflows/codeql-analysis.yml, .github/workflows/updateDocs.yaml
- Set Java version to Java 17 in codeql-analysis.yaml
- Set Java version to Java 17 in updateDocs.yaml
=> chore: Update java version in github workflow

docs/src/main/asciidoc/getting-started.adoc
add Spring version compatibility for 4.x
=> chore(doc): add Spring version compatibility

versions.txt
Important: Please do not edit `versions.txt` manually.
=> chore: revert changes to versions.txt

spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-basic-sample/src/main/java/com/example/Book.java, spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-basic-sample/src/main/java/com/example/BookController.java
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1502
=> chore: remove cross-site scripting

.kokoro/stage.cfg
Increases timeout for stage.sh from default.
=> chore: set longer timeout for releases

spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql/pom.xml
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1577
=> chore(dep): change mysql connector maven coordinate

docs/src/main/asciidoc/secretmanager.adoc, docs/src/main/md/secretmanager.md
=> bugfix: fix `secret-manager` docs

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/TraceAutoConfigurationFilter.java, spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/spring.factories, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/TraceAutoConfigurationFilterTests.java
=> bugfix: disable `ZipkinAutoConfiguration`

spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
=> fix: provide setters for min/max duration per ack ext

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessor.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessorTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/test/java/com/example/SqlR2dbcPostgresSampleApplicationIntegrationTests.java
=> fix: enable-iam-r2dbc in `3.x`

docs/src/main/asciidoc/datastore.adoc, docs/src/main/md/datastore.md, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreOperations.java, spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplateTests.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTransactionTemplateTests.java
=> feat: add support for insert and insertAll in DatastoreOperations (backport #1729)

.kokoro/stage.sh
3.x fix to retry https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1767.
=> chore: fix release script comment

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfigurationUnitTests.java, spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerTemplate.java, spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerTemplateTests.java
=> fix: use core id provider as backup provider

spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/README.adoc, spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample/README.adoc
=> chore: fix typo in README (backport of #1828)

spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
File was created in #966, most recent change #1871.
=> chore: add missing license header

spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
File was created in #966, most recent change #1871.
=> chore: add missing license header (backport #1872)

.mvn/wrapper/maven-wrapper.properties
Reverts GoogleCloudPlatform/spring-cloud-gcp#1981
we suspect this is causing issues on #1971
=> Revert "chore(deps): update dependency maven to v3.9.3 (main)"

spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1996
@meltsufin
=> fix: timestampNanos field with nanos precision.

spring-cloud-generator/README.md, spring-cloud-generator/scripts/generate-showcase.sh, spring-cloud-generator/scripts/generate-steps.sh
* Update local development documentation for `spring-cloud-generator`
* Tweak sed syntax in script for compatibility with MacOS ([workflow run](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/5524539748))
=> chore: update generator scripts and instructions for local development

spring-cloud-gcp-autoconfigure/pom.xml, spring-cloud-gcp-dependencies/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql/pom.xml
This will resolve https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2049.
=> deps: Manually bumping `cloud-sql-socket-factory.version` from `1.12.0` to `1.13.1`

spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/main/java/com/example/ReceiverConfiguration.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/main/java/com/example/SenderConfiguration.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/main/resources/application.properties, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/java/com/example/PubSubJsonPayloadSampleApplicationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/java/com/example/PubSubJsonPayloadTestConfiguration.java, spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/resources/application-test.properties
Similar to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2085
=> chore: prepare pubsub integration json sample tests for parallel runs

.github/workflows/renovate.yml, renovate.json
This PR aims to create a workflow to run renovate-bot on both branches hourly.
=> chore: workflow for renovate action

.github/workflows/integrationTests.yaml, spring-cloud-gcp-samples/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/spring-cloud-gcp-kotlin-app-sample/src/test/kotlin/com/example/RegistrationKotlinSampleApplicationIntegrationTests.kt
This is intended to fix a vulnerability brought by [b/296915631](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/b/296915631). The fix is about [SQL_WEAK_ROOT_PASSWORD](http://vulnstore/#advisories&expand=true&q=publisher:SHA+reference:SQL_WEAK_ROOT_PASSWORD)
=> chore: add secure password to root user in mysql CI db

spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/config/ExtendedBindingHandlerMappingsProviderConfiguration.java, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/config/PubSubBinderConfiguration.java, spring-cloud-gcp-pubsub-stream-binder/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
=> fix: Ensure proper merging of Binder default props

spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/config/ExtendedBindingHandlerMappingsProviderConfiguration.java, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/config/PubSubBinderConfiguration.java, spring-cloud-gcp-pubsub-stream-binder/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Backport of #2177.
Fixes #2151.
=> fix(3.x): Ensure proper merging of Binder default props

spring-cloud-gcp-dependencies/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2166
=> Revert "deps: bump com.google.cloud:libraries-bom from 26.22.0 to 26.23.0"

.github/workflows/integrationTests.yaml, spring-cloud-gcp-samples/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/spring-cloud-gcp-kotlin-app-sample/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/spring-cloud-gcp-kotlin-app-sample/src/test/kotlin/com/example/RegistrationKotlinSampleApplicationIntegrationTests.kt, spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/test/java/com/example/SqlPostgresSampleApplicationIntegrationTests.java
=> chore(3.x): add secure password to root user in mysql CI db

.github/workflows/integrationTests.yaml, spring-cloud-gcp-samples/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/test/java/com/example/SqlPostgresSampleApplicationIntegrationTests.java
=> chore: SQL testing cleanup

spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfiguration.java
=> fix: guard against null projectId in Firestore routing header

.github/workflows/NativeTests.yaml, spring-cloud-gcp-samples/pom.xml, spring-cloud-gcp-samples/spring-cloud-gcp-bigquery-sample/src/test/java/com/example/BigQuerySampleApplicationIntegrationTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-bigquery-sample/src/test/java/com/example/TestResourcesRuntimeHints.java
This pr adds runtime hints for resources used in test and add this sample test to native ci
=> chore: add bigquery sample to native ci.

.github/workflows/updateDocs.yaml, docs/src/main/asciidoc/ghpages.sh
In this PR:
- Fix: #2372 
- Code refactor
=> feat: only commit change if it's not a snapshot version

README.adoc
=> docs: fix readme to reflect Spring Boot 3.0.x & 3.1.x compatibility

SECURITY.md
=> chore: Update SECURITY.md on supported versions.

spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2413
=> Revert "deps: bump spring-cloud-config.version from 4.0.4 to 4.1.0"

spring-cloud-gcp-samples/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2378
=> Revert "deps: bump org.springframework.boot:spring-boot-starter-parent from 3.1.5 to 3.2.0"

docs/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2410
=> Revert "fix(deps): update dependency org.springframework.cloud:spring-cloud-build to v4.1.0"

.github/dependabot.yml, .github/release-please.yml, .github/workflows/NativeTests.yaml, .github/workflows/integrationTests.yaml, .github/workflows/renovate.yml, .github/workflows/scripts/native-image-tests.sh, .github/workflows/sonar.yaml, .github/workflows/unitTests.yaml
Plan:
* Merge this.
* Create 4.x branch.
* Open breaking change PR to update to Spring Cloud 2023 and Spring Boot 3.2
=> ci: setup for 4.x branch

SECURITY.md
=> docs: Update SECURITY.md for 5.x

docs/src/main/asciidoc/getting-started.adoc
=> docs: update compatibility table in docs

spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/LoggingAppender.java, spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/LoggingAppenderTests.java
Support setting logDestinationProjectId.
Fixes: #2496.
=> fix: delegate to all parent logging options

pom.xml
Reverting https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2554 .
=> chore: Adding back `spring-cloud-previews` to release profile.

README.adoc
Update documentation/javadoc versions on readme to latest.
This is a onetime fix. For release-please fix, tracking in #2697
=> chore: Update README.adoc on doc versions

docs/src/main/asciidoc/memorystore.adoc
=> chore: Update memorystore doc 4.x

.github/workflows/showcaseTests.yaml
temp disabling this workflow until #2214 is fixed
=> chore: temp disable showcase workflow.

spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryJsonDataWriter.java
=> fix: Use specified bigQueryWriteClient when creating JsonStreamWriter

spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerIntegrationTests.java
=> chore: randomize testing tables

spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentEntityImpl.java, spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentEntityImplTests.java
=> fix(datastore): guard against "Type must not be Null"

spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryJsonDataWriter.java, spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryTemplate.java, spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/BigQueryTemplateTest.java
=> fix: BigQueryTemplate now closes its BigQueryJsonDataWriter

spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2818
=> Revert "deps: bump spring-cloud-config.version from 4.0.4 to 4.1.1"

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
=> test: fix PubSubAutoConfigurationIntegrationTests resource ALREADY_EXISTS

spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfigurationTests.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContext.java, spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/typeadapter/InstantTypeAdapter.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReaderTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java, spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/typeadapter/InstantTypeAdapterTest.java
Integration test continuation of #2841
Author: @ablx
=> feat: #2576 Add spring-cloud-gcp-data-spanner support for Instant values (@ablx)

docs/src/main/asciidoc/spanner.adoc
=> docs: spanner support for float32 type

docs/src/main/asciidoc/pubsub.adoc, docs/src/main/asciidoc/spring-stream.adoc, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/properties/PubSubConsumerProperties.java, spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java, spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-functional-sample/spring-cloud-gcp-pubsub-stream-functional-sample-sink/src/main/resources/application.properties
Original PR #2894
Author: @jmitash
* Add properties for Binder expiration policy
* Set Expiration Policy when creating Subscription
* Treat non-positive durations as "never expire"
=> feat: configurable expiration policy on auto-created subscriptions (#2876) (@jmitash)

.github/workflows/NativeTests.yaml
Update native image testing to use graalvm-community 21
=> ci: update native image test version to graalvm-community 21

spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/subscriber/PubSubSubscriberTemplate.java, spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/subscriber/PubSubSubscriberTemplateTests.java
* fix: check for exception when parsing pub sub response and return it (#2696 )
=> fix: check for exception when parsing pub sub response and return it (#2696)

docs/src/main/asciidoc/getting-started.adoc
This statement was added in project README but not in this doc page.
ref: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2990
=> fix(doc): update compatibility statement for doc

spring-cloud-gcp-dependencies/pom.xml
Manually update libraries-bom to v26.48.0 as dependabot runs at night.
=> fix(deps): update dependency com.google.cloud:libraries-bom to v26.48.0

spring-cloud-gcp-autoconfigure/pom.xml, spring-cloud-gcp-bigquery/pom.xml, spring-cloud-gcp-data-datastore/pom.xml, spring-cloud-gcp-data-firestore/pom.xml, spring-cloud-gcp-data-spanner/pom.xml, spring-cloud-gcp-kms/pom.xml, spring-cloud-gcp-logging/pom.xml, spring-cloud-gcp-pubsub/pom.xml, spring-cloud-gcp-secretmanager/pom.xml, spring-cloud-gcp-security-iap/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-firestore/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-metrics/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgres-r2dbc/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgresql/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-trace/pom.xml, spring-cloud-gcp-vision/pom.xml
=> chore: revert exclude commons logging from artifacts.

.github/workflows/sonar.yaml, .kokoro/common.sh
=> fix: sonar build 401 issue

spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/ComplianceSpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/ComplianceSpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/IdentitySpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/IdentitySpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/MessagingSpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/MessagingSpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/SequenceServiceSpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/SequenceServiceSpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/TestingSpringAutoConfiguration.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/TestingSpringProperties.java, spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/package-info.java, spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/EchoSpringPropertiesFull.golden, spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/SpringPackageInfoFull.golden
see context: https://github.com/googleapis/sdk-platform-java/pull/3513, https://github.com/googleapis/sdk-platform-java/issues/3547
=> test: Update the golden files' copyright to 2025

.github/workflows/NativeTests.yaml
backport https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3476
=> chore: update native tests actions/upload-artifact to v4. (#3476)

README.adoc
javadoc are out
This should also close #3412
=> chore: update readme to point to new releases

README.adoc
This is release-related housekeeping. Whenever we release new versions, we need to update the readme accordingly.
=> docs: Update README.adoc with latest released versions

spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/LoggingAppenderTests.java
In this PR:
- Change logback default flush level, see https://github.com/googleapis/java-logging-logback/pull/1441 for more information.
=> fix(test): change logback default flush lev

spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/LoggingAppenderTests.java
=> fix(test): change logback default flush lev (#3627)

.github/workflows/generateAutoConfigs.yaml
Based on https://github.com/googleapis/google-cloud-java/pull/11498
=> chore: update permissions of autoconfig generation job

.github/workflows/unitTests.yaml, .kokoro/drop.sh, .kokoro/promote.sh, .kokoro/publish_javadoc.sh, .kokoro/stage.sh, pom.xml, spring-cloud-gcp-dependencies/pom.xml, spring-cloud-gcp-starters/spring-cloud-gcp-starter-config/pom.xml
=> chore: cleanup release scripts to prepare for migration to internal

spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java, spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Backport of #3717.
Fixes: #3694 for 5.x branch.
=> fix(backport): producer destination: ensure topic exists or create one, only if auto create resource is true

.github/workflows/updateDocs.yaml
For https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3787
=> chore(3.x): update doc permissions

.github/workflows/updateDocs.yaml
Similar to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3695
=> chore(4.x):  grant permission to doc jobs

.github/workflows/updateDocs.yaml
Similar to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3695/files
=> chore(5.x): update permissions in docs job

.kokoro/stage.sh
=> chore: fix syntax error in the release script

pom.xml
minor cleanup of unused property after #3796
=> chore: minor cleanup of properties used for java version.

spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsStreamingMessageSourceTests.java
=> fix: mock OffsetDateTime

pom.xml, spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsStreamingMessageSourceTests.java
=> fix: make mock blobs created only once

.github/workflows/NativeTests.yaml
do not merge until https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3860
=> test: add native tests for GraalVM for JDK 24

README.adoc
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3837#discussion_r2208831904
=> docs: fix versions mismatch in README.adoc

docs/src/main/asciidoc/sql.adoc, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/DatabaseType.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java, spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/GcpCloudSqlProperties.java, spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
backport https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/4123 to 6.x
=> chore: backport https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/4123 to 6.x
