- pom.xml
- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java
- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/test/java/com/example/CloudSqlJpaSampleApplicationTests.java
This PR upgrades the project to Ilford.
Since Spring Cloud GCP is no longer included in the Spring Cloud BOM for Ilford, we can actually use the Spring BOM ourselves in our parent POM.
The version of Sleuth is being overwritten to the old one because the new one causes our integration tests to fail.
> Use Ilford Spring Cloud BOM

- .github/workflows/buildAndTest.yaml
- .mvn/maven.config
- spring-cloud-gcp-samples/pom.xml
A few things here:
1. This only runs integration tests guarded by `it.storage` (will start adding more next)
1. Moved non-essential _maven_ details like bucket names into the `integration-test` profile, which feels like a nice place to put it without getting in the way of the sample itself.
1. Makes maven multi-threaded by default, not just in CI (`-T 1.5C` means use _1.5*numCPU_ of threads during a parallel build) 
Side note: I think I'm seeing some Integration tests starting up in-memory emulators during the unit test phase, so we may want to add `-Dtest=!**/*IntegrationTest*"` to the UnitTest step, though I would prefer to keep a local `mvn test` as similar as possible to the CI `mvn test`
> actions: Adds job to run integration tests

- .github/workflows/buildAndTest.yaml
- .mvn/maven.config
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/test/java/com/example/PubSubBinderSampleAppIntegrationTest.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/test/java/com/example/PubSubSampleApplicationIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/src/test/java/com/example/PubSubStreamBinderSampleAppIntegrationTest.java
It appears that the PubSub integration tests are the reason we can't run everything in parallel. We may be able to sink some effort into making them more thread safe (removing external dependencies, maybe removing some of the standard out redirects?, marking everything as `@DirtiesContext`). 
A few more runs with this enabled may show how much time we could save by fixing pubsub and re-enabling parallel builds (which in turn test in parallel). Without Pubsub, unit + integration tests can run as fast as [4min 24sec](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/126264301)
> tests: Enable pubsub integration tests

- .github/workflows/buildAndTest.yaml
Lots of testing out why things weren't working and turned out to be something as simple as the `beta` components weren't installed.
> tests: Reenable pubsub-emulator integration tests

- .github/workflows/buildAndTest.yaml
Two changes here:
1. Found the `always()` function that ensures the logs are actually saved, even if the job (or step) fails
2. The copious amount of Maven occasionally causes the GitHub Javascript to slow to a crawl - and most of it zooms by too fast to be useful. Found the Maven option to redirect all test stdout to files that are then archived afterward for viewing.
> actions: Redirect stdout to file and always save it

- .github/workflows/buildAndTest.yaml
This action queries GHActions endpoint to ensure only one integration test is running at a time (or at least I hope it does). This should help prevent integration tests stomping on each other's shared resources.
> tests: One at a time integration tests

- spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/logging/StackdriverLoggingAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubEmulatorAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java
Using the handy [maven-build-scanner](https://github.com/intuit/maven-build-scanner) I was able to identify the `spring-cloud-gcp-autoconfigure` as the bottleneck in our unit test build. Not only is it the bottleneck, it also is the source of a number of stacktrace outputs (that, in general, [look like bugs](https://github.com/spring-cloud/spring-cloud-gcp/issues/1892) and should try to be avoided).
This PR copies over the mocked `googleCredentials()` method in various places to return a mock Credential, therefore preventing a network call to the (absent) Metadata server. With no failing network call, there is also no errant stack traces. 
But wait, there's _MORE!!_
Removing these network calls _also_ shaves the bottleneck `test` phase from 34s --> 17s. Here's what the build scan now …
> tests: Removes various unnecessary network calls

- .github/workflows/buildAndTest.yaml
- docs/pom.xml
- pom.xml
- spring-cloud-gcp-data-firestore/pom.xml
- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/test/java/com.example/LoggingSampleApplicationIntegrationTests.java
A few things in this PR:
1. `./mvnw test` now only runs unit tests
1. `./mvnw verify` now runs both unit tests and integration tests. The `-Dit.whatever` flags still guard the test from actually running.
1. Two new options, `skip.surefire.tests` and `skip.failsafe.tests`, were added to control unit/integration tests independently. For the CI job(s), we're running only one or the other. (Context: it appears the documented `-DskipTests` and `-DskipITs` don't mesh well together, so I found this option suggested somewhere on stackoverflow, and it works nicely. `-DskipTests` still works to skip _all_ tests). 
1. Fixed some warnings maven kept complaining about 
1. Added an explicit version for the `maven-deploy-plugin` 
1. Removed duplicate dependency listing
1. Extended the logging …
> tests: Use failsafe plugin, fix maven missing-version warnings

- pom.xml
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-pubsub-stream-binder/pom.xml
- spring-cloud-gcp-samples/pom.xml
Apparently the spring-cloud-build snapshot name is now `3.0.0-SNAPSHOT`.
See: https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-build/
> Fix spring-cloud-build snapshot version name

- README.adoc
- docs/src/main/asciidoc/README.adoc
- pom.xml
- spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/support/DatastoreRepositoryFactory.java
- spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/support/SpannerRepositoryFactory.java
- spring-cloud-gcp-dependencies/pom.xml
Should fix the build for the repo.
The Ilford snapshot of `spring-data-commons` introduces a new method to implement for our spring-data modules.
```
QueryMethodEvaluationContextProvider.getEvaluationContext(T parameters, Object[] parameterValues, ExpressionDependencies expressionDependencies)
```
This adds the method implementation.
Also, `https://repo.spring.io/snapshot` appears to be the snapshot repo we should be relying on; the old repo location was missing some dependencies.
> Fix build for the Ilford version upgrade

- pom.xml
- spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQueryTests.java
- spring-cloud-gcp-samples/pom.xml
Reenable the junit tests by adding the junit4 vintage engine dependency.
Fixes #39.
> Re-enable JUnit 4 tests

- spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/TestDatastoreItemCollections.java
- spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/it/DatastoreIntegrationTests.java
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/51
This fixes the compilation as well as a flaky datastore test. The pubsub test failed once with an NPE, which prompted the other change. Only the pubsub integration tests are failing now (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/43).
> fix(build): Fix compilation error and attempt to fix some flaky tests.

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-client/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-client/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-server-local/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/spring-cloud-gcp-pubsub-bus-config-sample-test/src/test/java/com/example/LocalSampleAppIntegrationTest.java
with Spring Boot 2.4
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/43
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/53
1.) Upgrades pinned Spring Cloud Config server to the 3.0.0-SNAPSHOT (we've had recent discussions about whether we should be doing this, but since we're being pulled along with the Spring Boot 2.4-SNAPSHOT this needed to be upgraded too)
2.) Adds the `actuator` project to the sample so that I could ping `/actuator/refresh` manually and see the client refresh the value. Not strictly needed but was valuable for debugging.
3.) Added `spring.config.use-legacy-processing=true` to follow what @spencergibb did in his tests in the cloud config repo. I think in theory this shouldn't be necessary but it doesn't work without it right …
> fix(tests): Bring Config server in Pubsub integration test up to date

- .github/workflows/buildAndTest.yaml
Two big reasons for this:
1.) Since we're based on SNAPSHOTs right now, we don't know what's changing underneath us. If we don't commit for several days (or weeks) it's harder for the first person to narrow down what broke and when it started.
2.) Also since we're based on SNAPSHOTs, new JARs are downloaded on the first go and are cached. This randomly fails sometimes for a human so this warms up the cache a bit before the development day.
> builds(): Build and test every day at 5:30AM

- .github/workflows/buildAndTest.yaml
I *think* this should work - the [documentation says](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule) scheduled runes do not have an `event` payload.
> fix(test): Run integration tests as part of nightly build and test

- .github/workflows/buildAndTest.yaml
Java 15 was released to GA on [Sept 15, 2020](https://openjdk.java.net/projects/jdk/15/).
> builds(java): Java 14 --> 15

- pom.xml
There's a lot of maven cruft in this PR - I removed the root POM's parent and transferred over several of the plugins + their properties (and then sorted them). I'm not a maven expert (yet... coming close it seems), so I'm not 100% sure this does what I think it does, but it does feel more "composition over inheritance"-y. 
Question: There were a few PRs out recently around checkstyle and whatnot, but I also recall seeing something about using Google's checkstyle, which IIRC is more relaxed than the Spring/Pivotal one. Since this is now a Google repo I'd probably opt to follow `GoogleCloudPlatform` standards rather than Pivotals, though I don't feel strongly about it. So... **which checkstyle should we be using?**
> feat(pom): Remove dependency on spring-cloud-build POM

- .github/workflows/buildAndTest.yaml
I noticed that the `actions/cache` wasn't actually doing anything on a recent failed run because v1 didn't support scheduled runs, defeating the purpose of running it periodically. So I updated all GH-provided actions to their latest release, and then disabled scheduled runs on forks (because when it failed, it usually failed on my branch, the upstream branch, or both, and that was annoying).
> Update GHActions to latest versions, stop scheduled runs on forks.

- .github/workflows/buildAndTest.yaml
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> feat(builds): Enable manual GHA runs

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-reactive-sample/src/test/java/com/example/ReactiveReceiverApplicationIntegrationTest.java
Porting from 1.2.x: Make Pub/Sub integration tests less flaky (https://github.com/spring-cloud/spring-cloud-gcp/pull/2546)
> (forwardport): Make Pub/Sub integration tests less flaky

- pom.xml
Error from release:
```
[ERROR] Rule failure while trying to close staging repository with ID "comgooglecloud-2391".
[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] Repository "comgooglecloud-2391" failures
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no javadoc jar found in folder '/com/google/cloud/spring-cloud-gcp-data-spanner/2.0.0'
[ERROR]     * Missing: no javadoc jar found in folder '/com/google/cloud/spring-cloud-gcp-data-firestore/2.0.0'
[ERROR]     * Missing: no javadoc jar found in folder '/com/google/cloud/spring-cloud-gcp-security-iap/2.0.0'
[ERROR]     * Missing: no javadoc jar found in folder '/com/google/cloud/spring-cloud-gcp-storage/2.0.0'
[ERROR]     * Missing: no javadoc jar found in …
```
> Add javadoc and source modules, which are required to release

- .kokoro/build.sh
- .kokoro/common.sh
- .kokoro/drop.sh
- .kokoro/promote.sh
- .kokoro/publish_javadoc.sh
- .kokoro/release_snapshot.sh
- spring-cloud-gcp-samples/pom.xml
Step 1 when debugging Korkoro jobs - it's nice to know what exact command it's failed on, but without revealing any secrets. `set -v` shows what command is running without evaluating those variables, like `set -x` would, so things like `${GPG_PASSPHRASE}` should not be exposed.
Step 2: the latest job failed because it could not `nexus-staging:drop` on the code samples (yet another example of not having a strict hierarchy is a PITA):
```
...
[INFO] Spring Cloud GCP Pub/Sub Starter ................... SUCCESS [  0.001 s]
[INFO] Spring Cloud GCP Code Samples ...................... FAILURE [  5.839 s]
[INFO] Spring Cloud GCP Runtime Configuration Code Sample . SKIPPED
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] …
```
> Add nexus-staging plugin to samples, but skip it

- spring-cloud-gcp-samples/pom.xml
(*super annoyed*)
From failed logs:
```
[INFO] Spring Cloud GCP Metrics Code Sample 2.0.0-SNAPSHOT  FAILURE [  0.004 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:08 min
[INFO] Finished at: 2020-10-13T05:10:36-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:drop (default-cli) on project spring-cloud-gcp-metrics-sample: Nexus connection problem: Mandatory plugin parameter 'nexusUrl' is missing -> [Help 1]
[ERROR] 
```
> Add required configs to plugin that we're trying to skip 

- .github/workflows/buildAndTest.yaml
- .mvn/jvm.config
- spring-cloud-gcp-dependencies/pom.xml
Followup of spring-cloud/spring-cloud-gcp#2489.
- spring-cloud-gcp-dependencies to have the Linkage Checker enforcer plugin in "linkage-check" profile. It's off by default.
- It uses the latest Linkage Checker version 1.5.3, which fixes GoogleCloudPlatform/cloud-opensource-java#1609 and https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1656.
- GitHub Actions on pull requests to run the enforcer plugin
> Linkage Checker configuration as GitHub Actions

- .github/workflows/buildAndTest.yaml
- .kokoro/publish_javadoc.sh
- pom.xml
- spring-cloud-gcp-samples/pom.xml
Added a separate GHActions job to test the `-P release` flow, which generates javadoc and sources Jars, flattens the POM, etc. when preparing for a release.
> chore(pom): Move release-related plugins to release profile, add to GHA CI

- pom.xml
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/UserAgentHeaderProviderIntegrationTests.java
Fixes the regex and moves the class to another module to make sure
that the `getImplementationVersion()` method works.
> Make UserAgentHeaderProviderIntegrationTests run

- pom.xml
Our spanner integration test `SpannerRepositoryInsertIntegrationTests.insertTest` assumes reflection can correctly parse parameter names. Historically, `spring-cloud-build` configured the compiler plugin to turn parameter names on, but now that we have split off, it is useful to do it in spring-cloud-gcp parent pom.
Samples don't need the setting, since `spring-boot-starter-parent` turns the property on.
> Provide reflection with method parameter names

- docs/src/main/asciidoc/bigquery.adoc
- docs/src/main/asciidoc/config.adoc
- docs/src/main/asciidoc/core.adoc
- docs/src/main/asciidoc/datastore.adoc
- docs/src/main/asciidoc/firestore.adoc
- docs/src/main/asciidoc/logging.adoc
- docs/src/main/asciidoc/metrics.adoc
- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/asciidoc/security-iap.adoc
- docs/src/main/asciidoc/spanner.adoc
- docs/src/main/asciidoc/spring-cloud-bus-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-storage.adoc
- docs/src/main/asciidoc/spring-stream.adoc
- docs/src/main/asciidoc/sql.adoc
- docs/src/main/asciidoc/storage.adoc
- docs/src/main/asciidoc/trace.adoc
- docs/src/main/asciidoc/vision.adoc
Fixes the Gradle doc syntax to use updated format.
Cherry pick from the `spring-cloud-gcp` 1.x repo: https://github.com/spring-cloud/spring-cloud-gcp/pull/2549
> (Cherrypick) Replace gradle docs with correct syntax

- docs/src/main/asciidoc/spring-stream.adoc
- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinder.java
- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/properties/PubSubConsumerProperties.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderTests.java
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/1432
> Allow setting maxFetchSize on polling stream binder

- docs/src/main/asciidoc/firestore.adoc
- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/it/FirestoreDocumentationIntegrationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/it/User.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java
Seems failsafe (maybe surefire too?) doesn't run when `packaging` is `pom`. After discussing with the team, we agreed to move these last two tests into a real module.
> fix(tests): Re-enable documentation integration tests

- .github/workflows/buildAndTest.yaml
- README.adoc
- docs/pom.xml
- pom.xml
So the doc setup Spring uses is pretty complex. Instead of doing the normal copy-pasting, if we intend to continue publishing to spring.io, we probably need to continue using their exact doc-generating setup. 
Given that we no longer have any _code_ in the `docs` module, we no longer need to pull in everything as a dependency.
A good portion of this PR involves ensuring GitHub actions saves off these newly-generated archives in each run, so take a look at https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/100/checks and download the `Release Artifacts.zip` file to explore what is actually generated:
* `docs/target/generated-docs/reference/html/index.html` 
* `target/site/apidocs/index.html`
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/99
> docs: Have docs module inherit from Spring Cloud pom to get docgen working again

- docs/src/main/asciidoc/migration-guide-1.x.adoc
- docs/src/main/asciidoc/spring-cloud-gcp.adoc
Y'all tell me where I'm wrong, but beyond the package name change and some deprecations being removed, were there any other breaking changes?
> docs(migration): Adds first draft of migration guide for 2.0

- docs/pom.xml
I'm not 100% sure this will do what I intend long-term (i.e don't deploy docs now, but do it later when we need to publish refdocs to Spring) but it should get our Kokoro CI back to green.
> fix(docs): disable docs module deployment to fix kokoro CI

- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryOperations.java
- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryTemplate.java
- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/integration/BigQuerySpringMessageHeaders.java
- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandler.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/core/BigQueryTemplateIntegrationTests.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerIntegrationTests.java
This allows for manually specifying BigQuery schema when a datafile is loaded.
Introducing an overloaded method:
```
ListenableFuture<Job> writeDataToTable(
String tableName, InputStream inputStream, FormatOptions dataFormatOptions, Schema schema);
```
Which allows you to manually specify the `Schema` if you do not want to rely on schema auto-detect and are unable to create the table beforehand.
https://github.com/spring-cloud/spring-cloud-gcp/issues/2576
> Allow for manually specifying BigQuery table schema

- .kokoro/stage.sh
The `verify` stage fails because when `release` is activated it expects the GPG key. I could have added the skip config but I'm sure there's something else in there and we really only need the `release` profile active during the `deploy` invocation.
> fix(release): Don't activate release profile until deploy

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerEmulatorAutoConfiguration.java
Port of https://github.com/spring-cloud/spring-cloud-gcp/pull/2592.
> Support `spring.cloud.gcp.project-id` property for Spanner Emulator config

- .github/workflows/buildAndTest.yaml
This PR adds a conditional retry step for integration tests. Most of our test failures are merely flakes, and restarting the _whole_ tasks adds significant time. A single retry should help smooth out many of these random flakes in shorter time (since we don't have to repeat the `mvn install` or any of the other passing tests.
> feat(integrationTests): Retry integration tests on failure

- docs/pom.xml
- pom.xml
- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/test/java/com/example/TraceSampleApplicationIntegrationTests.java
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-trace/pom.xml
Also fixes a infrequently-flaky test and specified the expected exception in a Trace test.
The `spring-cloud-gcp-autoconfigure/pom.xml ` changes look worse in GH than they really are - there was a zipkin dep under BigQuery instead of Trace, so I shuffled some of them around.
> feat(upgrade): Upgrade to Spring Boot 2.4 and Spring Cloud 2020.0.0-M5

- .github/workflows/buildAndTest.yaml
Fixes some announcement warnings in our GHA workflow, notably:
* `ubuntu-latest` going to 20.04 (since this works, it's not strictly necessary to specify 20.04, but I want the warnings to go away)
* `setup-gcloud` moved to a new repo
> GH Actions Updates

- .github/workflows/updateDocs.yaml
- docs/src/main/asciidoc/ghpages.sh
Tested with `v2.0.0-RC2` ([live now](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.0-RC2/reference/html/index.html)) and `master` (reverted - should update when this PR is submitted. [Current live link](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html)).
My intention is to also have this run automatically whenever a new release is cut. This should be pretty easy with this automation.
> docs(build): Make ghpages.sh script work for our GH Pages

- .kokoro/promote.sh
- .kokoro/stage.sh
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-config/pom.xml
This PR should exclude `spring-cloud-gcp-starter-config` from the GA and future RC releases (but keeps it included in `-SNAPSHOT` releases)
> chore(releases): Exclude RTC starter from GA release

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplateAuditingTests.java
Port of https://github.com/spring-cloud/spring-cloud-gcp/pull/2604.
The new `DatastoreTemplate` instance should have the same
`ApplicationEventPublisher` as the original one, so that `AuditingHandler`
can be called.
> (cherry-pick): Fix auditing when running through DatastoreTemplate.performTransaction

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerBootstrapConfigurationTests.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerPropertySource.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerPropertyUtils.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerTemplate.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerPropertyUtilsTests.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerTemplateTests.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerTestConfiguration.java
Change secret manager module packages to depend on the `v1` library version, not `v1beta`.
> Change secret manager module to use v1 instead of v1beta

- docs/src/main/asciidoc/bigquery.adoc
- docs/src/main/asciidoc/core.adoc
- docs/src/main/asciidoc/datastore.adoc
- docs/src/main/asciidoc/firestore.adoc
- docs/src/main/asciidoc/logging.adoc
- docs/src/main/asciidoc/metrics.adoc
- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/asciidoc/security-iap.adoc
- docs/src/main/asciidoc/spanner.adoc
- docs/src/main/asciidoc/spring-cloud-bus-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-storage.adoc
- docs/src/main/asciidoc/spring-stream.adoc
- docs/src/main/asciidoc/sql.adoc
- docs/src/main/asciidoc/storage.adoc
- docs/src/main/asciidoc/trace.adoc
- docs/src/main/asciidoc/vision.adoc
Fixes primarily gradle packages names in the docs that should be migrated to `com.google.cloud.spring`.
> Fix gradle package names

- spring-cloud-gcp-kms/src/test/resources/logback-test.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-kms-sample/src/test/resources/logback-test.xml
Avoid too verbose `DEBUG` level output.
> Add Logback config for KMS tests

- spring-cloud-gcp-pubsub/pom.xml
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapter.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapterTests.java
The workaround will force the exception in MessageProducerSupport to bubble up without trying to go through message infrastructure, in the scenario where context shutdown is detected. This will prevent losing the exception during shutdown.
Forward port of spring-cloud/spring-cloud-gcp#2617
> Workaround to keep exception from disappearing (#2617)

- docs/src/main/asciidoc/firestore.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfiguration.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestoreClassMapper.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestoreDefaultClassMapper.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntity.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntityImpl.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/UpdateTime.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/transaction/ReactiveFirestoreResourceHolder.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/transaction/ReactiveFirestoreTransactionManager.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/User.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTestsConfiguration.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQueryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/transaction/ReactiveFirestoreTransactionManagerTest.java
Fixes: https://github.com/spring-cloud/spring-cloud-gcp/issues/2498
> Firestore - optimistic locking

- spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/main/resources/logback-spring.xml
Fix the path to the logging appender in our logging sample.
> Fix Logging Sample Appender Path

- docs/src/main/asciidoc/pubsub.adoc
Forward-porting spring-cloud/spring-cloud-gcp#2622
Gax default builder settings [turn off batching](https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/batching/BatchingSettings.java#L115-L117) for every relevant setting.
Our documentation assumed that batching is only controlled by the boolean `spring.cloud.gcp.pubsub.publisher.batching.enabled` property, which is not accurate.
> update docs with correct pubsub batching values (#2622)

- .github/workflows/updateDocs.yaml
Recent bump to 2.0.1-SNAPSHOT failed to update the docs because it couldn't find the `spring-cloud-gcp-depdendencies:2.0.1-SNAPSHOT`, so it looks like we've gotta install it.
Run for reference: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/482978202
> mvn install before updating docs to catch version updates

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
The getters/setters of `usingStreamTokens` does not appear to be used anymore.
> Remove unused getters/setters from FirestoreTemplate

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfigurationIntegrationTests.java
Cherrypick of https://github.com/spring-cloud/spring-cloud-gcp/pull/2625
Fixes #2514.
> (Cherrypick) Firestore emulator will use given project ID if present

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreReactiveOperations.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/PhoneNumber.java
This adds an overloaded `withParent(Object id, Class<?> entityClass)` method so that users are not required to have a reference to an entity to scope the template to some subcollection.
Fixes #206.
> Implement withParent overload for FirestoreTemplate

- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/bootstrap.properties
Try clarifying the usage of `bootstrap.properties` and `application.properties` in the Secret Manager sample by adding both files and sharing what settings can be added to either one.
> Demonstrate usage of bootstrap.properties vs. application.properties in Secret Manager Sample

- docs/src/main/asciidoc/spanner.adoc
Remove the broken link in the Spanner refdocs.
No need to link to the Spanner starter as the artifact is linked directly above.
> Remove broken link in Spanner refdocs

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
This adds an additional null check to FirestoreTemplate to resolve the null pointer exception issue reported by Sonar.
> Add additional null check for FirestoreTemplate

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-source/src/main/java/com/example/FrontendController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-source/src/main/java/com/example/FunctionalSourceApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-source/src/main/java/com/example/Source.java
`Processors` are now deprecated, being replaced by `Sinks` in Reactive 3.5: https://projectreactor.io/docs/core/release/reference/#processors
> Replace deprecated EmitterProcessor with Sinks.Many

- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/application.properties
In `application.properties`, you can set a property to an environment variable and then fallback to using a secret manager secret if the env var is not set via this syntax:
```
example.secret=${MY_ENV_VARIABLE:${sm://application-secret/latest}}
```
Fixes: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/213
This helps enable a use-case asked for in https://github.com/spring-cloud/spring-cloud-gcp/pull/2302#issuecomment-763075877 about allowing an app to be less coupled to a platform -- i.e. rely on ENV vars if provided since it's not guaranteed the app will run on google cloud.
> Add a note in the sample for how to use default values

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderTests.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/PubSubAdmin.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/PubSubTopicUtils.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/PubSubAdminTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/PubSubSubscriptionUtilsTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/PubSubTopicUtilsTests.java
- spring-cloud-gcp-pubsub/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/src/test/java/com/example/PubSubStreamBinderSampleAppIntegrationTest.java
Two commits in here:
1.) Update from deprecated `ProjectTopicName` to `TopicName`
2.) Allow specifying a fully-qualified consumer destination, which allows that destination to be in a different project. To do this, I had to add a public `getProjectId()` to the `PubSubAdmin` object, which simply returns its immutable project ID.
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/232
> Allow pubsub binder to use fully qualified topic name when creating subscription (consumer destination)

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/environment/OnGcpEnvironmentCondition.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/core/environment/OnGcpEnvironmentConditionTests.java
* Added asserts to prevent NPEs.
* Removed deprecated rule in favor of `assertThatThrownBy`.
* Added tests for new asserts, plus one missed test for an old assert.
> Add gating asserts to OnGcpEnvironmentCondition

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQuery.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
There is [one more](https://sonarcloud.io/project/issues?assignees=ttomsu%40github&id=GoogleCloudPlatform_spring-cloud-gcp&open=AXZNafd0hMoO4rKzKcLg&resolved=false) of these that I'm not convinced will always return non-null, but would like some additional eyes to help out.
> Remove expressions that always evaluate to true/false

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
Also avoid processing property placeholders in the `CloudSqlEnvironmentPostProcessor` as they should be processed later.
This enables the use of Secrets Manager property placeholders together with Cloud SQL configuration.
Fixes: #252.
> Skip CloudSqlEnvironmentPostProcessor in bootstrap context

- spring-cloud-gcp-core/src/test/java/com/google/cloud/spring/core/util/MapBuilderTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/reactive/PubSubReactiveFactoryTests.java
- spring-cloud-gcp-security-firebase/src/test/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoderTests.java
- spring-cloud-gcp-security-iap/src/test/java/com/google/cloud/spring/security/iap/AppEngineAudienceProviderTests.java
- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/DocumentOcrResultSetTests.java
From SC: "Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception.
When verifying that code raises a runtime exception, a good practice is to avoid having multiple method calls inside the tested code, to be explicit about which method call is expected to raise the exception."
> Only one invocation in a lambda that throws and exception

- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandler.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerTests.java
This fixes a bug in the `BigQueryFileMessageHandler` where it references the wrong variable in the setter.
Add additional tests.
> Fix BigQuery setter bug and add tests

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java
Fixes critical "smell" found by Sonar:
"Define a constant instead of duplicating this literal 3 times."
> Define a constant instead of duplicating this literal

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/PubSubAdmin.java
Fixes blocker SonarCloud finding:
"Use try-with-resources or close this "TopicAdminClient" in a "finally" clause."
> Cleanup in case of failures in PubSubAdmin constructor

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/storage/GcpStorageAutoConfigurationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplateTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContextTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/DatastoreQueryLookupStrategyTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateTransactionManagerTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContextTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategyTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryImplTests.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandlerTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/GoogleStorageTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/outbound/GcsMessageHandlerTests.java
Not sure I got all of them, but I got a big chunk of them.
[Call to Mockito method "verify", "when" or "given" should be simplified](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS6068&rule_key=java%3AS6068)
> Remove use of excessive Mockito arg matchers

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentEntityInformation.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/DatastoreRepository.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/DatastoreRepositoryFactory.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/DatastoreRepositoryFactoryBean.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/support/FirestoreRepositoryFactoryBean.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/support/ReactiveFirestoreRepositoryFactory.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/util/ObservableReactiveUtil.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/SpannerRepository.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryFactory.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryFactoryBean.java
[Type parameter names should comply with a naming convention](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS119&rule_key=java%3AS119)
> Rename generic types to single letters to comply with convention

- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
We continue to see some (albeit fewer) Maven Central failures, but when we do, the remedy is always to just retry, so lets just retry automatically and save some time.
> Add retry steps in case Maven Central fails for unit tests and Sonar

- pom.xml
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/AbstractSpannerIntegrationTest.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/IntegrationTestConfiguration.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/SpannerTestExecutionListener.java
- src/checkstyle/checkstyle-suppressions.xml
Turns out the DB cleanup code was broken too - fixed that as well.
I suggest reviewing one commit at a time.
Context: Was fixing the error flagged by [Test methods should not contain too many assertions](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS5961&rule_key=java%3AS5961), but this unit test was heavy on the test but not the _unit_ part. It contained 89 assertions in this one method (max is set at 25).
> Break up the monster Spanner integration test

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreReactiveOperations.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
This modifies `FirestoreTemplate.withParent(Object id, Class<?> ..)` to `FirestoreTemplate.withParent(String id, Class<?> ..)`.
Turns out that Document IDs can only be Strings (no longs, ints, custom data types, etc.) https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/217#issuecomment-764008911
Fixes #227
> Modify withParent to accept String only

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContext.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/CommitTimestamp.java
Removes declared RuntimeExceptions, and moves `register` method inside the static class that calls it (SC rule: ["private" methods called only by inner classes should be moved to those classes](https://sonarcloud.io/organizations/googlecloudplatform/rules?open=java%3AS3398&rule_key=java%3AS3398)
> Fix up some smells in CommitTimestamp

- .github/workflows/integrationTests.yaml
- .github/workflows/unitTests.yaml
I should have looked more closely at my change the other day on what step was actually failing. In this case we need to retry the `mvn install` step rather than the unit testing step itself. 
I've removed the unit test retry in this PR because there should be no flaky unit tests - it should always pass in 1 go - whereas we see an occasional failure with Maven central (during the mvn install step)
> Retry mvn install on failure, don't rerun unit tests on failure

- .github/workflows/purgeCache.yaml
I took a peek at our caches and they appear to be growing over time. A fresh install on my machine showed:
```bash
$ du -sh ~/.m2
1.5G	/home/ttomsu/.m2
```
Whereas [our current cache size is double that at 3GB](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/runs/1921577604?check_suite_focus=true#step:4:31).
It took ~1:47 to load our cache, so cutting it half should reduce our build time, and sometimes by more than just the ratio (you can see the speed dropped from 160MB/s to 60MB/s at around 60%, so I imagine a smaller cache will mostly be loaded with the faster bandwidth, if this test is usual). 
We're not the only ones to hit this issue - it's quite literally issue no. 2 in their repo: https://github.com/actions/cache/issues/2, and while they say old cache entries get deleted, …
> Adds periodic cache purge to keep the cache from growing

- .github/workflows/unitTests.yaml
- .github/workflows/warmCache.yaml
Following up from yesterdays conversation about the GHA cache - this changes the "purge cache" job to a "warm cache" job because, as we learned, we cannot _update_ an existing cache - we can only create wholly new ones. 
So this job runs right at the beginning of every day (UTC time, obv, we're not savages after all) and stores the cache based on the YYYY-MM-DD. I've also removed the backup `restore-keys` option as I have no idea what is in this `Linux-maven-` cache. It likely doesn't have much of what we need so lets save the time downloading it.
If this works out as expected I can make similar changes to our other jobs.
> Use date in dependencies cache and refresh daily

- docs/src/main/asciidoc/getting-started.adoc
The existing instructions seemed to refer to times before gradle supported BOMs. Since there is now a go-to way for BOM use built into gradle, it seems counter-intuitive to refer potential users to an out-dated solution.
> Simply suggested BOM use in gradle

- .github/workflows/codeql-analysis.yml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
As mentioned in https://github.com/actions/cache/issues/467, there is a 10GB/5min limit before throttling the cache upload. The bug is because the throttling shouldn't cause the build to fail, which is what we're seeing. We previously had a bunch of jobs all start within 5 minutes of each other, so this change should help avoid hitting the limit.
New schedule:
06:00 UTC (1AM EST/ 2AM EDT) - Sonar (one job caches for this and all unit tests)
07:00 - Unit Tests (Java 8/11/15 reuse Sonar cache)
08:00 - Integration Tests (all create new caches)
09:00 - Linkage check 
CodeQL runs once a week as well as on each merge.
> Stagger nightly GHA jobs to try to avoid hitting cache throttling

- .github/workflows/codeql-analysis.yml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
- .github/workflows/updateDocs.yaml
Moving away from a cache per job and integration test module.
This eliminates a lot of mostly overlapping maven caches, thereby reducing storage space and daily cache write bandwidth from ~30GB to ~1.5GB.
This also allows us to be within the [5GB cache storage limit](https://github.com/actions/cache#cache-limits).
> Set up unified maven cache for GH Actions

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/EmulatorSettings.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreEmulatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreEmulatorAutoConfigurationTests.java
#342 Currently, some properties are missing to propagate from the application properties to Datastore emulator.
I propagate `storeOnDisk` and `dataDir` here and adjust the javadoc. The task supposes to add only the first property but consistency order, I add the second one.
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/342.
> GH-342: Apply additional emulator properties

- docs/src/main/asciidoc/datastore.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/EmulatorSettings.java
Followup to #342 -- Add the new datastore emulator settings to the documentation.
Also fixes the comment to use the [`--store-on-disk`](https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/start) flag which more accurately corresponds to the setting instead of the negative `--no-store-on-disk`.
> Add Datastore emulator settings to documentation

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerOperations.java
Clarify that executeDmlStatement may start a transaction.
Fixes: https://github.com/spring-cloud/spring-cloud-gcp/issues/2650
> Fix javadoc on SpannerOperations.executeDmlStatement

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/subscriber/PubSubSubscriberOperations.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/SubscriberFactory.java
Updates javadocs and reference documentation with a warning.
However, we decided not to deprecate the field for now.
Addresses: #309.
> Add warning about use of `returnImmediately=true`

- docs/src/main/asciidoc/spring-integration-pubsub.adoc
I changed it to inject `PubSubTemplate` instead of `PubSubSubscriberOperations`; turns out there are 2 beans in the environment that implement `PubSubSubscriberOperations` making it non-unique -- `PubSubTemplate` and `PubSubSubscriberTemplate`.
> Fix Pub/Sub Integration Snippet in doc

- .github/workflows/integrationTests.yaml
By default, turntstyle will only block concurrent jobs on the same branch.
That's not what we want.
> Make ITs wait their turn across all branches

- .github/workflows/integrationTests.yaml
- .github/workflows/sonar.yaml
This is because secrets are not available for dependabot.
See: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
> Skip integration tests for dependabot

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-reactive-sample/src/test/java/com/example/ReactiveReceiverApplicationIntegrationTest.java
The `returnImmediately=true` with 1K messages requests in our cleanup code seems to interfere with the test.
So, removing it.
> Remove message cleanup from Pub/Sub reactive sample

- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java
This is a substitute for `findAll(Pageable)`.
Related to #409.
> Document findBy(Pageable) for Firestore

- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/GcpPubSubHeaders.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/converter/JacksonPubSubMessageConverter.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/converter/PubSubMessageConverter.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/converter/SimplePubSubMessageConverter.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandlerTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/converter/JacksonPubSubMessageConverterTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/converter/SimplePubSubMessageConverterTests.java
Introduces `GcpPubSubHeaders.ORDERING_KEY` header that will be automatically applied to the `PubsubMessage` up conversion.
Also, introduces `spring.cloud.gcp.pubsub.publisher.enable-message-ordering` property to enable message ordering on the `Publisher`.
First step in addressing: #85.
> Enable Pub/Sub message ordering for publishing

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfigurationTests.java
> Increase default Pub/Sub health indicator timeout to 2000

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java
> Exposes publisher endpoint for Pub/Sub message ordering

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreEmulatorAutoConfiguration.java
Fixes SonarCloud findings in Datastore Emulator config:
> "InterruptedException" should not be ignored
> Improve Datastore Emulator exception handling

- .github/workflows/linkageCheck.yaml
- spring-cloud-gcp-dependencies/linkage-checker-exclusion-rules.xml
- spring-cloud-gcp-dependencies/pom.xml
Towards https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/389
@meltsufin  As discussed, here is an example filtering XML file. The output of running Linkage Checker (https://gist.github.com/suztomo/7f3a02b246cb0e18e280a69c461fb466) does not show autoconfigure or GcsMessageHandler any more.
After this is merged, would you try adding more rules and share feedback?
> Linkage Checker: adding exclusion file for autoconfigure package

- spring-cloud-gcp-dependencies/pom.xml
With this, the number of errors goes down to 221. No netty linkage errors.
https://gist.github.com/suztomo/3e9a6993aca800b5327bb1be57b09f1a
> Upgrading Linkage Checker to 1.5.8

- .github/workflows/integrationTests.yaml
- .github/workflows/unitTests.yaml
This is basically a no-op change, so that Travis no longer gets notification e-mails on failed builds.
In the long run, we should add a post-run step to e-mail the whole team.
> Push unit/integration tests by 5 minutes

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerEmulatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerEmulatorAutoConfigurationIntegrationTests.java
> Fix Spanner Emulator triggering default credentials creation

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubEmulatorAutoConfiguration.java
This fixes the edge case where the project has the `spring.cloud.gcp.pubsub.emulator-host` set but not actually imports the `spring-cloud-gcp-starter-pubsub` starter.
Before this change, this would cause a `NoClassDefFoundError` when the auto config encountered the `GcpPubSubEmulatorAutoConfiguration`.
> Add class condition on ManagedChannel

- spring-cloud-gcp-dependencies/pom.xml
This is used by some services we use, and it would be convenient to be able to not have to keep track of the version manually.
> Add jdbc-socket-factory-core version

- spring-cloud-gcp-samples/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#468
Integration tests are failing and these are not just flakes.
For example `SecretManagerSampleIntegrationTests` failures can be reproduced locally.
Getting
` No converter found capable of converting from type [com.google.protobuf.ByteString$LiteralByteString] to type [java.lang.String]` which seems to indicate the converter registration in bootstrap autoconfig no longer works in Spring Boot 2.5.
> Revert "Bump spring-boot-starter-parent from 2.4.5 to 2.5.0"

- docs/src/main/asciidoc/sql.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/GcpCloudSqlProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
Introduces `spring.cloud.gcp.sql.enableIamAuth=true` for enabling IAM authentication,
which currently only works on PostgreSQL.
Fixes: #474.
> Add support for IAM database authentication

- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandler.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandlerTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/java/com/example/SenderApplication.java
Two callbacks provided: `setSuccessCallback()` and `setFailureCallback()`. 
Second parameter to both is the original `Message` for consistency, and to enable forwarding to downstream channels.
Fixes #467.
> Pub/Sub publish callbacks with original Message awareness

- docs/src/main/asciidoc/spanner.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/SpannerOptionsCustomizer.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfigurationTests.java
I looked at providing individual option overrides, but there are too many options that are not very relevant to Spring fundamentals. So we might as well introduce a customizer that works for any need. I put it in autoconfiguration project because it's not really useful for any other scenario -- without Spring Boot, users would be creating their own `SpannerOptions` in the first place.
Fixes #480.
> Add customizer for SpannerOptions object

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
Secret Manager placehoders are still skipped as before.
Fixes: #491.
> Allow placeholders in Cloud SQL config

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinder.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderTests.java
Fixed missing `beanFactory` in #509
> Propagate bean factory to adapter

- pom.xml
`java-cfenv:2.4.0` is not released yet; it most likely made its way to spring release repo [as an experiment](https://github.com/pivotal-cf/java-cfenv/issues/155#issuecomment-877498452), and we got lucky and picked it up.
> Revert to published cfenv version

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapter.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapterTests.java
Fix [GH-505](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/505) remove workaround for GH-2615, and using new requireSubscribers option introduced in Spring Integration.
> Remove workaround nulling out Pub/Sub error channel on shutdown.

- .github/workflows/unitTests.yaml
- spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/spring-cloud-gcp-kotlin-app-sample/pom.xml
Fix [GH-538](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/538), upgrade spring-cloud-gcp-kotlin-samples kotlin version to 1.5.21 and remove workaround step from unit test workflow.
> Upgrade samples project kotlin to 1.5.21

- docs/src/main/asciidoc/datastore.adoc
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQuery.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQuery.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TestEntityRepository.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQueryTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SingerRepository.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/test/java/com/example/DatastoreSampleApplicationIntegrationTests.java
This is fix for #452. 
Fixed code in `GqlDatastoreQuery` and `PartTreeDatastoreQuery` to support for Stream as a return type and added corresponding unit tests and integration tests.
> Support Stream as return type to datastore queries

- docs/src/main/asciidoc/bigquery.adoc
- docs/src/main/asciidoc/config.adoc
- docs/src/main/asciidoc/core.adoc
- docs/src/main/asciidoc/datastore.adoc
- docs/src/main/asciidoc/firestore.adoc
- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/asciidoc/kms.adoc
- docs/src/main/asciidoc/logging.adoc
- docs/src/main/asciidoc/metrics.adoc
- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/asciidoc/security-iap.adoc
- docs/src/main/asciidoc/spanner.adoc
- docs/src/main/asciidoc/spring-cloud-bus-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- docs/src/main/asciidoc/spring-integration-storage.adoc
- docs/src/main/asciidoc/spring-stream.adoc
- docs/src/main/asciidoc/sql.adoc
- docs/src/main/asciidoc/storage.adoc
- docs/src/main/asciidoc/trace.adoc
- docs/src/main/asciidoc/vision.adoc
Made edits to fix some broken links within the documentation. Added explicit block id where applicable.
- all links to Bill of Materials section
- links in Starter Dependencies section table
- link to spring-cloud-stream from spring-cloud-bus-pubsub
> Fix some broken links within documentation

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfigurationTests.java
Fix [GH-501](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/501)
> Use NoCredentialsProvider when firestore emulator enabled.

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/DatastorePageable.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepository.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepositoryTests.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/SimpleSpannerRepositoryTests.java
This PR allows Datastore to work with both Spring Data/Spring Boot 2.4 and 2.5. It also adds placeholder methods for the new `CrudRepository` method `deleteAllById()` to fix compilation issues with 2.5.
I've inlined `super.next()` creating a new `PageRequest` because there were inheritance issues with Spring Data 2.4.9 (at runtime, the overridden superclass method was not called, causing the infinite loop. But this only happens if the signature is `public PageRequest next() {`. If the signature is `public Pageable next() {`, java finds the overridden method, and all is well. Classic "this should never happen" type of Java situation, which I would normally troubleshoot to bitter end, but inlining the `PageRequest` creation also improves readability).
Fixes #564.
> Fix Datastore pageable return type compatibility

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContext.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContextTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TestEntity.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TestEntityRepository.java
Fixes #552.
Added Datastore native types on top of Spring natives as simple types in `DatastoreMappingContext` constructor.
Also added tests in `DatastoreMappingContextTests.java` and `DatastoreIntegrationTests.java` .
> Fix Timestamp as datastore supported types

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepository.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java
Implement `deleteAllById()` in `SimpleFirestoreReactiveRepository` and add relevant tests.
Resolves #566.
This is in the checklist of #472.
> Implement deleteAllById() in SimpleFirestoreReactiveRepository 

- spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/test/java/com/example/TraceSampleApplicationIntegrationTests.java
Trace tests run just fine locally, but flake regularly when running on GitHubActions.
Let's find out why.
> Add diagnostic message to find source of trace test flakiness

- .github/workflows/integrationTests.yaml
The old GHA step for GraalVM seems to have broken; this uses a different implementation.
> Fix the GraalVM Github Actions step

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
> Add implementation to choose global properties when subscription-specific properties are not specified

- pom.xml
Migrates to the new sonatype endpoint to fix our continuous build.
> Updates the sonatype endpoint

- docs/src/main/asciidoc/trace.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/test/java/com/example/TraceSampleApplicationIntegrationTests.java
There is little value in Spring Integration Sleuth support when you enable Pub/Sub trace instrumentation.
So, the recommended settings are:
```
spring.cloud.gcp.trace.pubsub.enabled=true
spring.sleuth.integration.enabled=false
```
This avoids the flakyness we observe with SI instrumentation.
This PR updates Trace sample to disable Spring Integration instrumentation, when Pub/Sub trace instrumentation is used.
Fixes flaky `TraceSampleApplicationIntegrationTests`.
Fixes: #597.
> Disable SI trace instrumentation with Pub/Sub tracing

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/FirestoreTransactionManagerAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/it/FirestoreDocumentationIntegrationTests.java
This PR is a fix for https://github.com/spring-cloud/spring-cloud-gcp/issues/2550 from the old repository location
> Separates firestore transaction manager into its own auto-configuration

- docs/src/main/asciidoc/logging.adoc
- spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java
- spring-cloud-gcp-logging/src/main/resources/com/google/cloud/spring/logging/logback-json-appender.xml
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
- spring-cloud-gcp-logging/src/test/resources/logback-test.xml
I will suggestion to support new option for customizing MDC field name for traceId and spanId.
This PR's motivation is supporting easily that use together with the [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation). The opentelemetry-java-instrumentation store a value to the MDC using [snake case field name(`trace_id` and `span_id`)](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md).
> Support new option for customizing MDC field name for traceId and spanId

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/pubsub/TracingSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/SubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
Fixes #603
In addition to maintaining backwards compatibility, this PR removes the `global` boolean from PubSubConfiguration which used to determine whether a configuration, specifically the executor threads property, was global or subscription specific. Since it is possible to have a mix of global and subscription-specific properties (as discovered in #605), this boolean wasn't fully accurate.  Now, this is determined through the presence of a scheduler in the thread pool scheduler map.
> Keep two versions of createSubscriberStub in DefaultSubscriberFactory

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
Part 1 of #671 
This PR registers global and subscription-specific flow control settings as beans in `GcpPubSubAutoConfiguration`. However, note that if a custom bean is provided then the global and subscription-specific beans won't be created.
> Register subscriber flow control settings as beans

- docs/src/main/asciidoc/trace.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/GcpTraceProperties.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java
Allows configuring the server response waiting timeout.
This PR addresses  https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/563
See also: https://github.com/spring-cloud/spring-cloud-gcp/issues/1617
> Expose StackdriverSender.serverResponseTimeoutMs via a config property.

- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorIntegrationTests.java
This fixes compiling error on `mvn test-compile` phase.
Added `TODO` comment to check on test functionality later.
> update method signatures to match super class changes.

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/pubsub/PropagationSetterTest.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/pubsub/PubSubConsumerRequestSetterTest.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/pubsub/PubSubProducerRequestSetterTest.java
This is to **temporarily** fix and unblock for upgrading purposes. Fix unit test failures:
```
Error:    PubSubConsumerRequestSetterTest>PropagationSetterTest.reset:59 » NoSuchMethod ...
Error:    PubSubConsumerRequestSetterTest>PropagationSetterTest.set:34 » NoSuchMethod or...
Error:    PubSubConsumerRequestSetterTest>PropagationSetterTest.set128:41 » NoSuchMethod
Error:    PubSubConsumerRequestSetterTest>PropagationSetterTest.setTwoKeys:49 » NoSuchMethod
Error:    PubSubProducerRequestSetterTest>PropagationSetterTest.reset:59 » NoSuchMethod ...
Error:    PubSubProducerRequestSetterTest>PropagationSetterTest.set:34 » NoSuchMethod or...
Error:    PubSubProducerRequestSetterTest>PropagationSetterTest.set128:41 » NoSuchMethod
Error: …
```
> Bring in brave tests locally to bypass assertj errors.

- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubEmulator.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorIntegrationTests.java
This is PR brings `PubSubMessageChannelBinderEmulatorIntegrationTests` to junit 5 to avoid mis-match with the abstract test class it inherit from. This test has been running with all modules's integration tests regardless of the `-Dit.pubsub-emulator` settings.
This is step 1 of #707 and should unblock and reveal any further issues on it test for other modules.
> Unblock integration tests: fix to respect `-Dit.pubsub-emulator` settings

- spring-cloud-gcp-samples/pom.xml
Update sample pom to match spring boot 2.6. 
This should fix `ConfigSampleApplicationIntegrationTests` and `TraceSampleApplicationIntegrationTests`.
Need to merge and rerun tests after #708 gets merged in.
> update spring boot version for samples

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubTestBinder.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
Part 2 of #671
If a custom executor provider bean is provided then global or selective executor provider beans are not created/registered.
> Register executor provider as a bean

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
Part 3 for #638
This PR registers global and subscription-specific retry settings as beans in GcpPubSubAutoConfiguration. However, note that if a custom bean is provided then the global and subscription-specific beans won't be created.
> Register subscriber retry settings as beans

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
We recently introduced support for overriding retryableCodes in pull settings (#670). However, this property can only be set globally. This PR enables subscription-specific configuration. 
The `retryableCodes` configuration can be set in the following manner:
Global
```
spring.cloud.gcp.pubsub.subscriber.retryableCodes=INTERNAL, ABORTED
```
Subscription-specific
```
spring.cloud.gcp.pubsub.subscription.mySubscription.retryableCodes=INTERNAL, ABORTED
```
> Add subscription-specific settings for retryableCodes

- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/admin/SpannerSchemaUtilsTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/SpannerStructReadMethodCoverageTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/SpannerWriteMethodCoverageTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerConvertersTest.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/event/AfterExecuteDmlEventTest.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/event/BeforeExecuteDmlEventTest.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategyTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryFactoryBeanTests.java
Migrated the following tests from JUnit4 to JUnit5 in 
**module: spring-cloud-gcp-data-spanner**
1. SpannerSchemaUtilsTests.java
2. SpannerStructReadMethodCoverageTests
3. SpannerWriteMethodCoverageTests.java
4. TestEntities.java
5. SpannerQueryLookupStrategyTests.java
6. SpannerRepositoryFactoryBeanTests.java
7. AfterExecuteDmlEventTest
8. BeforeExecuteDmlEventTest
9. ConverterAwareMappingSpannerEntityProcessorTests
10. SpannerConvertersTest
> spring cloud gcp data spanner tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/UtilTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentEntityImplTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQueryTests.java
Migrated the following tests from JUnit4 to JUnit5 :
**module: spring-cloud-gcp-data-firestore**
1. FirestorePersistentEntityImplTests.java
2. PartTreeFirestoreQueryTests.java
3. FirestoreTemplateTests.java
4. SimpleFirestoreReactiveRepositoryTests.java
5. UtilTests.java
> spring cloud gcp data firestore tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversions.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/convert/DefaultDatastoreEntityConverterTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Singer.java
Blob-to-byte[] and reverse are a special case in conversion -- it's the only exception to the general rule of "Datastore collection becomes Java collection; Datastore simple type becomes Java type". It seems to have been intended to work in original implementation, but never had a test, so either never worked right or broke over the years. The other direction, on write, works fine through `BYTE_ARRAY_TO_BLOB_CONVERTER` combined with `ValueUtil.isArrayOfItems()` exempting `byte[]` from array status. 
There were several ways of fixing this (each commit in this PR is a working solution), but at the end I went with making the standard conversion path worked. It required redefining the meaning of collection to exclude byte arrays, which is already done in the local utility …
> Implement datastore Blob to byte[] conversion on read

- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversionsTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastoreMappingContextTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/util/KeyUtilTest.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/util/SliceUtilTest.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/DatastoreQueryLookupStrategyTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQueryTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/DatastoreRepositoryFactoryBeanTests.java
Migrated the following tests from JUnit4 to JUnit5 :
module: spring-cloud-gcp-data-datastore
1. TwoStepsConversionsTests
2. DatastoreMappingContextTests
3. KeyUtilTest.java
4. SliceUtilTest.java
5. DatastoreQueryLookupStrategyTests.java
6. GqlDatastoreQueryTests.java
7. DatastoreRepositoryFactoryBeanTests.java
> spring cloud gcp data datastore tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-core/src/test/java/com/google/cloud/spring/core/DefaultCredentialsProviderTests.java
- spring-cloud-gcp-core/src/test/java/com/google/cloud/spring/core/UserAgentHeaderProviderTests.java
- spring-cloud-gcp-core/src/test/java/com/google/cloud/spring/core/util/MapBuilderTests.java
Migrated the following tests from JUnit4 to JUnit5 : 
_**Module: spring-cloud-gcp-core**_
1. MapBuilderTests.java
2. DefaultCredentialsProviderTests.java
3. UserAgentHeaderProviderTests.java
> spring cloud gcp core tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-cloudfoundry/src/test/java/com/google/cloud/spring/cloudfoundry/GcpCloudFoundryEnvironmentPostProcessorTests.java
Migrated the following tests from JUnit4 to JUnit5 :
**_Module: spring-cloud-gcp-cloudfoundry_**
1. GcpCloudFoundryEnvironmentPostProcessorTests.java
> spring cloud gcp cloudfoundry tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubEmulator.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorIntegrationTests.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubTestBinder.java
This is step 2 and fixes #707 
There are 2 fixes in this PR: 
1. Let `PubSubEmulator` extend `ParameterResolver` to inject the emulator port number into the instance. This is left-over from task 1 upgrading to junit5 test, solves the `java.lang.NullPointerException: target` error caused by no port number provided.
2. After above change, tests fail due to a [recent change](https://github.com/spring-cloud/spring-cloud-stream/commit/2c47c6de8977345e0595ba122adf89c2709c41d6#diff-70aeaabb8c7de9d4d4b239ba643f594bf49f111d18569056dd93a835d5e9867cR132) in spring-cloud-stream logic. 
- when checking if context already has an ObjectMapper bean, calls `getBeansOfType(ObjectMapper.class)`, which has an internal call to `assertBeanFactoryActive()`
- Test setup fails with error: …
> Fixes for`PubSubMessageChannelBinderEmulatorIntegrationTests`

- spring-cloud-gcp-native-support/src/test/java/com/google/cloud/spring/nativex/firestore/NativeSupportTest.java
Migrated the following tests from JUnit4 to JUnit5:
**_module: spring-cloud-gcp-native-support_**
1. NativeSupportTest.java
> spring cloud gcp native support tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerPropertyUtilsTests.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerTemplateTests.java
Migrated the following tests from JUnit4 to JUnit5
**_Module : spring-cloud-gcp-secretmanager_**
SecretManagerPropertyUtilsTests.java
SecretManagerTemplateTests.java
> spring cloud gcp secret manager tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-security-firebase/src/test/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoderTests.java
Migrated the following tests from JUnit4 to JUnit5
**_Module : spring-cloud-gcp-security-firebase_**
1. FirebaseJwtTokenDecoderTests.java
> spring cloud gcp security firebase tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
Update spring-cloud-config.version for pubsub-bus-config-sample compatible with Spring Boot 2.6.0-RC1.
> update spring-cloud-config.version for pubsub-bus-config-sample

- docs/src/main/asciidoc/spanner.adoc
This PR removes outdated wording from our documentation.
Cloud Spanner supports foreign keys [since March 2020](https://cloud.google.com/spanner/docs/release-notes).
Addresses a small part of #737.
> Remove wording for foreign keys being unsupported

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/ReadWriteConversions.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversions.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/convert/TwoStepsConversionsTests.java
**I want a second opinion on this. TLDR: code handling array-to-list conversion broke a year ago and nobody noticed. We can either (1) remove this code entirely (and document it as unsupported) or (2) fix the array-to-list conversion to the way it was before #284 and add a test.** In an ideal world, I'd prefer a type-safe conversion interface that has separate methods to convert single values and collections, but we don't have bandwidth for refactoring what's not technically broken.
When working on #729, this block in `convertOnRead(Object, EmbeddedType, TypeInformation)` was bothering me -- it did not seem right to make a List-wrapped array.
```
if (val.getClass().isArray()) {
elements = Collections.singletonList(val);
}
```
Looking into the history of the change, this line accidentally …
> Datastore: remove unused code handling array conversion

- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/GoogleStorageLocationTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/GoogleStorageResourceTest.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/filters/GcsDiscardRecentModifiedFileListFilterTest.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/filters/GcsPersistentAcceptOnceFileListFilterTest.java
Migrated the following modules from JUnit4 to JUnit5:
**_Module: spring-cloud-gcp-storage_**
1. GcsDiscardRecentModifiedFileListFilterTest.java
2. GcsPersistentAcceptOnceFileListFilterTest.java
3. GoogleStorageLocationTests.java
4. GoogleStorageResourceTest.java
> spring cloud gcp storage tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/DocumentOcrResultSetTests.java
- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/OcrPageRangeTests.java
Migrated the following tests from JUnit4 to JUnit5:
**_module: spring-cloud-gcp-vision_**
1. DocumentOcrResultSetTests.java
2. OcrPageRangeTests.java
> spring cloud gcp vision tests migration(JUnit4 to JUnit5)

- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerPropertySourceIntegrationTests.java
The test were failing at value injection to TestConfiguration due to missing converter. This failure only affects integration test as its setup does not rely on auto-configuration.
This change explicitly provides SecretManagerTestConfiguration as source when building context so that the custom converter gets picked up.
> Fix secret manager it test setup to work with spring boot 2.6

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java
- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepository.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorIntegrationTests.java
Cleanup todo tags: 
- no need to support 2.4 on 3.x, so restore `@Override` for `deleteAllById()`
- `PubSubMessageChannelBinderEmulatorIntegrationTests` tests already verified in #730 .
> Cleanup todo tags: no need to support 2.4 and verified tests.

- .kokoro/publish_javadoc.sh
It's an experiment to fix our javadoc publishing. The error seems to be caused by a mismatch in python versions vs code.
> Remove python version override

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
Implemented this for **spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java** 
The test results summary shows an improvement in runtime by 0.5 seconds (on an average), noted over 5 cycles.
Please review the changes and let me know if they look fine.
> Overriding autoconfiguration of DefaultCredentialsProvider to make the tests run faster (Sample) 

- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/pom.xml
Java8 is [not supported](https://github.com/paketo-buildpacks/graalvm/commit/276cf8880ed8f81573db0f3577e5679bd71734b7) by the latest graal buildpack.
In any case, we should keep the version of graal in buildpack consistent with the rest of the dependencies.
> Set graal to 21.2

- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/EmbeddedEntity.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TestEntity.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TestEntityRepository.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java
- spring-cloud-gcp-data-datastore/src/test/resources/index.yaml
`index.yaml` is only used for integration test setup once per GCP project. It affects 3 test in `DatastoreIntegrationTests.java`: `testSlicedEntityProjections`, `testSliceString`, `projectionTest` due to the query method used in tests.
Proposing change aligns with current CI project setting and tested with new GCP project.
> change to index.yaml to match integration test setup.

- .kokoro/publish_javadoc.sh
I published javadoc from `2.0.6-javadoc` branch because `main` was already tagged at a point in time that had the bad version of the script.
Porting it, so it's correct for future releases.
> Port fixes that worked for javadoc publishing back to main

- docs/src/main/asciidoc/spanner.adoc
Related to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/774
> Document restriction on embedded objects

- .github/workflows/unitTests.yaml
- pom.xml
With Java 17, the old way to override illegal module access switched to `--add-opens java.base/java.lang=ALL-UNNAMED`. 
This is all to make one test using a concrete implementation of a collection --  `DatastoreTemplateTests.saveTestNotInterfaceLazy` -- work. 
[This discussion in Spring](https://github.com/spring-projects/spring-boot/issues/26578#issuecomment-842305746) was helpful for understanding why this was an issue in the first place -- JUnit has a different classloader from the one Spring is using to create context.
The original error when running tests with Java17 was
```
[INFO] Running com.google.cloud.spring.data.datastore.core.DatastoreTemplateTests
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.953 s <<< FAILURE! - in …
```
> Switch unit tests from Java 16 to 17

- spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/test/java/com/example/CloudSqlJpaSampleApplicationIntegrationTests.java
Migrated the test from JUnit4 to JUnit5, including ExecutionCondition changes and superseding "Rule" annotation with "ExtendWith"
Also updated the readme doc about enabling the Cloud SQL Admin API.
> Migrating "CloudSqlJpaSampleApplicationIntegrationTests.java" to JUnit5

- pom.xml
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerPropertySourceIntegrationTests.java
We currently derive Spring Boot versions indirectly, through Spring Cloud Build. That's not ideal because for Spring Cloud Build, it's a minor infrastructural detail, while users of Spring Cloud GCP can get the version of Spring Boot through our starters.
We should explicitly maintain the version of Spring Boot.
Fixes #801.
> Remove spring-cloud-build dependency; add spring-boot BOM explicitly

- pom.xml
roll back dependabot bump of spring-cloud-dependencies (#807) due to failing integration tests.
> Roll back spring-cloud-dependencies from 2020.0.5 to 2020.0.4

- spring-cloud-gcp-samples/pom.xml
[Spring Boot 2.6.2](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.2) just released today. 
Including upgrade to Log4j2 2.17.0
> upgrade to spring-boot 2.6.2 for 3.x

- .github/workflows/integrationTests.yaml
Native tests are breaking when upgrading either Spring Native (0.10.4 to 0.10.5) or when upgrading Libraries BOM (24.0.0 to 24.1.0). We can't hold up upgrades on an experimental feature.
> Remove native tests from integration matrix

- spring-cloud-gcp-samples/pom.xml
I think dependabot ignored updates for a bit because we asked to not do "minor updates" when it tried to go from 2.5.3 to 2.6.0.
> Update Spring Boot in samples to 2.5.8

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/PartTreeSpannerQuery.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryMethod.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQuery.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryMethodTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQueryTests.java
Spring Data added a new package-private method in v2.5.0 that clashes in name with `SpannerQueryMethod.getMethod()`. Sonar had angry thoughts about this that came up when I set Spring Boot version to 2.5.x in this repo.
This PR should fix Sonar's complaint about a confusing method name. Also, since this method never had any business being public, and because this is a breaking change anyhow, I've reduced visibility to package-private.
> Rename method to avoid confusing name clash with parent

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapper.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/GcpPubSubHeaders.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapperTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-polling-sample/src/test/java/com/example/SampleAppIntegrationTest.java
Introduced a new header pattern "GcpPubSubHeaders.CLIENT" in outboundHeaderPatterns to strip out all the headers starting with "googclient_" along with writing a unit test for the same.
Fix to the issue -> #776  
**(This PR also includes migration of "SampleAppIntegrationTest.java" to JUnit5")**
> Exclude all attributes starting with "goog_" from outbound Pub/Sub headers 

- docs/src/main/asciidoc/spring-integration-pubsub.adoc
fix doc link to javadoc page PatternMatchUtils.class
> fix doc link to javadoc page PatternMatchUtils.class

- .github/dependabot.yml
Add dependabot config for targeting 2.x branch, ignoring all major version upgrades.
[guide for setting up ignore.](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#creating-ignore-conditions-from-dependabot-ignore)
> Add dependabot config to also work on 2.x branch

- docs/src/main/asciidoc/logging.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/logging/StackdriverLoggingAutoConfiguration.java
- spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/LoggingWebMvcConfigurer.java
- spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java
- spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/extractors/CloudTraceIdExtractor.java
- spring-cloud-gcp-logging/src/main/resources/com/google/cloud/spring/logging/logback-json-appender.xml
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/CloudTraceIdExtractorTests.java
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/StackdriverJsonLayoutLoggerTests.java
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/TraceIdLoggingWebMvcInterceptorTests.java
- spring-cloud-gcp-logging/src/test/resources/logback-test.xml
In preparation for switching from Spring to Google checkstyle, several breaking changes are needed. These will not be backported to 2.x.
- Renamed XCloudTraceIdExtractor to CloudTraceIdExtractor
- Renamed methods in StackdriverJsonLayout (users will have to update `traceIdMDCField` and `spanIdMDCField` in custom layouts to `traceIdMdcField` and `spanIdMdcField` respectively.)
- getTraceIdMDCField -> getTraceIdMdcField
- setTraceIdMDCField -> setTraceIdMdcField
- getSpanIdMDCField -> getSpanIdMdcField
- setSpanIdMDCField -> setSpanIdMdcField.
> Google checkstyle breaking changes only

- .github/workflows/integrationTests-2.x.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests-2.x.yaml
GHA "schedule" task does not allow you to set custom branches; it always runs on the last commit of the main branch. So I added two new actions to handle the scheduled unit/integration tests for the 2.x branch.
Pull requests and pushes to the branch will continue being handled by the existing yaml configuration files.
I also removed all native IT setup from the 2.x integration configuration. No reason to maintain it for the 2.x branch, as those are not released artifacts.
> Added scheduled CI workflows for 2.x

- docs/src/main/asciidoc/security-iap.adoc
Update link to [Spring Security OAuth 2.0 Resource Server](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/index.html) mentioned in Cloud-IAP documentation.
> Fix outdated link to spring-security in documentation.

- README.adoc
I see we haven't run this checker in more than 6 month and leaving this badge on our front page always red seems weird. 
Is it reasonable to remove it for now?
> remove linkage checker badge from readme.

- spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample/README.adoc
After running the sample, 
- adding information where I run into bumps: on enable IAP and adding "IAP-Secured Web App User" role for user access to deployed application.
- adding some narrative to set up "audience" property when running locally. (we do not need this for App Engine env, but need locally or GCE/GKE - [doc](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.7/reference/html/index.html#cloud-iap))
- adjusting sequence and put "Deploying the Sample to AppEngine Standard" upfront. I personally find it more natural to do in this sequence, since testing locally really need to have this deployed version first. Does this make sense to you?
> Security-Iap-Sample readme: adding and adjustment to readme after running sample.

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
Verified that the session pool stays stable after the fix using one of the Spanner samples, plus actuator dependency.
Fixes #891.
> Close Spanner health check ResultSet to prevent session leak

- docs/src/main/asciidoc/sql.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessorTests.java
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/901 
This PR also renames `R2dbcCloudSqlEnvironmentPostProcessorTest` to `R2dbcCloudSqlEnvironmentPostProcessorTests` for consistency.
> Introduce property to turn off jdbc support

- .github/workflows/integrationTests-2.x.yaml
- .github/workflows/unitTests-2.x.yaml
I think one of the reasons the flakes got more frequent is that the 2.x unit/integration tests run first, and set up the older set of artifacts. Then all the new code (`main` branch and PRs off of it) has to re-download Spring Boot 2.6-related artifacts on the fly.
This PR makes 2.x unit and integration tests use different caches.
After this if, once we start backporting changes to 2.x, we notice that 2.x flakes more than `main`, it will be confirmation of this hypothesis.
> Differentiate scheduled 2.x job cache from main cache

- .mvn/maven.config
- docs/pom.xml
- pom.xml
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-native-support/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/pom.xml
We don't rely on snapshots/milestones in the releasable branches.
This may help with the flakes -- I suspect that maven's multi-threading tries to fetch jars from Maven Central and from Spring Milestones at the same time, but milestones don't actually have the artifacts that cause issues.
> Remove Spring Milestones/Snapshots repositories

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapper.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/GcpPubSubHeaders.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapperTests.java
> Exclude `goog_` prefixed attributes from outbound Pub/Sub messages (backport)

- docs/src/main/asciidoc/security-iap.adoc
Update link to Spring Security OAuth 2.0 Resource Server mentioned in Cloud-IAP documentation.
Backports #888.
> Fix link (backport)

- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/asciidoc/sagan-index.adoc
- docs/src/main/asciidoc/security-firebase.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-security-firebase-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-security-firebase-sample/src/main/resources/static/index.html
- spring-cloud-gcp-security-firebase/src/main/java/com/google/cloud/spring/security/firebase/FirebaseJwtTokenDecoder.java
- spring-cloud-gcp-security-firebase/src/main/java/com/google/cloud/spring/security/firebase/FirebaseTokenValidator.java
This should close #879.
- Add reference documentation for security-firebase module.
- Mentioning Firebase starter and sample in getting-started and sagan-index. 
- Edits in sample readme and Javadoc format for better readability.
- Fix a typo in sample.
> Adding Firebase Documentation

- docs/src/main/asciidoc/sql.adoc
- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-r2dbc-sample/src/main/java/com/example/User.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-r2dbc-sample/src/main/java/com/example/WebController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/main/java/com/example/User.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/main/java/com/example/WebController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/test/java/com/example/SqlR2dbcPostgresSampleApplicationIntegrationTests.java
This PR also modifies the samples to use `R2dbcEntityTemplate` to query databases instead of using `ConnectionFactory` directly. 
Fixes #904
> Add documentation for R2DBC and simplify samples

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepositoryTests.java
> Spanner repository findAllById() should return empty result on empty input

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/SpannerRepositoryExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/TradeRepository.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/test/java/com/example/SpannerRepositoryIntegrationTests.java
This is a quick fix for issue #943 to correctly skip Pageable/Sort when it might not be the last parameter.
Note for future refactoring: what case makes `originalParam == null` [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java#L459)? It's never used in current test cases. might worth look into remove building of `paramMetadataMap`  if not used.
> Fix query breaks when Pageable parameter is not the last

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubChannelAdaptersIntegrationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java
Migrated the following tests to JUnit5 : 
1. PubSubChannelAdaptersIntegrationTests.java
2. PubSubTemplateDocumentationIntegrationTests.java
3. PubSubTemplateIntegrationTests.java
> Migrating tests to JUnit5 (PubSubChannelAdaptersIntegrationTests, PubSubTemplateDocumentationIntegrationTests, PubSubTemplateIntegrationTests)

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubReactiveAutoConfigurationTest.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubSubscriptionHealthIndicatorTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
Migrated the following tests to JUnit5:
1. GcpPubSubReactiveAutoConfigurationTest.java
2. PubSubSubscriptionHealthIndicatorTests.java
3. PubSubAutoConfigurationIntegrationTests.java
> Migrating tests to JUnit5 (GcpPubSubReactiveAutoConfigurationTest, PubSubSubscriptionHealthIndicatorTests, PubSubAutoConfigurationIntegrationTests)

- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/core/BigQueryTemplateIntegrationTests.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerIntegrationTests.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/integration/outbound/BigQueryFileMessageHandlerTests.java
Migrated the following tests to JUnit5:
1.  BigQueryTemplateIntegrationTests.java
2.  BigQueryFileMessageHandlerIntegrationTests.java
3. BigQueryFileMessageHandlerTests.java
Introduced **@ TestInstance(TestInstance.Lifecycle.PER_CLASS)** annotation in **BigQueryTemplateIntegrationTests** to enable **@ AfterAll annotation** to work with non-static fields. 
**@ TestInstance(TestInstance.Lifecycle.PER_CLASS)** enables us to ask JUnit5 to create only one instance of the test class and reuse it between tests. This enables the usage of @ Autowired fields with @ AfterAll methods (otherwise not possible because @ AfterAll is used in static context and @ Autowired doesn't work with static)
> Migrating tests in spring-cloud-gcp-bigquery to JUnit5

- pom.xml
Unfortunately, testing maven deploy locally does not generate the child pom XMLs in the same way -- the inherited fields are not populated. So I'd like to merge this in, trigger a staging job, and then verify whether this change works.
If it does not work, I'll back out the property, and hardcode the URL in all deployable modules.
> Turn off option to append URLs

- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/convert/EntityPropertyValueProviderTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentEntityImplTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/mapping/DatastorePersistentPropertyImplTests.java
Migrated the following tests:
1. EntityPropertyValueProviderTests
2. DatastorePersistentEntityImplTests
3. DatastorePersistentPropertyImplTests
> Migrating tests to JUnit5

- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/SimpleFirestoreReactiveRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentPropertyImplTest.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/transaction/ReactiveFirestoreTransactionManagerTest.java
Migrated the following tests to JUnit5:
1. SimpleFirestoreReactiveRepositoryTests.java
2. FirestoreIntegrationTests.java
3. FirestoreRepositoryIntegrationTests.java
4. FirestorePersistentPropertyImplTest.java
5. FirestoreRepositoryTests.java
6. ReactiveFirestoreTransactionManagerTest.java
> Migrating tests in "spring-cloud-gcp-data-firestore" to JUnit5

- .github/workflows/integrationTests-2.x.yaml
- .github/workflows/integrationTests.yaml
setup-gcloud will be updating the branch name from master to main in a future release. Even though GitHub will establish redirects, this will break any GitHub Actions workflows that pin to master. This PR updates your GitHub Actions workflows to pin to v0, which is the recommended best practice.
> Pin setup-gcloud to v0 instead of master

- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/PubSubHeaderMapperTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapterTests.java
Tests migrated to JUnit5:
1. PubSubHeaderMapperTests.java
2. PubSubInboundChannelAdapterTests.java - (splitting setup into two parts to avoid UnnecessaryStubbing)
> Migrating more pubsub tests to JUnit5

- spring-cloud-gcp-security-iap/src/test/java/com/google/cloud/spring/security/iap/AppEngineAudienceProviderTests.java
- spring-cloud-gcp-security-iap/src/test/java/com/google/cloud/spring/security/iap/AudienceValidatorTests.java
1. AppEngineAudienceProviderTests.java
2. AudienceValidatorTests.java
> Migrating "spring-cloud-gcp-security-iap" tests to JUnit5

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/SpannerRepositoryExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/TradeRepository.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/test/java/com/example/SpannerRepositoryIntegrationTests.java
Backporting from #958.
This is a quick fix for issue #943 to correctly skip Pageable/Sort when it might not be the last parameter.
> Backport: Pageable parameter not in last position fix

- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/GoogleStorageTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsInboundFileSynchronizerTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsStreamingMessageSourceTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/outbound/GcsMessageHandlerTests.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/it/GoogleStorageIntegrationTests.java
1. GoogleStorageTests.java
2. GcsInboundFileSynchronizerTests.java
3. GcsStreamingMessageSourceTests.java
4. GcsMessageHandlerTests.java
5. GoogleStorageIntegrationTests.java
> Migrating "spring-cloud-gcp-storage" tests to Junit5

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/CloudVisionTemplateTests.java
- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/DocumentOcrTemplateTests.java
- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/DocumentOcrTemplateIntegrationTests.java
1. CloudVisionTemplateTests.java
2. DocumentOcrTemplateTests.java
3. DocumentOcrTemplateIntegrationTests.java
> Migrating "spring-cloud-gcp-vision" tests to JUnit5

- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/ParallelDatastoreIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/subclasses/descendants/SubclassesDescendantsIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/subclasses/references/SubclassesReferencesIntegrationTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/query/PartTreeDatastoreQueryTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/DatastoreRepositoryFactoryTests.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepositoryTests.java
1. DatastoreIntegrationTests.java
2. ParallelDatastoreIntegrationTests.java
3. SubclassesDescendantsIntegrationTests.java
4. SubclassesReferencesIntegrationTests.java
5. PartTreeDatastoreQueryTests.java
6. DatastoreRepositoryFactoryTests.java
7. SimpleDatastoreRepositoryTests.java
> Migrating datastore tests to JUnit5

- pom.xml
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/it/CommitTimestampIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/it/SpannerTemplateIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerKeyPropertyTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContextTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImplTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentPropertyImplTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/ParallelSpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryInsertIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepositoryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/support/SpannerRepositoryFactoryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/AbstractSpannerIntegrationTest.java
1. CommitTimestampIntegrationTests.java
2. SpannerTemplateIntegrationTests.java
3. SpannerKeyPropertyTests.java
4. SpannerMappingContextTests.java
5. SpannerPersistentEntityImplTests.java
6.  SpannerPersistentPropertyImplTests.java
7. ParallelSpannerRepositoryIntegrationTests.java
8. SpannerRepositoryInsertIntegrationTests.java
9. SpannerRepositoryIntegrationTests.java
10. SpannerStatementQueryTests.java
11. SqlSpannerQueryTests.java
12. SimpleSpannerRepositoryTests.java
13. SpannerRepositoryFactoryTests.java
14. AbstractSpannerIntegrationTest.java
> Migrating spanner tests to JUnit5

- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/Address.java
This is a class used in spanner sample code. For some reason, errorprone seems only complaining on my local and fails to build.
Errorprone complains:
- Prefer instanceof to getClass
- Boxedclass equals
> minor fix: address errorprone complains about .equals()

- pom.xml
It may take some time for dependabot to pick this up. Bump the version manually in response to [this vulnerability](https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement).
> Bump spring-boot-dependencies from 2.6.5 to 2.6.6

- pom.xml
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-pubsub-stream-binder/pom.xml
The next Spring Cloud train release is next week. Update spring-cloud-functions versions in the meantime.
Also:
* update Spring Cloud BOM manually; dependabot missed the last one because we applied second-to-last manually.
* Remove the unnecessary `spring-cloud-dependencies-parent`; this was only needed for when the code was under Spring Cloud org.
> Update spring cloud functions versions

- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-pubsub-stream-binder/pom.xml
With the workaround directly in Spring Cloud GCP binder, the `spring-cloud-gcp-starter-bus-pubsub` and its sample applications still pick up the bad version of `spring-cloud-function-context` from the Spring Cloud Stream dependency tree.
Forcing dependency in the Spring Cloud GCP BOM seems to be the only way to make sure Spring Cloud GCP users who follow [our documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/3.0.0/reference/html/index.html#bill-of-materials) get the correct version of Spring Cloud Function.
> Back out the workaround and force dependency in our BOM

- spring-cloud-gcp-dependencies/pom.xml
Overrides Spring Cloud Function dependencies with ones patched for [CVE-2022-22963](https://tanzu.vmware.com/security/cve-2022-22963).
> (backport) Force patched version of Spring Cloud Function

- docs/pom.xml
Looked into #1076 releaseCheck failure with debug mode, error:
```
Caused by: java.nio.file.NoSuchFileException: /path/to/repo/spring-cloud-gcp/docs/target/refdocs/index.adoc
```
Found these related issues on maven side: [MRESOURCES-278](https://issues.apache.org/jira/browse/MRESOURCES-278), [MSHARED-966](https://issues.apache.org/jira/browse/MSHARED-966).
For the meantime, use `maven-resources-plugin:3.1.0` instead.
> bump spring-cloud-build for docs/pom.xml, fix build failure by pin dependency version.

- README.adoc
We are currently linking to 3.3.0-SNAPSHOT from 2.x branch readme.
> remove references to 3.x docs and javadocs

- CHANGELOG.adoc
Clean up changelog: 
Move release notes since 2.0.8 to 2.x branch changelog. These releases are after split with 3.x, and should be in 2.x branch.
> Move release notes since 2.0.8 to 2.x branch changelog.

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
Vision seems to have stopped adding the trailing newline to their OCR'ed output. Vision flakes of yesterday have turned into a fairly persistent integration test failure today.
> Removes new vision flake

- pom.xml
- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
Because of an [intellij bug](https://youtrack.jetbrains.com/issue/IDEA-288257), local development can be irritating nowadays because of random issues with last character of package files getting changed to \0. 
This turns off the unicode checking rule for Java 9+, which will take care of our local development flow. 
I've tested adding non-English-ascii unicode, and it does not even get past checkstyle, so it won't get to compilation/errorprone. So this change won't relax the code standards.
> Turn off UnicodeInCode errorprone rule

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/bigquery/GcpBigQueryAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubAutoConfigurationIntegrationTests.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/PubSubTestBinder.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
TLDR: 
- immutable maps
- type-safe and unambiguous `ProjectSubscriptionName` map keys
- switched map types to generic `Map` interface
Details:
- In the past, settings for subscriptions not explicitly specified by the user were cached in the map as a reference to global settings. Now they are not; instead global subscriber is returned on-demand whenever properties are requested for an heretofore unknown subscription. This caused a couple of tests to change in behavior -- instead of testing for 2 entries in the map, they are now testing for only 1.
- An instance of `PubSubConfiguration` effectively can't be used until `.initialize()` is called, allowing tying settings to fully qualified subscription names, using the passed-in project ID as a default.
-  `PubSubConfiguration` no longer …
> Fully qualified subscription configuration support + immutable configuration in Pub/Sub

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/SelectiveSchedulerThreadNameProvider.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
Currently thread names for subscription specific Task Schedulers are lengthy as they comprise of 
`gcp-pubsub-subscriber-` + fully qualified subscription name, ex:
`gcp-pubsub-subscriber-projects/fake project/subscriptions/subscription-name1`
This may result in a lengthy log statement, if thread name is a part of it.
This MR allows customization of subscription specific Task Scheduler's thread names.
> Customize thread name prefixes for subscription specific TaskSchedulers

- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/SpannerTestExecutionListener.java
Switch to @EnabledIfSystemProperty to be consistent with other test classes that SpannerTemplateIntegrationTests.java depend on. This makes the behavior consistent running test in Intellij so no VM option needed.
> Fix for spanner it test precondition setup

- docs/src/main/asciidoc/trace.adoc
`StackdriverTracePropagation` has been Brave-centric for years now, but Spring Cloud GCP docs did not keep up. 
Soon, we are going to have to think about how to handle two large ecosystem changes: Spring Cloud Sleuth responsibilities shifting to Micrometer and OpenCensus becoming industry standard. But for now, up to date docs will do.
Fixes #1154.
> Update trace propagation order to reflect reality

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryExecutor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerStatementQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/domain/TradeRepository.java
fixes #1168.
When including `IsNotNull` conditions in query methods by convention, Spanner query fails with  error `Query failed: Operands of <> cannot be literal NULL` with `property<>NULL` syntax. Changing to `property IS NOT NULL` instead.
> fix: SpannerStatementQueryExecutor query generation for IsNotNull conditions

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/support/SimpleDatastoreRepository.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
Spring Data [removed](https://github.com/spring-projects/spring-data-commons/issues/2603) non-load-bearing punctuation from their exceptions.
We have a couple of spots where we verify exception wording, and I've removed another two places just for consistency. Note that this only affects the tests, and not the code throwing those exceptions.
> Remove exclamation points from tests

- docs/src/main/asciidoc/core.adoc
- docs/src/main/md/core.md
the old link for `ServiceOptions.getDefaultProjectId()` does not exist anymore, updated the link to client lib references.
> fix: update broken link in doc.

- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/DatastoreIntegrationTests.java
delete created test entities in ci tests.
> fix: clean-up missed stored entities after datastore integration test.

- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/asciidoc/spring-integration-pubsub.adoc
- docs/src/main/md/pubsub.md
- docs/src/main/md/spring-integration.md
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/PubSubAdmin.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/publisher/PubSubPublisherOperations.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/subscriber/PubSubSubscriberOperations.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapter.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/PubSubSubscriptionUtils.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/PubSubTopicUtils.java
Several documentation changes:
1) Added notes to Spring Integration adapters that subscription/topic names can be fully qualified.
2) Replaced javadoc `<property>` with `[property]` because IntelliJ does not render what it thinks are HTML tags (`<...>`).
3) Replaced "canonical" with "short", because "canonical" reads as ambiguous -- are short names canonical, or are the fully qualified names canonical? It's kind of both -- short names are historically canonical to Spring Cloud GCP, but fully qualified ones are canonical to the client library.
Fixes #581.
> Add refdoc for short vs fully qualified topics/subscriptions

- docs/src/main/asciidoc/spanner.adoc
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructAccessor.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructPropertyValueProvider.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImpl.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQuery.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/admin/SpannerSchemaUtilsTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReaderTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/it/SpannerTemplateIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerPersistentEntityImplTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SqlSpannerQueryTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/domain/Trade.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/test/domain/TradeRepository.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/SpannerRepositoryExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/Trader.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/test/java/com/example/SpannerRepositoryIntegrationTests.java
support ARRAY<JSON> spanner type. 
- read: `StructAccessor.java` and `StructPropertyValueProvider.java`
- write: `ConverterAwareMappingSpannerEntityWriter.java`
- sql query when return type is ARRAY<JSON> field.
- `SqlSpannerQuery.java` and `SpannerPersistentEntityImpl.java`
- test and sample
closes #651.
> feat: add support for ARRAY<JSON> type in Spring Data Spanner

- docs/src/main/asciidoc/logging.adoc
- docs/src/main/md/logging.md
The enhancers' usage is confusing, so while I linked to the main logback appender library, I've added two rows specifying the exact interface that must be implemented for each. Otherwise the ehnancers get silently ignored, which... is not ideal.
Note that documentation temporarily has to be mirrored manually between markdown and asciidoc.
Fixes #1218.
> Add documentation for api logger ehnancers

- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/md/secretmanager.md
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerProperties.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLoader.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataResource.java
- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/spring.factories
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLoaderUnitTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataResourceUnitTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretConfiguration.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretManagerApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretManagerWebController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/bootstrap.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/templates/index.html
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleIntegrationTests.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerPropertySource.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerTemplate.java
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-secretmanager/pom.xml
External resources from GCP Secret Manager can be imported to custom project by add the following line in the `application.properties`:
`spring.config.import=sm://`
This feature is implemented using Spring Boot’s Config Data API, more info can be found in [here](https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4)
fix #149 
Users who want to use this feature should either exclude `<artifactId>spring-cloud-starter-bootstrap</artifactId>` from their dependency or to set `spring.cloud.gcp.secretmanager.legacy=false`
> feat: support  for `spring.config.import` GCP Secret Manager

- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/md/secretmanager.md
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerBootstrapConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerProperties.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerBootstrapConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretManagerWebController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/templates/index.html
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerOperations.java
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/SecretManagerTemplate.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/SecretManagerTemplateTests.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerTestConfiguration.java
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/213
As adding a new behavior to the Secret Manager, introducing a new opt-in property: `spring.cloud.gcp.secretmanager.allow-default-secret`. When it set to `true`, the SecretManager will return `null` when accessing a non-exited secret, rather than throwing an exception. 
Customers can define a default value for non-existed secret using `@Value("${${sm://application-fake}:DEFAULT}")`, the framework will resolve the value as `DEFAULT` if `sm://application-fake` is NOT existed in Secret Manager and `application-fake` is NOT a property.
> Support default secret value when accessing non-existed secret for Secret Manager

- docs/src/main/asciidoc/spanner.adoc
- docs/src/main/md/spanner.md
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/src/main/java/com/example/SpannerTemplateExample.java
Property `spring.cloud.gcp.spanner.emulator.enabled` is missing in spanner sample docs. It is required per [Spring Cloud GCP Spanner doc](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#configuration-5) if the user want to run an instance on emulator.
> Modify spanner sample docs to instruct user running spanner using emulator

- CONTRIBUTING.md
This PR updates `CONTRIBUTING.md`:
- Adds back build instructions from the old repo’s [contribution guide](https://github.com/spring-attic/spring-cloud-gcp/blob/main/CONTRIBUTING.adoc), along with (slightly adapted) steps for a typical contribution workflow 
- Adds links to `google-java-format` tool and plugins
Some formatting changes to the Markdown was introduced when I auto-formatted the file, but the three sections with actual content diff are:
- Building the Project
- Code reviews (added: typical contribution cycle subsection)
- Code style (added: ref to `google-java-format` tool)
> Update contributing guide to add back build instructions, workflow, and checkstyle tools

- CHANGELOG.md
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateIntegrationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/CachingPublisherFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/CachingPublisherFactoryTests.java
See https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/864.
Add `@PreDestroy` method to shutdown cached `Publisher` in `CachingPublisherFactory`.
> Support publisher shutdown

- docs/src/main/asciidoc/sql.adoc
- docs/src/main/md/sql.md
See https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1055.
Add database username when connecting to cloud sql instance using IAM authentication.
> Modify cloud sql docs to add one step when use IAM authentication

- docs/src/main/asciidoc/sql.adoc
- docs/src/main/md/sql.md
Fixes a simple documentation typo for SQL IAM auth which breaks a link.
Closes #1273 
- this is my first contribution here so go easy if missed something; please let me know and I'll try to work swiftly to get up to spec
- ~I did sign my CLA~ had some proof here but apparently yall got a CI/CD job to check it 🤣
> chore: fix broken SQL IAM auth docs links

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/kms/GcpKmsAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/kms/KmsAutoConfigurationTests.java
- spring-cloud-gcp-autoconfigure/src/test/resources/fake-credential-key.json
fixes #1271.
I find it hard to increase test coverage without exposing more getter methods from `KmsTemplate.class` or `GcpKmsAutoConfiguration.class`. Any thoughts?
> fix(kms): to honor kms credentials when present.

- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/core/BigQueryTemplateIntegrationTests.java
Each test runs in isolation, but when run together, the different schema requirement in `testJsonFileLoadWithSchema` causes it to fail.
Creating a clean table for each test in bigquery to allow each test to specify its own schema fixes the immediate issue.
This testing issue also uncovered a real problem (tests are good!!) -- if writing fails with anything but `DescriptorValidationException`, `IOException` or `InterruptedException`, the thread failure is not passed into the returned future. I'll send a PR for this separately.
> Fix bigquery integration tests

- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryTemplate.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/BigQueryTemplateTest.java
This PR adds a catch-all for any unforeseen errors and passes the error to the returned future.
In normal code, catching `Throwable` is a bad idea -- the error should be allowed to propagate and stop the app. However, when running in a separate thread, an uncaught `Throwable` will simply disappear without a trace, so we have to catch it and hand the error over to the returned future, so that the failure may be acted upon.
Unrelated changes:
* lightly refactored to have the template get created before each test, since every test will need it.
* somehow this test was still on JUnit4. Upgraded to JUnit5.
> Catch generic throwable and pass exception to returned future

- docs/src/main/asciidoc/bigquery.adoc
- docs/src/main/md/bigquery.md
Updating the `bigquery.adoc` and `bigquery.md` to add the documentation of writeJsonStream methods
> chore: Documentation of writeJsonStream methods

- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryTemplate.java
This  change is adding the possibility to be able to change the `CreateDisposition` (`CREATE_IF_NEEDED` or `CREATE_NEVER`) on the `BigQueryTemplate` ackin to how you would currently configure the `WriteDisposition`.
In our use case we have to use `CREATE_NEVER` because we want to prevent even the attempt to create a table in BigQuery. Currently this is only be possible by using a `BigQuery` instance directly, because the `CreateDisposition` is not passed through by the template to the `WriteChannelConfiguration` and eventually the writer falls back to the `CREATE_IF_NEEDED` default.
> Make CreateDisposition configurable on BigQueryTemplate

- generator/generate-one.sh
To replace `http_archive()` rule with `local_repository()` rule for using local repo of `gapic-generator-java`, this PR updates the current approach in generator script of replacement by line number to search and replace with pattern matching.
- Some additional notes for the perl one-liner logic, not sure if they'd be helpful to include as inline comments?
```
```
**Potential conflicts:** with #1313, will just need to update location of change if merged after.
> fix(codegen): use find and replace to switch to local gapic-generator-java repo

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptions.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTemplate.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptionsTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateTests.java
Fixes #1306 which points out a missed condition: when converting Spanner `ReadOption` to `QueryOption`, [`ReadQueryUpdateTransactionOption`](https://github.com/googleapis/java-spanner/blob/d59e2db88a365a6c119040983459eb3f1b98dfe5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java#L51) should also result in a valid conversion.
> fix: add supported type to Spanner read to query option conversion

- .github/workflows/integrationTests.yaml
Switching trigger logic to use `on`.
* PRs will trigger ITs only if
* They have at least 1 change in a folder other than `generat[ed|or]/`. [details](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths)
* The PR has been opened or [`synchronized`](https://github.com/orgs/community/discussions/25161#discussioncomment-3246673)
* Pushes to `main` will also trigger the ITs (e.g. merge a PR)
The logic for excluding ITs from dependabot was moved to the job's `if` entry
> fix(actions): suppress IT only on PRs

- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/spring.factories
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/FirestoreSampleApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserService.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/java/com/example/FirestoreSampleApplicationIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/java/com/example/TestUserClient.java
As part of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/620, the transaction manager autoconfiguration was removed from the main Firestore autoconfig but was not added to Spring's metadata, so it's not automatically loaded.
This PR:
1) Brings back the transaction manager in `spring.factories` (we'll have to re-add for the New Way in Boot 3.0).
2) Adds a service between controller and repository, but for only one method.
3) Strengthens the test by verifying that HTTP call does not fail, but only for one method.
I'll either send a follow-up to do 2) and 3) for the remaining functionality or leave them as an exercise for the reader :)
Fixes #1297.
> Find the lost transaction manager

- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/updateDocs.yaml
- Disabled the following workflows when a PR comes from a fork:
- Integration tests
- Linkage check
- SonarCloud analysis
- Removed the fork procedence check in `updateDocs.yaml` because its `on` clause states that it will only be run from `push`es (i.e. a PR has been merged)
- Confirmed logic is working:
* [fork PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1329) - skips
* [local PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1330) - runs
> fix: correct fork check logic

- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/asciidoc/trace.adoc
- docs/src/main/md/getting-started.md
- docs/src/main/md/trace.md
Noticed two broken links in docs:
- the `README.adoc` link seems redundant, as version already included in code snippet.
- fix link to `cloud-logging`
> fix: removed broken readme link. fix broken cloud-logging link.

- generator/download-repos.sh
- generator/generate-one.sh
Solves an issue mentioned in a [comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1313#issuecomment-1309013396) by @emmileaf in #1313.
Corrects a wrong rebase procedure: Changes from #1315 were successfully added to `generate-one.sh`, but this should be done in `download-repos.sh`
> fix: use logic from #1315

- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
So far the logic allowed either 'push' or 'pull_request' events. This fix allows either a validated 'pull_request' (fork validation) or any other even that is not a PR since these don't require validation
> fix: modify 'if' filter on gh actions to allow non-prs

- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/md/getting-started.md
- generated/README.md
- generator/generate-one.sh
As discussed earlier, adding these items in prep for documentation:
- a `README.md` to `generated/` with header for  a list of modules generated.
- list item generation line into script.
- link from documentation page.
> codegen: adding documentation items for generated modules

- spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/resources/schema.sql
CloudSQL acquired an annoying flake where the table is sometimes not cleaned up correctly. This change should force table deletion before creation in the db initialization stage.
> Drop table before creating

- src/checkstyle/java.header
This PR updates checkstyle to accept single year copyright patterns (e.g.`2022`) in addition to the existing range pattern (e.g. `2022-2022`).
> style: update license header check to accept single year pattern

- generator/download-repos.sh
- generator/googleapis-dep-string.txt
To account for changes in https://github.com/googleapis/gapic-generator-java/pull/1046, Spring related dependencies needs to be added to [WORKSPACE](https://github.com/googleapis/googleapis/blob/38e8b447d173909d3b2fe8fdc3e6cbb3c85442fd/WORKSPACE#L239-L245).
> fix(codegen): add logic to add spring deps to googleapis/WORKSPACE

- generator/googleapis-dep-string.txt
typo in replacement string. `,` should be outside of quotes.
> fix(codegen): typo fix for #1349

- generator/download-repos.sh
- generator/generate-one.sh
**This PR:** edits generator scripts given the separation of the `java_gapic_spring_library` rule in https://github.com/googleapis/gapic-generator-java/pull/1065 (please see its description for context of edits).
The script now makes local edits to:
- `googleapis/repository_rules.bzl` (add switch)
- `google/cloud/<client_lib_name>/v1/BUILD.bazel` (add rule name to load, and rule definition using similar arguments as `java_gapic_library`)
**Note for review:** the initial goal of these changes is to have something to unblock the code generation workflow, but there's currently a lot of perl mess so any suggestions on cleaner/more reliable file processing would be welcomed!
> fix(codegen): modify generator scripts after separation of bazel rules

- generated/pom.xml
- generator/generate-all.sh
- generator/generate-one.sh
- Remove version replacement for generated modules, these versions should be inferred from parent pom.
- set parent version to project version.
Using placeholder for parent version for unblocking generation workflow setup. For future improvements:
- Use `revision` to get versions from spring-cloud-gcp parent pom. This will involve changes for all modules with `spring-cloud-gcp` as parent.
> fix(codegen): remove version replacement for modules.

- .github/dependabot.yml
**This PR:**
* Configures dependabot to ignore major version bumps (which will need manual upgrades)
* Similar to [#846](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/846), tracks some dependencies that we will be suppressing dependabots for while working towards support for Spring Boot 3.0 - see [#1280](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1280)
* Also suppresses dependabots for formatter dependencies brought in as part of codegen - see [#1356](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1356)
Previous manually-invoked dependabot ignores:
* spring-boot-dependencies ([#1357](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1357))
* spring-boot-starter-parent ([#1358](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/ …
> chore: configure dependabot ignores for major version bumps

- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/md/getting-started.md
This documentation line was added as part of #1336. 
Now that we are releasing more frequently, I think it makes sense to revert this change temporarily until those modules are ready for release.
> chore: remove doc mention of generated modules before releasing.

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/DocumentOcrTemplateIntegrationTests.java
There seems to be some behavior change on the client library side leading to below test failure in our integration tests.
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/3655598879/jobs/6177106625
Putting in this temp fix to unblock nightly CI test. For long term, perhaps we should make the test more tolerant to these changes?
```
Error:  Failures: 
Error:    DocumentOcrTemplateIntegrationTests.testDocumentOcrTemplate:75 
Expecting actual:
["Hello World. Is mayonnaise an instrument?",
"Page 2 stuff",
"Page 3 stuff",
"Page 4 stuff"]
to contain exactly (and in same order):
["Hello World. Is mayonnaise an instrument?
",
"Page 2 stuff
",
"Page 3 stuff
",
"Page 4 stuff
"]
but some elements were not found:
["Hello World. Is mayonnaise an instrument?
",
"Page 2 stuff
", …
```
> fix: change expected string to reflect client library behavior change.

- spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/Retry.java
- spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/util/RetryUtil.java
- spring-cloud-gcp-core/src/test/java/com/google/cloud/spring/core/util/RetryUtilTests.java
This PR adds a helper class and util used by https://github.com/googleapis/gapic-generator-java/pull/1140. It defines:
- `Retry` class with getters and setters that enable updating a `RetrySettings` object through spring properties
- `RetryUtil` class that contain merge logic (conditioning to only overwrite fields in the old `RetrySettings` when a new value is configured).
> feat: add helper class and util for RetrySettings configuration

- generator/generate-one.sh
Based on `gapic-generator-java` and `googleapis` both have bazel version fixed:
- https://github.com/googleapis/gapic-generator-java/pull/1164/files
- https://github.com/googleapis/googleapis/blob/4834b4c97ed2577db072d645df393ee246328ee3/.bazeliskrc#L2
This change should be enough for our script to pickup these versions.
> codegen: fix for bazel upgrade issue

- docs/src/main/asciidoc/pubsub.adoc
- docs/src/main/md/pubsub.md
Fixes docs related to keeping a background user thread for command-line applications. This is based on the discussions in #1182
> Fixes docs related to keeping a background user thread - pub/sub

- spring-cloud-generator/googleapis-dep-string.txt
This PR goes together with https://github.com/googleapis/gapic-generator-java/pull/1208 in switching dependency from `spring-cloud-gcp-core` to `spring-cloud-gcp-autoconfigure`.
> fix(codegen): update dependency string replacement

- spring-cloud-generator/download-repos.sh
- spring-cloud-generator/generate-one.sh
- spring-cloud-generator/setup-googleapis-rules.sh
For each library, a hard reset is performed towards the specified commitish. The repo setup previously done in download-repos.sh was moved to generate-one.sh. The hard reset is also due to WORKSPACE and repository_rules changing between commits.
> feat: use googleapis commitish

- spring-cloud-generator/generate-all.sh
- spring-cloud-generator/generate-library-list.sh
Initially brought by #1424, intended to handle a dev-env workflow that was later [deleted](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1424/commits/0da05fa43f104c7d74a751dc4c4d08cddadce494) (do `mvn install` in root). This is now unnecessary.
> chore: remove unnecessary optarg handling in `generate-library-list.sh`

- pom.xml
Temp fix for [`releaseCheck` error](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/3881029407/jobs/6626072510), which is tracked in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1442:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:aggregate-no-fork (aggregate) on project spring-cloud-gcp: An error has occurred in Javadoc report generation: 
Error:  Exit code: 1 - javadoc: error - Error fetching URL: https://cloud.google.com/java/docs/reference/google-cloud-vision/latest/overview.html/
Error: [ERROR] javadoc: error - Error fetching URL: https://cloud.google.com/java/docs/reference/google-cloud-spanner/latest/overview.html/
Error: [ERROR] javadoc: error - Error fetching URL: …
```
> docs: update javadoc links to resolve issue in releaseCheck

- .github/workflows/sonar.yaml
This reverts change in [cffaa6e](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1416/commits/cffaa6e164c7d39bb0675592f80412d2f46d3b55) to unblock a few prs pending on sonar check.
The above change does not work because sonar check is required to merge into main, and the ignore would result in sonar check pending. (e.g. #1443, #1433)
In the meantime, working on alternatives to set jacoco exclude to skip coverage tests for generated code (#1446).
> codegen: remove path to ignore for sonar.

- spring-cloud-previews/google-cloud-language-spring-starter/src/test/java/com/google/cloud/language/v1/spring/LanguageAutoConfigurationTests.java
This PR patches unit tests added in #1355 to all have mock top-level credentials configured. 
@zhumin8 thanks for catching this - feel free to cherry-pick commit 312e42a to unblock your CI testing.
> test(codegen): set top-level mock credentials for language-starter module unit tests

- src/checkstyle/checkstyle-suppressions.xml
This PR defines more specific checkstyle suppressions for generated modules in `spring-cloud-previews` adapted from #1449's commit [9036f7d](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1449/commits/9036f7d80e678d3dce2367db52166e3fa4933c3c). It looks like `spring-cloud-gcp` enforces stricter checkstyle rules ([fail on warning](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/a5a346600e4b123643d9a507144d9167280c8870/pom.xml#L273-L274)) than what is used for the client libraries, and a number of abbreviation to lowerCamelCase edge cases are getting caught here.
- `AbbreviationAsWordInName` suppressions - for abbreviations in service names that appear in generated class names (e.g. `IDSSpringProperties`) , as well as abbreviations in rpc method names (affecting …
> chore(codegen): add checkstyle suppressions for preview modules

- spring-cloud-generator/generate-one.sh
- spring-cloud-previews/pom.xml
This PR cleans up the various changes made in #1407. Two fixes were made
The source of changes was moved to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1422 for which several PRs were made and
are now either closed or merged (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1430, https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1428, https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1427, https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1426, https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1425
, https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1424). https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1423 has not been merged as https://github.com/googleapis/gapic-generator-java/pull/1212 …
> chore: cleanup from 1407

- docs/pom.xml
Reverting the maven-resources-plugin version upgrade to fix the `NoSuchFileException`.
> chore: fix generate-docs.sh NoSuchFileException

- .github/workflows/codeql-analysis.yml
After a major bump in Spring Cloud GCP, the CodeQL-Analyze check failed with invalid target release. The root cause is Java 11 used to compile the code but Java 17 is required.
In this PR:
- setup Java 17
- setup JDK distribution
> chore(ci): Fix CodeQL-Analyze check

- spring-cloud-previews/pom.xml
Adds back #1448, which accidentally got removed as part of #1287.
> chore(codegen): add back release-please annotation

- spring-cloud-generator/googleapis-gapic-string.txt
- spring-cloud-generator/setup-googleapis-rules.sh
This PR unblocks generation script [errors](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/3953287474) when pointing to more recent googleapis committish. This is due to a change in `googleapis/WORKSPACE` ([d7e8de7](https://github.com/googleapis/googleapis/commit/d7e8de775ab827293821077c6c198b32a51260ff)) that modified this file to maven install the gapic-generator-java jar. The spring codegen workflow still relies on editing this to use a locally installed branch of `gapic_generator_java`. 
- This patch adds logic to remove the  `maven_install()` block and add back `gapic_generator_java_repositories()`. 
Note that the longer-term to address this to migrating the spring generator code out of the `gapic-generator-java` repo, and switching to using the …
> chore(codegen): additional replacement logic in googleapis workspace file

- .gitignore
- spring-cloud-generator/generate-all.sh
This PR addresses two cleanup items to go along with the Github Action setup in #1341:
- Updates `.gitignore` to ignore the maven wrapper jar
- Removes `tmp-generate-one-output` at the end of generation script workflow.
> chore(codegen): remove temp output file and update gitignore

- docs/pom.xml
Restore the maven resources plugin to 3.1.0 in `3.x` branch as there's a [bug](https://issues.apache.org/jira/browse/MSHARED-966) in 3.3.0.
> chore(deps): restore maven resources plugin

- .github/dependabot.yml
For dependabot-generated PRs, change the title prefix to `deps: `.
> chore: update dependabot PR title

- spring-cloud-previews/google-cloud-language-spring-starter/src/test/java/com/google/cloud/language/v1/spring/LanguageAutoConfigurationTests.java
This PR fixes formatting of the manually written unit test file so that it is consistent with the formatter run for generated modules. This way, the process of generation will not introduce modification to this file. The corresponding change is removed from the auto-generated PR #1517 in [731923a](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1517/commits/731923af4f40427e3cc083b36b3a7de5ce092f4c).
> test(codegen): adjust formatting for unit test

- spring-cloud-generator/generate-all.sh
- spring-cloud-generator/generate-one.sh
- spring-cloud-generator/spring-cloud-previews-template/README.md
- spring-cloud-previews/README.md
This PR fixes [two items](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1528#issue-1558203562) that needed to be manually patched in the latest generated PR (#1528):
- Residual file from earlier sanity check WIP (#1498)
- Two places where updating README breaks given the current pattern matching logic:
* Removing entries by matching on `$starter_artifactid` alone also removes the line that contains it in the sample dependency snippet above
* Sorting entries pattern-matched on lines containing `:`, which caused issue when lines containing `:` were added in the descriptive section of the readme. Replaced this punctuation as a quick fix, but will need to look into a replacement for the regex going forward.
Added context for each change in in-line comments below.
> chore(codegen): fix script issues with readme and residual files

- spring-cloud-gcp-dependencies/pom.xml
After removal of [spring-cloud-dependencies as parent](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/482c2f586533010ee3c0d92b0d733bcd9d47d044/spring-cloud-gcp-dependencies/pom.xml#L5-L10), copy over scm, url, and issueManagement metadata from root pom.
```
[ERROR]   Rule "pom-staging" failures
[ERROR]     * Invalid POM: /com/google/cloud/spring-cloud-gcp-dependencies/4.0.0/spring-cloud-gcp-dependencies-4.0.0.pom: Project URL missing, SCM URL missing
```
> chore: copy missing metadata from parent pom to spring-cloud-gcp-dependencies pom

- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
Fixes #1537 (hopefully).
We have been observing these flakes more consistently in unitTest and sonar workflows. From discussion in https://youtrack.jetbrains.com/issue/KT-43894, it seems like our multi-threaded mvn commands for unit test and sonar workflows are leading to a race condition on system properties, between the behaviour of [kotlin-maven-plugin](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/dccc57c6619734a98201bcafdc0aa12197161903/spring-cloud-gcp-samples/spring-cloud-gcp-kotlin-samples/pom.xml#L29) and [maven-surefire-plugin](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/dccc57c6619734a98201bcafdc0aa12197161903/spring-cloud-gcp-samples/pom.xml#L141) in the kotlin samples.
This PR adds a suggested workaround from the discussion (I've also triggered …
> ci: workaround for kotlin sample by specifying system properties

- .kokoro/publish_javadoc.cfg
- .kokoro/publish_javadoc.sh
Current `publish_javadoc.sh` was complaining about pyenv 3.7.2 not installed. 
Default pyenv version on the image is 2.3.9
The changes here include installing pyenv 3.7.2 and using it. 
I've also skipped the remove snapshot step that we don't need anymore - 
`./mvnw versions:set --batch-mode -DremoveSnapshot -DprocessAllModules`
> chore: update publish_javadoc.sh

- .kokoro/publish_javadoc.cfg
The build failed. We need jdk17 for this build too.
> chore: updating image to java17 for javadoc publishing

- .kokoro/publish_javadoc.sh
java17 image does not support maven wrapper usage.
> chore: Removing maven wrapper usage in `publish_javadoc.sh`

- .github/workflows/generateAutoConfigs.yaml
A small change to update the commit message and PR title generated by the codegen github action, since future PRs will be updating the modules existing in main. 
- Defaulting prefix to chore, reviewer of the generated PR can override if needed.
Note: this PR is not a blocker for the 4.0.0 release.
> chore(codegen): update auto-generated commit and pr title by gh action

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfigurationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/main/java/com/example/Application.java
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1554
Add a span encoder bean in trace so that `ZipkinAutoConfiguration` doesn't provide encoders with incompatible encoding schema, e.g., JSON.
As a result, customers don't need to exclude `ZipkinAutoConfiguration` in their applications.
> feat: add an encoder bean in Trace auto-configuration

- .kokoro/stage.sh
To try resolving the promote-step issue observed in our last release, this PR adds the `MAVEN_OPTS` workaround as suggested by @ddixit14.
Reference to error from `nexus-staging-maven-plugin`: https://issues.sonatype.org/browse/OSSRH-66257
```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release (default-cli) on project spring-cloud-previews: Execution default-cli of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release failed: No converter available
[ERROR] ---- Debugging information ----
[ERROR] message             : No converter available
[ERROR] type                : java.util.Arrays$ArrayList
[ERROR] converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] message[1]          : Unable to …
```
> chore: add workaround for sonatype issue with Java 17

- spring-cloud-gcp-autoconfigure/pom.xml
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1577
Apart from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1578, there's another `mysql-connector-java` dependency used in auto-configuration module.
> chore(dep): change mysql connector coordinate in auto-configuration

- .github/workflows/generateAutoConfigs.yaml
This PR updates the existing github action to update generated modules, so that when the workflow is triggered from a branch other than `main`, the generated PR uses that branch as the base branch.
Use case: this allows for the workflow to be triggered from a branch created by dependabot (e.g. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1582), and generated PR will contain both the dependabot commits and any updates to `spring-cloud-previews`.
> chore(codegen): allow base branch of github action to be different from main

- src/checkstyle/checkstyle-suppressions.xml
Revisiting the discussion back in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1455 and applying this specific suppression blanketly instead of per-module.
There has been additional methods with this violation from client library/proto changes that are tripping up the [newest update run](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/4256631603/jobs/7405755097): 
```
src/main/java/com/google/devtools/artifactregistry/v1/spring/ArtifactRegistrySpringProperties.java:[468,47] (naming) AbbreviationAsWordInName: Abbreviation in name 'updateVPCSCConfigRetry' must contain no more than '1' consecutive capital letters.
src/main/java/com/google/devtools/artifactregistry/v1/spring/ArtifactRegistrySpringAutoConfiguration.java:[319,21] (naming) …
```
> chore: update AbbreviationAsWordInName checkstyle suppression to blanket for preview modules

- .github/workflows/integrationTests.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
Turning on some checks on push to 3.x branch.
Context: currently troubleshooting some IT failures in the v3.4.5 release PR (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1609) - I think having associated checks for each pushed commit (since dependabot PRs don't run ITs on presubmit) would be helpful in the future.
> chore: turn on ci workflows on push to 3.x branch

- .github/workflows/generateAutoConfigs.yaml
Try switching to if condition within job instead of workflow branch filtering, to see if check can show up as skipped for PRs instead of pending.
Ref: [handling skipped but required checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)
> chore: move branch filtering to if condition in generateLibraries job

- .github/workflows/generateAutoConfigs.yaml
This PR contains two follow-up fixes after https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1656:
- Also moves `type: “opened”` into the if condition, so that the check can be triggered and skipped on synchronize/re-open for existing PRs 
- Switches to use `pull_request` event instead of `pull_request_target`, since we only expect running this workflow on branches within the repo, and not external forks. (Looking into this a bit more, [`pull_request_target`](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows) gives more privileged read/write/secret permissions to the workflow, and runs the action from the trusted target branch instead of the pull request branch. This doesn't work with the existing action unless we additionally …
> chore: fixes for generateAutoConfigs action on pull requests

- .github/workflows/generateAutoConfigs.yaml
This PR adds back a step to checkout pull request branch by name before pushing the new commit, since the checked out ref from PR events is a merge commit like `refs/pull/<pr_number>/merge`. 
- Small change: also renames `BASE_BRANCH_NAME` to `BRANCH_NAME` to avoid confusion with base vs. head terminology for pull request events, where base_ref refers to the target branch (main) 
Previous [error log:](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/4451442073/jobs/7818093824)
```
+ git stash pop
HEAD detached at pull/1660/merge
...
+ git commit -m 'chore: update starter modules in spring-cloud-previews'
[detached HEAD 7543d4c36] chore: update starter modules in spring-cloud-previews
..
+ git push --set-upstream origin …
```
> chore: checkout branch in generateAutoConfigs action before pushing commit

- docs/src/main/asciidoc/secretmanager.adoc
- docs/src/main/md/secretmanager.md
Remove `bootstrap.properties` in Secret Manager docs as this file is deprecated in Spring 3.x.
> fix: fix secret manager docs

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessorTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/test/java/com/example/SqlR2dbcPostgresSampleApplicationIntegrationTests.java
> fix: pass `enable-iam-auth=true` to `spring.r2dbc.properties`

- .github/workflows/compatibilityCheck.yaml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
- .github/workflows/updateDocs.yaml
Resolve #1732 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
run: echo "::set-output name=date::$(date +'%Y-%m-%d' --utc)"
```
**TO-BE**
```yaml
run: echo "date=$(date +'%Y-%m-%d' --utc)" >> $GITHUB_OUTPUT
```
> chore: replace deprecated command with environment file

- .github/workflows/generateAutoConfigs.yaml
- spring-cloud-generator/compute-monorepo-tag.sh
- spring-cloud-generator/generate-all.sh
- spring-cloud-generator/generate-library-list.sh
This PR makes some changes to the current `generateAutoConfigs` action so that it can work with the spring-cloud-gcp’s new setup of using forking-renovate instead of dependabot.
- `workflow_dispatch`: support manually triggering the workflow given branch and optional fork repo name (auto-populated with expected forking-renovate values, so the manual effort will just be clicking the `run workflow` button, but these inputs are also customizable if needed) 
- `pull_request`: a check workflow will trigger upon matching dependabot or renovate bot PR when they open, and fail with error to indicate further action needed. It will also logs branch/fork information about the PR in case inputs for the manual trigger need to be adjusted.   
Looking to merge this before #1686 to unblock this release …
> chore: update generateAutoConfigs action to work with forking-renovate

- pom.xml
JDK17 profile was not correctly applying the configuration due to an invalid artifactId. 
On fixing the artifactId, the multi-line argument was causing javac to throw an exception, so these arguments have been 
~split into dedicated `<arg>` entries~ 
...reverted to the single-line argument it was prior to the introduction of the profile error.
`mvn compile -X` now shows:
```
compilerArgs = [-XDcompilePolicy=simple, -Xplugin:ErrorProne -Xep:UnicodeInCode:OFF, -parameters, -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, ...
```
> fix: profile for jdk17 compiler arguments

- .kokoro/stage.cfg
This is a backport of #1774 from `main` to the stage job configs on `3.x` branch, since we are also making releases from this branch (e.g. #1727).
> ci: Track released artifacts for EO 14028 compliance. (backport of #1774)

- .github/release-please.yml
- spring-cloud-generator/scripts/resources/googleapis_modification_string.txt
Follow-up to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1686, the generator SNAPSHOT version used to modify `googleapis/WORKSPACE` did not get updated after the latest spring-cloud-gcp release
Fixes: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1498#discussion_r1186323967
> chore: update generator version and add to extraFiles for release-please configuration

- .github/workflows/generateAutoConfigs.yaml
- spring-cloud-generator/scripts/generate-all.sh
- spring-cloud-generator/scripts/resources/googleapis_modification_string.txt
This check was not catching the correct location of the error logs
[Confirmation](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/4896975748/jobs/8744449722)
It also fixes a slightly misleading message (no such file) in favor of a proper folder existence check
> chore: fix generation errors check

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandler.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/outbound/PubSubMessageHandlerTests.java
> fix: regression of outbound pubsub message handling (success/failure callbacks both called regardless of success/failure)

- pom.xml
Please see https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1689 for context on this javadoc links removal. Backporting this change to 3.x branch since I had missed it earlier.
> chore: remove links configuration for external packages (backport of #1689)

- pom.xml
Fixes #1842.
As follow-up to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1775 which fixed the maven-compiler-plugin artifact id, this PR adds `spring-boot-configuration-processor `explicitly under `annotationProcessorPaths` configuration for `maven-compiler-plugin`, so that `spring-cloud-gcp-autoconfigure/target/META-INF/spring-configuration-metadata.json` gets generated at compile-time.
> fix: add spring-boot-configuration-processor to maven-compiler-plugin configuration

- pom.xml
This PR reverts the sonar exclusion change from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1816 to unblock CI.
I must have missed something in the exclusion glob pattern, and sonar analysis failed on main after merge ([details](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/runs/13494665939)). Seems like the analysis is picking up on code from generated modules (new in last 30 days: [google-cloud-dataproc-metastore-spring-starter](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-previews/google-cloud-dataproc-metastore-spring-starter)) when they intend to be excluded.
Going to verify this configuration out a bit more on a branch and retry the change (or possibly relocate the tests as suggested).
> test: revert back to blanket sonar exclusion on spring-cloud-previews

- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/pom.xml
This pr cleans up setups in pom for `spring-cloud-gcp-data-firestore-sample` related to native support (configured with outdated `org.springframework.experimental:spring-native-configuration`). It reverts what's added for the sample in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/508.
The relevant native support module has stopped working for a while and was deleted in #1287. So it should be safe to also remove these setups in sample.
> chore: cleanup and remove unsed pom entries

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
This `CloudVisionTemplateIntegrationTests.java` was missed in #1027. 
Migrating it to JUnit5 for consistency.
> chore: migrate vision it test to JUnit5

- docs/pom.xml
Attempt at a workaround for https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1909, following @zhumin8's investigation:
* Update spring-cloud-build version to 4.0.3 ([spring-asciidoctor-backends 0.0.3](https://github.com/spring-cloud/spring-cloud-build/blob/8420504e81493ba1f4630bad9f2b85302a160fdb/pom.xml#L36) is inherited but only available in spring releases repo, so an override is added for this to a later version (0.0.4) available in [maven central](https://mvnrepository.com/artifact/io.spring.asciidoctor.backends/spring-asciidoctor-backends).
> chore(docs): update spring-cloud-build to 4.0.3 and override inherited versions not available in maven central

- spring-cloud-gcp-vision/src/test/java/com/google/cloud/spring/vision/it/CloudVisionTemplateIntegrationTests.java
This `CloudVisionTemplateIntegrationTests.java` was missed in #1027.  Migrating it to JUnit5 for consistency.
> chore: migrate vision it test to JUnit5 (backport #1871)

- pom.xml
- spring-cloud-gcp-samples/pom.xml
Based off https://github.com/mpeddada1/spring-cloud-gcp-current/pull/1, adding `spring-native` for parent pom, and `native-sample` for samples pom.
These added profile should not have any affect on existing workflows.
To be followed by #1933 .
Install and use GraalVM compiler and install native image extension with `gu install native-image`.
To package and run sample as native, instead of `mvn spring-boot:run`:
` mvn clean package -Pnative-sample -DskipTests` then execute the target built.
To run integration tests of sample as native, add relevant system property to `systemPropertyVariables` :
` mvn -Pnative-sample clean test`
> chore: adding profiles for native compile testings

- spring-cloud-generator/pom.xml
- spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden
- spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/EchoSpringPropertiesFull.golden
- spring-cloud-generator/src/test/java/com/google/cloud/generator/spring/composer/goldens/SpringPackageInfoFull.golden
Opening a manual PR to make this gapic-generator-java version bump, as it also requires:
* Spring generator golden test updates, to reflect new copyright year in license header template (https://github.com/googleapis/sdk-platform-java/pull/1720)
* Update protobuf.version used in testing to 3.23.2 (aligning with https://github.com/googleapis/sdk-platform-java/releases/tag/v2.21.0 update)
This PR should supersede https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1929 and https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1928 (currently blocked on presubmits)
> chore(deps): update gapic-generator-java-bom.version to v2.21.0 

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerTemplate.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/src/main/java/com/example/SpannerTemplateExample.java
Cloud Spanner Java client library actually delay the execution of query until the first call to `ResultSet#next()`, hence we can not provide an accurate query elapsed time in spring-cloud-gcp.
In addition, change `SpannerOperations` to `SpannerTemplate` in Spanner sample to align with other samples.
fixes: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1945
> fix: Remove misleading DEBUG log for query elapsed time.

- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessorTests.java
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-r2dbc-sample/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql-r2dbc/pom.xml
Fixes regression brought by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1950
After merging it, the Cloud SQL Mysql R2DBC IT started failing. Details in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1951#issuecomment-1591912710
It was suggested in https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blame/24e35149b74e661276607e6b8341ca518ed91427/docs/r2dbc-mysql.md#L23 (seems like a recent addition)
EDIT: as per https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1955#discussion_r1230352167 I transformed this PR in a migration to `io.asyncer:r2dbc-mysql`
> chore: migrate from `dev.miku:r2dbc-mysql` to `io.asyncer:r2dbc-mysql` 

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/bigquery/GcpBigQueryAutoConfiguration.java
- spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryTemplate.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/BigQueryTemplateTest.java
- spring-cloud-gcp-bigquery/src/test/java/com/google/cloud/spring/bigquery/core/BigQueryTestConfiguration.java
This PR Wires `ThreadPoolTaskScheduler` with `writeJsonStream`. 
User can use `bigQueryThreadPoolTaskScheduler` in order to avoid `java.lang.OutOfMemoryError` which was arising due to too many concurrent write threads working. 
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1599
> fix: Wiring `bigQueryThreadPoolTaskScheduler ` with `writeJsonStream`

- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql/pom.xml
Update spring-cloud-gcp projects to depend explicitly on mysql-socket-factory-connector-j-8, instead of 
relying on the central maven repo to replace dependencies on `mysql-socket-factory` with
`mysql-socket-factory-connector-j-8`. 
This change should not have any effect on the classpath of existing customer applications. Customers
are already using `mysql-socket-factory-connector-j-8`  due to the relocation directive for the `mysql-socket-factory`
dependency. 
MySQL Connector/J 5.0.x is no longer under development and has significant security vulnerabilities. 
We strongly recommend all users update to 8.0.x instead. See the following GitHub issue for more details: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/1243
Fixes #1982
Related to …
> chore(deps): Use an explicit dependency on mysql-socket-factory-connector-j8 

- spring-cloud-gcp-dependencies/pom.xml
The Guava version is already managed in shared-dependencies that are imported into the BOM.
Fixes #2067.
> deps: stop forcing Guava version

- spring-cloud-gcp-dependencies/pom.xml
The Guava version is already managed in shared-dependencies that are imported into the BOM.
Fixes #2067.
> deps(3.x): stop forcing Guava version

- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/main/java/com/example/PollingReceiverApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/test/java/com/example/PollingReceiverIntegrationTest.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/test/java/com/example/PollingReceiverIntegrationTestConfiguration.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-polling-receiver/src/test/resources/application-test.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/main/java/com/example/ReceiverApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/test/java/com/example/ReceiverIntegrationTest.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/test/java/com/example/ReceiverTestConfiguration.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/test/resources/application-test.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/java/com/example/SenderApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/test/java/com/example/SenderIntegrationTest.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/test/java/com/example/SenderTestConfiguration.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/test/resources/application-test.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleTestConfiguration.java
- spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/resources/application-test.properties
In preparation for https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2007.
This PR refactors the `spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample` sample.
> chore: refactor Spring Integration Pub/Sub Sample tests to use unique resources

- docs/src/main/asciidoc/datastore.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreAutoConfigurationTests.java
GCP added support for multiple databases inside single GCP project. It's possible to specify database id on `com.google.cloud.datastore` level, but it was missing on autoconfiguration side.
> feat: add support for Datastore database name configuration #2145

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java
This change ensures that the correct updateTime is extracted for each entity after commit. Previously, commit timestamp was used, but it's wrong when there is no change to the entity.
Fixes: #2163.
> fix: Firestore updateTime extraction after commit

- docs/src/main/asciidoc/datastore.adoc
- docs/src/main/asciidoc/firestore.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreEmulatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/GcpFirestoreAutoConfigurationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/resources/application-test.properties
Also adds routing headers for all Firestore requests.
Backport of #2164.
Fixes #2145.
> feat(3.x): add support for Firestore database id configuration

- .github/workflows/NativeTests.yaml
- pom.xml
- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleLoadSecretsIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleTemplateIntegrationTests.java
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/it/SecretManagerTemplateIntegrationTests.java
Changes in this pr:
- Add secret manager sample app test to native test ci. Tests run for sample application:
```
com.example.SecretManagerSampleIntegrationTests > testDeleteSecret() SUCCESSFUL
com.example.SecretManagerSampleIntegrationTests > testCreateReadSecret() SUCCESSFUL
com.example.SecretManagerSampleIntegrationTests > testApplicationStartup() SUCCESSFUL
```
- Add secret manager module it test to native test ci.
tests run for module:
```
com.google.cloud.spring.secretmanager.it.SecretManagerTemplateIntegrationTests > testReadWriteSecrets() SUCCESSFUL
com.google.cloud.spring.secretmanager.it.SecretManagerTemplateIntegrationTests > testUpdateSecrets() SUCCESSFUL
com.google.cloud.spring.secretmanager.it.SecretManagerTemplateIntegrationTests > testReadMissingSecret() SUCCESSFUL
```
- …
> chore: add secret manager module and sample it tests to native image CI

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
fix: removed topic existence and creation from provisionConsumerDestination
As Pub/Sub subscriber role does have permission to access or create topic so in case `autoCreateResources` is set to false `provisionConsumerDestination` should not perform any admin task e.g fetch or create  subscription or topic. 
So in case subscription name is provided in the configuration with `autoCreateResources` to false provisionConsumerDestination should return `PubSubConsumerDestination` with provided subscription name.
also removed test against creation validation of topic for provision consumer Fixes #2231
> fix: removed topic existence & creation from provisionConsumerDestination

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Backport of #2233 
This change allows Pub/Sub Subscriber role to be sufficient to receive messages from a subscription, when auto-create-resources is disabled.
Fixes: #2231.
> fix(3.x): allow minimal permissions for consumer destination use

- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleLoadSecretsIntegrationTests.java
Part of [this comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/1e8602dd41e63902b8e4193653d2ce5e68e795d3/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSampleIntegrationTests.java#L36) was accidentally removed with changes in #2206.
> chore: add back original comment.

- .github/workflows/NativeTests.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/compatibilityCheck.yaml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
- .github/workflows/updateDocs.yaml
* Adds a parallel-integrationTests and parallel-NativeTests job that copies the non-parallel workflow except for the blocking step prior to integration testing.
* Removes 'compile' from the mvn dependency:go-offline command and adds `-T 1.5C -ntp -B` to speed this step up (~10mins per test before change). Now ~1m
* Uses Temurin for integration testing
> ci: add parallel integration and native tests (#2265)

- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SampleApplicationConfiguration.java
According to our [doc](https://googlecloudplatform.github.io/spring-cloud-gcp//reference/html/index.html#declarative-transactions-with-transactional-annotation-2),  a bean of `DatastoreTransactionManager` is already provided when using `spring-cloud-gcp-starter-data-datastore`. This bean setup in sample should be redundant.
update: 
`DatastoreTransactionManager` bean is pre-configured in [autoconfig code](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/f937b36efb442e5294a357c1a5a14e529aac3fa4/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/DatastoreTransactionManagerAutoConfiguration.java#L60C1-L69).
> chore: removes unnecessary bean from sample app config.

- .github/workflows/NativeTests.yaml
- .github/workflows/scripts/native-image-tests.sh
- spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SampleApplicationConfiguration.java
As discovered in #2007, the Pub/Sub native image job is taking a really long time to run (approx. 145 mins). Instead of all Pub/Sub tests running in a single job, this PR splits them into multiple sub-jobs:
- pubsub-sample which runs template sample tests
- pubsub-integration-sample which runs Spring Integration tests
- pubsub-stream-sample which runs Cloud Stream tests
- pubsub-bus-sample which runs tests under `spring-cloud-gcp-pubsub-bus-config-sample`
> chore: split pubsub tests into sub-jobs

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Fix #2294.
PR #2233 minimized the topic permissions requirement on consumers when `autoCreateResources=false`, but also changed the existing behavior of creating the topic when `autoCreateResources=true`.  This PR reinstates the "create topics in consumers when `autoCreateResources=true`" while also avoiding any topic checks (and thus maintaining minimal permissions requirements) when `autoCreateResources=false`.
CC @SheheryarAamir
> fix: Ensure topic exists in consumer only if autoCreateResources is true (#2294)

- .github/workflows/codeql-analysis.yml
- .github/workflows/compatibilityCheck.yaml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
- .github/workflows/updateDocs.yaml
Go-offline isn't required, takes 10mins if compile is performed at the same time, and appears to be break without compile. This PR provides an option to just remove the stage.
> ci(3.x): remove mvn go-offline

- .github/workflows/NativeTests.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/compatibilityCheck.yaml
- .github/workflows/integrationTests.yaml
- .github/workflows/linkageCheck.yaml
- .github/workflows/sonar.yaml
- .github/workflows/unitTests.yaml
- .github/workflows/updateDocs.yaml
Go-offline isn't required, takes 10mins if compile is performed at the same time, and appears to be break without compile. This PR provides an option to just remove the stage.
> ci: remove mvn go-offline

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Backport fix for #2294 to 3.x branch
> fix(3.x): Ensure topic exists in consumer only if autoCreateResources is true (#2294)

- .github/workflows/NativeTests.yaml
- pom.xml
Adding 2 tests from core module to native ci. 
`spring-cloud-gcp-core` is also tested via module sample tests.
> chore: add spring-cloud-gcp-core tests to native ci.

- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTestsConfiguration.java
- spring-cloud-gcp-data-firestore/src/test/resources/application-test.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/test/resources/application-test.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-starter-firestore-sample/src/test/resources/application-test.properties
With feature in [#2164](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2164), now  Firestore can run in same project as datastore. This PR cleans up settings for integration tests ci so that tests for Firestore module and samples run in the same ci project as the rest.
Modules affected in this change:
- autoconfigure/firestore
- data-firestore
- data-firestore-sample
- starter-firestore-sample
Before this change, these modules are setup to run with `spring-cloud-gcp-ci-firestore` project.
After this change:
- database-id=firestoredb is specified for above module's tests.
- does not specify `firestore.project-id` and get project id info from `DefaultGcpProjectIdProvider`. For integration test ci, it is `spring-cloud-gcp-ci` set via gcloud …
> chore: cleanup firestore ci test resource

- README.adoc
Backport #2351 to 3.x branch README.md. 
Also remove 4.x version ref doc links from this page.
> chore: backport update reference documentation linked in readme

- spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/Book.java
- spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/SpringDataR2dbcApp.java
- spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/java/com/example/WebController.java
- spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/main/resources/static/index.html
- spring-cloud-gcp-samples/spring-cloud-spanner-r2dbc-samples/src/test/java/com/example/SpringDataR2dbcAppIntegrationTest.java
Adding a capability to increment the *read count* of a book, It starts a transaction, and then fetches a book by ID and update the count followed by persisting the changes back to the database before committing the transaction.
> sample: Transactional annotation sample to demonstrate Read-write transaction

- docs/pom.xml
- docs/src/main/asciidoc/firestore.adoc
- docs/src/main/asciidoc/ghpages.sh
> fix: disable profile `CI` when building reference docs

- .github/workflows/updateDocs.yaml
To fix warning:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-java@v1, actions/cache@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
And specify temurin as jdk distribution.
> chore: update github action for update docs.

- .github/workflows/integrationTests.yaml
Followup to comment [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2384#discussion_r1409865100), upgrades `google-github-actions/setup-gcloud` to be consistent with  [nativeTests.yaml](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/.github/workflows/NativeTests.yaml) following example [here](https://github.com/google-github-actions/setup-gcloud#service-account-key-json).
This also fixes deprecation warnings on integration test workflows.
```
"service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
```
> chore: upgrade github action setup-gcloud to v1

- pom.xml
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubSubscriptionHealthIndicatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubSubscriptionHealthIndicatorAutoConfigurationTests.java
- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQuery.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerCompositeKeyProperty.java
These updates introduce source changes that will be required for Spring Boot 3.2.x compatibility, but do not update Spring Cloud GCP to use Spring Boot 3.2.x as Spring Cloud 2022 is not compatible and Spring Cloud 2023 has not yet been GA released.
Attempting to update to Spring Boot 3.2.x will cause a compatibility verification error if using any module requiring Spring Cloud 2022.
Related issue: #2379
> fix: backport Spring Boot 3.2 compatibility updates to Spring Cloud GCP 4.x

- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-r2dbc-sample/src/main/resources/schema.sql
Try to cleanup database before starting test.
According to doc for [`ResourceDatabasePopulator`](https://github.com/spring-projects/spring-framework/blob/cb60f745566767554b620df5663a9e1055f8d26d/spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/init/ResourceDatabasePopulator.java#L87-L92), looks like it can also used to clean up database before initialize.
> chore(test): add cleanup to script to initialize database.

- pom.xml
- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-bigquery/pom.xml
- spring-cloud-gcp-data-datastore/pom.xml
- spring-cloud-gcp-data-firestore/pom.xml
- spring-cloud-gcp-data-spanner/pom.xml
- spring-cloud-gcp-kms/pom.xml
- spring-cloud-gcp-logging/pom.xml
- spring-cloud-gcp-pubsub/pom.xml
- spring-cloud-gcp-samples/pom.xml
- spring-cloud-gcp-secretmanager/pom.xml
- spring-cloud-gcp-security-iap/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-firestore/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-metrics/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgres-r2dbc/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgresql/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-trace/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-vision/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter/pom.xml
- spring-cloud-gcp-vision/pom.xml
Spring Boot starters ships with `spring-jcl` module ([doc](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/logging.adoc)), which comes with its own Commons Logging bridge implemented in the `spring-jcl` module ([Spring Framework doc ](https://docs.spring.io/spring-framework/reference/core/spring-jcl.html)). This has potential conflicts with commons-logging.jar from classpath.
In particular, this causes failure for native compilation when logging gets accidentally initialized at runtime instead of build time. 
This pr tries to exclude `commons-logging` from SCGCP artifacts. With 2 exceptions: preview modules and `spanner-data-spring-data-r2dbc` module.
Also removes this flag for native builds: …
> chore: exclude commons logging from artifacts.

- .github/workflows/integrationTests.yaml
The parallelizing github action being used (softprops/turnstyle@v1) is no longer supported, resulting in unnecessary maximum delays and then all the tests being run in parallel anyhow.
This PR removes the unnecessary delay and unsupported github action.
> ci: remove parallel integration tests

- .github/workflows/updateDocs.yaml
- docs/pom.xml
+ cherry-pick spring-cloud-build dependency fix.
This PR triggers this branch of the updateDocs CI check: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/.github/workflows/updateDocs.yaml#L65
Which when run locally shows no updates occur to the production docs.
> ci: enable updateDocs PR check

- spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/LoggingAppender.java
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/LoggingAppenderTests.java
Support setting logDestinationProjectId.
Backport of #2500.
Fixes: #2496.
> fix(3.x): delegate to all parent logging options

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/admin/SpannerDatabaseAdminTemplate.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/admin/SpannerDatabaseAdminTemplateTests.java
Spanner databases contain both system schemas and a user schema. The current Spring Data Spanner implementation assumes that all table names in a database are unique, but this is not true if a user creates a table that is equal to the name of a system table in one of the system schemas.
Additionally, Spanner could introduce support for user-defined named schemas in the future. This would increase the probability that a single database contains multiple tables with the same name, but in different schemas.
This change fixes any problems that might occur if a database contains multiple tables with the same name in different schemas. The change does not attempt to implement full support for using multiple different schemas with Spring Cloud Data Spanner.
> fix: include schema name in table name

- pom.xml
The [generateAutoConfigs](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/.github/workflows/generateAutoConfigs.yaml) workflow is currently failing and needs more time to get resolved, hence excluding this module from current release.
> chore: Removing spring-cloud-previews module for current release.

- .github/workflows/NativeTests.yaml
Try reenable native tests.
fixes #2455
The failed datastore-basic-sample is related a known issue from spring-data-commons
Fix is scheduled to be released in v3.2.3
> chore: reenable tests with spring boot upgraded to 3.2.2.

- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubTemplateTests.java
In the test case `com.google.cloud.spring.pubsub.core.PubSubTemplateTests`, we configure the `ObjectMapper` to sort the keys when calling `this.objectMapper.writeValueAsBytes(payload)` in the method `JacksonPubSubMessageConverter.toPubSubMessage`.
There is an implementation-dependent operation `this.objectMapper.writeValueAsBytes(payload)` in `JacksonPubSubMessageConverter.toPubSubMessage`, which is identified by the engine [NonDex](https://github.com/TestingResearchIllinois/NonDex).
In the test `PubSubTemplateTests#testPublish_Object`, we assert the value `message.getData().toStringUtf8()` with the json string in particular order, which would not be guaranteed by `ObjectMapper`.
There are possible orders as follow.
```
{"@class":"com.google.cloud.spring.pubsub.core.test.allowed.AllowedPay …
```
> test: configure the ObjectMapper to prevent from flaky behavior

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessor.java
- spring-cloud-gcp-dependencies/pom.xml
In order to use the new version `1.16.0` it's required to use the new method to set artifact ID.
Related to #2503
> fix(deps): update cloud-sql-socket-factory.version to v1.16.0

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/SqlCredentialFactory.java
Use GoogleCredentials instead of deprecated GoogleCredential to fetch user credentials for Cloud SQL.
Fixes #2503
> fix: Use GoogleCredentials to fetch user credentials for Cloud SQL

- docs/src/main/asciidoc/memorystore.adoc
Closes #2661 
Needs to backport to 4.x and 3.x with adjustments.
The newly referenced reactive starter: `spring-boot-starter-data-redis-reactive` ([source](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-starters/spring-boot-starter-data-redis-reactive/build.gradle)) includes `reactor-core` in addition to `spring-boot-starter-data-redis`.
> chore: Update memorystore doc

- docs/src/main/asciidoc/memorystore.adoc
backport of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2703. Removed application.property change that's not applicable to Spring Boot 2.7.x.
> chore: Update memorystore doc 3.x

- .github/workflows/generateAutoConfigs.yaml
- spring-cloud-generator/scripts/generate-library-list.sh
First step to solve #2722.
This should be the minimum set of changes to unblock release with hermetic build changes. 
Further cleanup are needed to simplify this workflow. Will raise separate pr.
> chore: update codegen to use single googleapis commitish.

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/core/PubSubConfigurationTests.java
There has been a significant revision of `ThreadPoolTaskScheduler/Executor` lifecycle capabilities as part of the spring-6.1.x release. It includes a concurrently managed stop phase for `ThreadPoolTaskScheduler/Executor`, favouring early soft shutdown. As a result, the `ThreadPoolTaskScheduler`, which is used for pubsub publishing, now shuts down immediately on `ContextClosedEvent`, thereby rejecting any further task submissions (#2721).
This PR aims to retain the default behavior of spring-6.1.x but provides config options to leverage the `lateShutdown` of the underlying `ThreadPoolTaskScheduler`, such as:
`spring.cloud.gcp.pubsub.publisher.executor-accept-tasks-after-context-close=true`.
References:
1. https://github.com/spring-projects/spring-framework/issues/32109#issuecomment-19102730 …
> Support spring 6.1.x lifecycle changes/late-shutdown for pubsub publisher scheduler

- .github/workflows/NativeTests.yaml
- .github/workflows/compatibilityCheck.yaml
- .github/workflows/integrationTests.yaml
- docs/src/main/asciidoc/alloydb.adoc
- docs/src/main/asciidoc/getting-started.adoc
- docs/src/main/asciidoc/index.adoc
- docs/src/main/asciidoc/sagan-index.adoc
- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/alloydb/AlloyDbEnvironmentPostProcessor.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/alloydb/AlloyDbProperties.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/alloydb/package-info.java
- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/spring.factories
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/alloydb/AlloyDbEnvironmentPostProcessorTests.java
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/README.adoc
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/main/java/com/example/AlloyDbApplication.java
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/main/java/com/example/WebController.java
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/main/resources/application.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/main/resources/data.sql
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/main/resources/schema.sql
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/test/java/com/example/AlloyDbSampleApplicationIntegrationTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-alloydb-sample/src/test/resources/logback-test.xml
- spring-cloud-gcp-starters/pom.xml
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-alloydb/.repo.metadata.json
- spring-cloud-gcp-starters/spring-cloud-gcp-starter-alloydb/pom.xml
This PR adds a component to allow our customers to connect to [Google Cloud AlloyDB](https://cloud.google.com/alloydb) instances using Spring Boot with the [Java Connector](https://github.com/GoogleCloudPlatform/alloydb-java-connector) integration.
It includes a starter, autoconfigure, sample, associated integrations tests and documentation.
Issue related: https://github.com/GoogleCloudPlatform/alloydb-java-connector/issues/151
> feat: Spring Cloud AlloyDB integration

- spring-cloud-generator/scripts/generate-library-list.sh
- spring-cloud-generator/scripts/generate-steps.sh
- spring-cloud-generator/scripts/generate.sh
follow up to #2726. This pr tries to simplify logic now that googleapis commitish is consistent for all mono repo, it is not a blocker for current release cycle. 
- replace old logic to parse proto path from "OwlBot.yaml" file, to utilize the new "generation_config.yaml" and parse GAPIC.proto_path. Keep current logic to only grab latest stable version for now.
- This step is done inside the loop for each library directory, look for library config by `api_shortname`. This is sufficient for current selection (stable libs). But noted  `api_shortname` is not unique identifier for libraries in config. Need followup on this.
- remove logic to checkout versioned proto folders, and set googleapis_committish directly from config.
> chore(codegen): adopt hermetic build configs and simplify logic

- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/alloydb/AlloyDbEnvironmentPostProcessor.java
- spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/test/java/com/example/SqlPostgresSampleApplicationIntegrationTests.java
Making `alloydb-jdbc-connector` optional dependency in autoconfig module.
Fixes: #2847.
> fix: AlloyDB should not load when Postgres starter is used

- .github/sync-repo-settings.yaml
Use `Build with Sonar` as that's the job name defined: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/8f515d16c03c805cc8cb3ccb1e4a222a537b9b2e/.github/workflows/sonar.yaml#L17
My suspicion is that `SonarCloud Code Analysis` isn't matching and the jobs listed below are ignored.
> chore: Fix sync-repo-settings.yaml file

- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfigurationTests.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/SpannerMappingContext.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/mapping/typeadapter/InstantTypeAdapter.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityReaderTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/mapping/typeadapter/InstantTypeAdapterTest.java
This PR adds a default `TypeAdapter` to the Spanner Mapping Context, enabling seamless mapping of java.time.Instant. Consequently, the need to include `--add-opens java.base/java.time=ALL-UNNAMED` in JVM arguments is eliminated.
Solves https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2576
> feat: #2576 Added typeadapter to read and write Instant values.

- .github/workflows/generateAutoConfigs.yaml
- spring-cloud-generator/scripts/generate-library-list.sh
Generate Spring Auto-Configurations is currently failing on `securitycenter`'s module due it having a duplicate api_shortname (https://github.com/googleapis/google-cloud-java/blob/main/generation_config.yaml#L1666).
This updates the script to get the values needed from `generation_config.yaml` rather than looping through `google-cloud-java` folders and mimics the hermetic build script logic for those values. It uses `library_name` if it exists (which is the unique moniker if there is a duplicate `api_shortname`).
It removes `language` as a variable as I didn't see it being used elsewhere in the script.
This also updates the default value of the PR branch name to the correct value.
> fix: update generate-library-list.sh for duplicate api_shortnames

- spring-cloud-generator/scripts/generate-library-list.sh
- spring-cloud-generator/scripts/sanity-checks.sh
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2890
This updates the columns `sanity-checks.sh` checks for to match the ones generated by `generate-library-list.sh`.
Example error: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/9096934589/job/25003567600
```
accessapproval,  google/cloud/accessapproval/v1,  com.google.cloud:google-cloud-accessapproval,  java/accessapproval, 
sanity check failed:
the library list entry 'accessapproval' has an empty required cell - see /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-
```
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/commit/df9f7051807f9a7002674bae5d25f01fa1350947#diff-d70307c629e3ee96cc0a222bda6e4cc1e02a27d95691b81c4c66fa51883ab3a0 removed the `googleapis_committish` column in …
> fix: update sanity-checks.sh

- spring-cloud-generator/scripts/generate-library-list.sh
I erroneously mislabeled the variable here: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2891/files#diff-d70307c629e3ee96cc0a222bda6e4cc1e02a27d95691b81c4c66fa51883ab3a0
This fixes to use `distribution_name` consistently. 
For: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2890
> chore: cleanup generate-library-list.sh

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/properties/PubSubConsumerProperties.java
- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
Adds a way to configure the expiration policy on auto-created subscriptions.
The expiration policy contains a single field, `ttl` which is a Duration.
When the `ttl` is not set, the Pub Sub backend sets its own default of 31 (no expirationPolicy set on API request).
When the `ttl` is set to a >0 duration, that duration is configured for auto-created Subscriptions (expirationPolicy with ttl set on API request).
When the `ttl` is set to a <= 0 duration, the `ttl` is interpreted as "Never", and the auto-created Subscriptions will not expire (expirationPolicy with no ttl set on API request).
Fixes #2876
> feat: configurable expiration policy on auto-created subscriptions

- docs/src/main/asciidoc/logging.adoc
- spring-cloud-gcp-logging/src/main/resources/com/google/cloud/spring/logging/logback-appender.xml
- spring-cloud-gcp-logging/src/test/java/com/google/cloud/spring/logging/LoggingAppenderTests.java
Fixes #2906 
Note that this only changes the Spring Cloud GCP `STACKDRIVER` appender's default. It does not change the base java-logging-logback's appender which [defaults to ERROR](https://github.com/googleapis/java-logging-logback/blob/main/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L302).
> fix: stackdriver logback appender now defaults to flushlevel off (#2906)

- pom.xml
In this PR:
- Remove `micrometer-tracing-bom` from pom.xml because this dependency is managed by spring-boot.
> chore: remove micrometer-tracing

- spring-cloud-gcp-samples/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#2975
> fix: Revert "deps: bump org.springframework.boot:spring-boot-starter-parent from 3.2.5 to 3.3.1"

- .github/workflows/showcaseTests.yaml
This prevents the check from showing on PRs that target other release branches (`3.x` and `4.x`)
> chore: use showcase autoconfig check only on PRs against `main`

- README.adoc
Reported in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3020
This is a manual fix for now.
> docs: Update README links

- spring-cloud-generator/pom.xml
This has been out of sync for a while. Update to be consistent with [gapic-generator-java](https://github.com/renovate-bot/gapic-generator-java/blob/308aeafc9f04795d2e1df8206c84689b11c4323a/gapic-generator-java-pom-parent/pom.xml#L34)
> chore(test): update protobuf version in spring-cloud-generator to 3.25.3

- .github/dependabot.yml
I'm hoping this will prevent dependabot PRs like this one which are incorrectly trying to update 4.x's Spring Boot version due to some un-ignored dependencies having updates: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2995
> ci: use dependabot config wildcards to cover all boot and cloud artifacts

- spring-cloud-generator/scripts/generate-library-list.sh
- spring-cloud-generator/scripts/resources/manual_modules_exclusion_list.txt
This fixes the autoconfig generation by excluding two libraries that do not have a `java_gapic_library` rule in their BUILD.bazel files ([example](https://github.com/googleapis/googleapis/blob/master/google/cloud/alloydb/connectors/v1/BUILD.bazel) for alloydbconnectors).
> chore: fix autoconfig module generation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
config.yml mirrors https://github.com/googleapis/google-cloud-java/blob/main/.github/ISSUE_TEMPLATE/config.yml
> docs: add Google Cloud Support link to new issues templates and choices

- .github/workflows/showcaseTests.yaml
- spring-cloud-generator/scripts/generate-steps.sh
- spring-cloud-generator/scripts/resources/googleapis_modification_string.txt
- spring-cloud-generator/showcase/showcase-spring-starter/src/test/java/com/google/showcase/v1beta1/spring/EchoAutoConfigurationTests.java
Need this adjustment due to changes in `googleapis/WORKSPACE` change [here](https://github.com/googleapis/googleapis/commit/cf16946acfefb6f5a33122802ebbaebf5bb45645).
To fix: 
Spring Auto Generation is failing: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/10376314314
```
[INFO] Scanning for projects...
Error: ] Some problems were encountered while processing the POMs:
Error:  Child module /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-previews/google-cloud-workstations-spring-starter of /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-previews/pom.xml does not exist @ 
Error:  Child module /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-previews/google-cloud-workflows-spring-starter of …
```
> fix: change to generation script in manipulating googleapis/WORKSPACE.

- README.adoc
update links to documentation and javadocs after releases: [v5.5.1](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v5.5.1), [v4.10.7](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v4.10.7), [v3.8.7](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v3.8.7).
> docs: Update README post releases

- docs/src/main/asciidoc/core.adoc
context: b/337025794
Adjusting the sequence mentioned in doc to make it clear that ADC is the default, also adding a note about potential security risk for using service account keys.
> docs: adjust spring-cloud-gcp-core documentation auth guides.

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-dead-letter-sample/src/main/java/com/example/SinkExample.java
- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-functional-sample/spring-cloud-gcp-pubsub-stream-functional-sample-sink/src/main/java/com/example/Sink.java
Added object mapper bean to [fix issue with spring cloud stream 4.1.3 failing to load objects in application context when loading their ObjectMapper](https://github.com/spring-cloud/spring-cloud-stream/issues/2977) causing PubSubDeadLetterTopicSampleAppIntegrationTest when trying to deserialize the object from the stream.
> fix: CastClassException in PubSubDeadLetterTopicSampleAppIntegrationTest #3139

- spring-cloud-gcp-dependencies/pom.xml
This issue occurred due to a mismatch in the OpenTelemetry library include in the BigQuery google cloud library and the Open telemetry version included in sprint-boot.  Fix: add correct version of OpenTelemetry dependency in spring-cloud-gcp for google cloud libraries to work with older versions of spring.
> fix: noSuchMethodError in BigQuerySampleApplicationIntegrationTests #3140

- docs/src/main/asciidoc/kms.adoc
> docs: add documentation for kms universe domain and endpoint properties

- .kokoro/publish_javadoc.sh
The default javadoc output path was changed from target/site to target/reports in https://github.com/apache/maven-reporting-impl/pull/26 and was introduced in maven-javadoc-plugin:3.10.0 in https://github.com/apache/maven-javadoc-plugin/pull/204.
The maven-javadoc-plugin was updated from 3.8.0 to 3.10.0 in v5.6.0 ([PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3164)). This fix aims to address the current failure in the publish_javadoc job:
```
pushd target/site/apidocs/
github/spring-cloud-gcp/.kokoro/publish_javadoc.sh: line 29: pushd: target/site/apidocs/: No such file or directory
[ID: 8846228] Command finished after 191 secs, exit value: 1
```
> chore: fix javadoc job by updating to the new javadoc output path

- spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/util/KeyUtil.java
- spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/core/util/KeyUtilTest.java
If you override the default database ID and are using `@Descendants` annotation the database ID wasn't getting copied over when migrating keys from ancestor to child
> fix: Descendants entities losing database ID from parent (#3142)

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerMutationFactoryImpl.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerMutationFactoryImplTests.java
In the case that parent and child have multiple primary keys, do not fail key match validation if both have a null value.
> fix: handle null primary keys between parent and child objects

- .kokoro/publish_javadoc.sh
Backporting https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3184 to 3.x branch.
> chore(3.x): fix javadoc publish job by updating to the new javadoc output path

- .kokoro/publish_javadoc.sh
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3185
> chore(4.x): fix javadoc publish job by updating to the new javadoc output path

- README.adoc
We'd love to accept your patches and contributions to this project. There are just a few small
guidelines you need to follow before opening an issue or a PR:
1. Ensure the issue was not already reported.
2. Open a new issue if you are unable to find an existing issue addressing your problem. Make sure
to include a title and clear description, as much relevant information as possible, and a code
sample or an executable test case demonstrating the expected behavior that is not occurring.
3. Discuss the priority and potential solutions with the maintainers in the issue. The maintainers
would review the issue and add a label "Accepting Contributions" once the issue is ready for
accepting contributions.
4. Open a PR only if the issue is labeled with "Accepting Contributions", ensure the PR …
> docs: Update README.adoc for v5.6.0, v4.10.8 and v3.8.8

- .github/workflows/integrationTests.yaml
- .github/workflows/unitTests.yaml
see: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> fix(dep): update actions/upload-artifact@v2 to v4 as v2 was deprecated and now fails workflows

- spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/main/resources/META-INF/native-image/com/google/cloud/storage-integration/native-image.properties
- spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/src/main/resources/META-INF/native-image/com/google/cloud/storage-sample-scgcp/native-image.properties
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3147
> fix: added native image class initialization workaround to storage samples

- docs/src/main/asciidoc/bigquery.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/bigquery/GcpBigQueryAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/bigquery/GcpBigQueryProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/bigquery/GcpBigQueryAutoConfigurationTests.java
This PR introduces the following changes:
- Introduces `spring.cloud.gcp.bigquery.universe-domain` property to customize the universe domain in `BigqueryOptions` (option to customize endpoint is not provided in the client library) and `BigQueryWriteClient` if these values aren't `null`. 
- Introduces `spring.cloud.gcp.bigquery.endpoint` property to customize the endpoint and host in `BigQueryWriteClient` and if this value isn't `null`. Since Biqguery accepts `host` instead of `endpoint`, the endpoint is formatted to the `https://service.universeDomain` format before being set to Bigquery. 
- Adds unit tests in `GcpBigQueryAutoConfigurationTests` verify that the client settings have been correctly set. 
End-to-end verification with test environment endpoints have been documented in a …
> feat: add properties to set universe domain and endpoint in bigquery

- .github/workflows/generateAutoConfigs.yaml
- pom.xml
This workflow step "Compile non-autogen libraries" but is trying to install all modules. This leads to failures https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3304#issuecomment-2423226206 because certain rpcs are removed (https://github.com/googleapis/google-cloud-java/pull/11237).
duplicating the profiles might not be the best way, but `-pl '!spring-cloud-previews' ` is not working for me. This is to  unblock release.
> chore: fix generate workflow to compile on non-autgen libraries

- docs/src/main/asciidoc/sql.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/GcpCloudSqlProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/sql/CloudSqlEnvironmentPostProcessorTests.java
This adds JDBC properties needed for lazy refresh, service account impersonation, universe domains, and alternate 
SQL Admin API endpoints to the JDBC configuration for a Cloud SQL JDBC connection. 
See #3285 
This is related to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/2065.
> feat: Add all additional Cloud SQL Java Connector parameters 

- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfigurationTests.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/core/PubSubConfiguration.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactory.java
- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactory.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultPublisherFactoryTests.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/support/DefaultSubscriberFactoryTests.java
Notable Changes:
- Adds subscription-specific property for universe domain to customize `Subscriber`
- Adds global subscriber property for universe domain. In terms of priority. The subscription-specific property takes precedence if both global and subscription-specific properties are set. If subscription-specific configuration is not set then the global configuration is picked.
- Adds global publisher property for universe domain to customize `Publisher`. 
Verified behavior manually in separate test plan document.
> feat: add property to customize universe domain in Pub/Sub

- .kokoro/common.sh
Since we're no longer using trampoline.py, the logic to create a tmp dir needs to be migrated from it directly to the build script
> fix: migrate logic to create tmpdir to build script (#3367)

- spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java
- spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQueryTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserRepository.java
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2859 
This PR always includes a query limit of 1 when either findFirst or findTop are used.
> fix: include limit in query for findFirst and findTop support in Firestore

- spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapter.java
- spring-cloud-gcp-pubsub/src/test/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapterTests.java
> feat: log stacktrace

- docs/src/main/asciidoc/pubsub.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorProperties.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfigurationTests.java
We have received an internal request from the Pub/Sub team to increase the default from its current 2s value. (See b/380915972)
(There was a previous default timeout value increase from 1s to 2s: #419)
> fix: increase default pubsub health indicator timeout from 2000ms to 5000ms

- spring-cloud-generator/scripts/resources/googleapis_modification_string.txt
`override_targets` is removed from googleapis/WORKSPACE in cl/696966324
> chore: remove override_targets

- spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample/pom.xml
Reverts GoogleCloudPlatform/spring-cloud-gcp#3433
According to https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions 4.2.x is compatible with Spring Cloud 2023.0 and 2024.0 (our 5.x, 6.x), 4.1.x compatible with 2022.0 (4.x branch)
> deps: revert spring-cloud-config.version from 4.2.0 to 4.1.3"

- .github/dependabot.yml
context: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3448
our 4.x branch should be compatible with Spring Cloud 2022.0, and thus Spring Cloud Config 4.1.x
> chore: update dependabot to ignore spring-cloud-config updates for 4.x

- docs/src/main/asciidoc/spanner.adoc
The original text says:
> Other Google Cloud database-related integrations like Spanner and Firestore can introduce `PlatformTransactionManager` …
However, the docs _are_ about Spanner integration.
> docs: fix references about other integrations in spanner doc

- docs/src/main/asciidoc/spanner.adoc
backport https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3413
> docs: fix references about other integrations in spanner doc (#3413)

- .github/workflows/NativeTests.yaml
See deprecation notice: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Native test workflows are failing now:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/12811784967
Other workflows are already upgraded in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3204
This change should also be backported to 4.x (failed workflow [log](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/12811782688))
> chore: update native tests actions/upload-artifact to v4.

- .kokoro/publish_javadoc.sh
use one provided in docker image
> fix: do not explicitly set python version for publish-javadoc script

- .github/workflows/sonar.yaml
sonar checks from forks does not have access to secret so sonar ci constantly failing for them
> chore: Disable Sonar if PR comes from a fork

- docs/src/main/asciidoc/secretmanager.adoc
This PR explains the introduction of the `sm@` syntax introduced by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3411
From its description:
We will introduce support for resolving values of the form `sm@secret_id` in addition to the already existing `sm://secret_id` format. Users should move away from `sm://` and use `sm@` instead. Usage of `sm://` will raise a warning about this being removed in the future. This has been tested using `spring-framework:6.2.2-SNAPSHOT`.
The introduction of this syntax was suggested in a discussion of a regression caused by spring-framework:6.2.1 - see https://github.com/spring-projects/spring-framework/issues/34124
> docs: update secret manager documentation

- docs/src/main/asciidoc/core.adoc
fixes #3177.
Putting extra note to avoid confusion.
> docs: add clarification for `spring.cloud.gcp.core.enabled`

- .github/workflows/generateAutoConfigs.yaml
The job https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/13709162243 failed with 
```
remote: Permission to GoogleCloudPlatform/spring-cloud-gcp.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/GoogleCloudPlatform/spring-cloud-gcp/': The requested URL returned error: 403
```
This is because the GH actions bot does not have repo access. We here configure the action to use Cloud Java Bot instead.
> chore: use cloud java bot token in autoconfig generation job checkout

- docs/src/main/asciidoc/secretmanager.adoc
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpProperties.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java
- spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSamplePropertyIdTest.java
fixes #3181 , also fixes #3564
cherry-picked changes from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3383 to allow ci properly run. Adding tests.
@PatrickGotthard 's original comment on root cause: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3181#issuecomment-2478682585
When using Secret Manager (sm) module, expected behavior for GcpProjectIdProvider should be:
- in Spring Bootstrap Phase (where sm if configured), order of discovery: secretmanager.project-id >>  gcp.project-id >> default (according to DefaultGcpProjectIdProvider)
- in Application Context, GcpProjectIdProvider bean should behave similar to other modules, with no knowledge of secretmanager.project-id, thus: gcp.project-id >> default
Current behavior prior to this fix, the discovery order …
> fix: GcpProjectIdProvider when using Secret Manager

- spring-cloud-gcp-autoconfigure/pom.xml
- spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3560 ☕ 
It marks the secretmanager dependency as optional. The config loader in the Secret Manager autoconfig was assuming the existence of the now optional Secret Manager integration.
We now check for the class to be present before resolving the properties
> fix: secretmanager to be an optional dep in autoconfig module

- spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java
- spring-cloud-gcp-pubsub-stream-binder/src/test/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java
fix: #3694   Producer destination: ensure topic exists or create one only if auto create resource is true
> fix: #3694: Producer destination: ensure topic exists or create one only if auto create resource is true

- .github/workflows/NativeTests.yaml
- spring-cloud-gcp-dependencies/pom.xml
- spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/resources/application.properties
- spring-cloud-gcp-secretmanager/src/main/java/com/google/cloud/spring/secretmanager/aot/SecretManagerRuntimeHints.java
- spring-cloud-gcp-secretmanager/src/main/resources/META-INF/spring/aot.factories
- spring-cloud-gcp-secretmanager/src/test/java/com/google/cloud/spring/secretmanager/aot/SecretManagerRuntimeHintsTest.java
[Context doc](https://docs.google.com/document/d/1bOeGtVFLsq5ts71If5pFXCvHIeNpbtBRvF6XQfavLZs/edit?tab=t.0#heading=h.gxq6ycxusimq)
Includes runtime hint for secret manager as per https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3706#discussion_r2050999672
Apr 15, 2025 the Cloud SQL folks solved the concern for Graal 17 support in [jdbc-socket-factory#2140](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/2140#event-17212837470) by removing the flag. They released [1.24.2](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.24.2) with this change.
> chore: add JDK 17 to Native Tests pool

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/SpannerTypeMapper.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructAccessor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-dependencies/pom.xml
For https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3756#issuecomment-2874348012. Emulating https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2662.
The Interval datatype was added in the Spanner client library in https://github.com/googleapis/java-spanner/pull/3714 (v6.90.0)
Additionally, the java.util.UUID support was added in https://github.com/googleapis/java-spanner/pull/3839 and https://github.com/googleapis/java-spanner/pull/3572
This PR addresses the following failures: 
```
[ERROR] Failures: 
[ERROR]   SpannerWriteMethodCoverageTests.allKnownMappingTypesTest:75 
Expecting actual:
{java.lang.Boolean=com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriter$$Lambda$424/0x00007fbe2c0d3e50@383bfa16, …
```
> fix: update libraries-bom to 26.60.0 and add support for Interval and UUID

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/SpannerTypeMapper.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructAccessor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-dependencies/pom.xml
Backport of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3769
BEGIN_COMMIT_OVERRIDE
deps: bump com.google.cloud:libraries-bom from 26.57.0 to 26.60.0
feat(spanner): support Interval and UUID types.
END_COMMIT_OVERRIDE
> fix(4.x): update libraries-bom to 26.60.0 and add support for Interval and UUID

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/SpannerTypeMapper.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructAccessor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-dependencies/pom.xml
Backport of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3769
BEGIN_COMMIT_OVERRIDE
deps: bump com.google.cloud:libraries-bom from 26.57.0 to 26.60.0
feat(spanner): support Interval and UUID types.
END_COMMIT_OVERRIDE
> fix(5.x):  update libraries-bom to 26.60.0 and add support for Interval and UUID

- spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringAutoConfiguration.java
- spring-cloud-generator/showcase/showcase-spring-starter/src/main/java/com/google/showcase/v1beta1/spring/EchoSpringProperties.java
- spring-cloud-generator/showcase/showcase-spring-starter/src/test/java/com/google/showcase/v1beta1/spring/EchoAutoConfigurationTests.java
The generator was updated in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3757. This PR is to address the following failures we've been seeing in the release PR: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3697#issuecomment-2881639794
> chore: update showcase tests for generator-java-bom 2.57.0

- pom.xml
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/SpannerTypeMapper.java
- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/convert/StructAccessor.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessorTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriterTests.java
- spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/convert/TestEntities.java
- spring-cloud-gcp-dependencies/pom.xml
Backport of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3769
BEGIN_COMMIT_OVERRIDE
deps: bump com.google.cloud:libraries-bom from 26.57.0 to 26.60.0
feat(spanner): support Interval and UUID types.
END_COMMIT_OVERRIDE
> fix(3.x): update libraries-bom to 26.60.0 and add support for Interval and UUID

- .github/workflows/unitTests.yaml
- pom.xml
this is in order to support graalvm upgrade
This required an upgrade in errorprone to support the support JDK 24
> chore: add jdk 24 to test matrixes

- .kokoro/stage.sh
- pom.xml
- spring-cloud-gcp-dependencies/pom.xml
As the preparation for Central Portal API publication, we need to wrap nexus-staging-maven-plugin with a profile.
The release scriptm, which uses existing OSSRH infra, is updated to activate the release-sonatype profile.
The profile name matches java-shared-config.
https://github.com/googleapis/java-shared-config/blob/main/native-image-shared-config/pom.xml#L112
I'll have to make similar changes to other maintained branches.
b/422164249
> ci: wrap nexus-staging-maven-plugin with a profile

- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsStreamingMessageSourceTests.java
Applying the mock logic of #3840 to the 5.x branch.
> fix: mock OffsetDateTime (5.x)

- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/integration/inbound/GcsStreamingMessageSourceTests.java
Applying the mock logic of #3840 to the 4.x branch.
> fix: mock OffsetDateTime (4.x)

- spring-cloud-gcp-dependencies/pom.xml
The latest run failed with `[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy (injected-nexus-deploy) on project spring-cloud-gcp-dependencies: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy failed: Server credentials with ID "ossrh" not found!` This is a typical error when nexus-staging-maven-plugin is not wrapped by a profile.
`suztomo@suztomo2:~/spring-cloud-gcp$ mvn clean deploy -V     -DaltDeploymentRepository=local::default::file:${local_staging_dir}     -DskipTests=true     -P=-release-sonatype     -P=-release-staging-repository     -P=-clirr-compatibility-check     -P=-checkstyle-tests     -Dgpg.executable=gpg   -Dgpg.homedir="${GPG_HOMEDIR}"` succeeded.
> ci: wrap nexus-staging-maven-plugin the dependencies module

- spring-cloud-generator/pom.xml
Update in sync with sdk-platform-java
merge when  gapic-generator-java-bom gets upgraded.
> chore: upgrade protobuf version to v3.25.8

- spring-cloud-gcp-dependencies/pom.xml
manual create while https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3808 is not resolved.
> deps(5.x): bump com.google.cloud:libraries-bom from 26.61.0 to 26.62.0

- spring-cloud-gcp-dependencies/pom.xml
manual create while https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3808 is not resolved.
> deps(3.x): bump com.google.cloud:libraries-bom from 26.61.0 to 26.62.0

- .github/workflows/unitTests.yaml
- .kokoro/publish_javadoc.sh
- .kokoro/stage.sh
- pom.xml
- spring-cloud-gcp-dependencies/pom.xml
- Wrap nexus-staging-maven-plugin in the release-sonatype profile.
- Use "performRelease" Maven property to match the main branch and the new release script.
- maven-source-plugin is not needed here any more (reference: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/commit/3441f06f24e83e3def7a480f0773ff6ebce6a493)
> ci: wrap nexus-staging-maven-plugin (5.x)

- spring-cloud-gcp-dependencies/pom.xml
Created manually due to Issue: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3808
> deps(3.x): bump com.google.cloud:libraries-bom from 26.62.0 to 26.63.0

- spring-cloud-gcp-dependencies/pom.xml
Created manually due to Issue: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3808
> deps(4.x): bump com.google.cloud:libraries-bom from 26.62.0 to 26.63.0

- spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/UserAgentHeaderProvider.java
- spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/it/GoogleStorageIntegrationTests.java
This PR is created based on #3676.
[StorageOptions](https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java#L41) is Serializable. It extends [ServiceOptions](https://github.com/googleapis/sdk-platform-java/blob/0be1e9670079bcf6a9246d0284e59001c24242ea/java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L83) in google-cloud-core. So this UserAgentHeaderProvider that is set to StorageOptions [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/a2efc4af6b39d82df0f636f2dd8b03fa91bff0a4/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/storage/GcpStorageAutoConfiguration.java#L86) in autoconfig needs to be Serializable.
serialVersionUID is …
> fix: make UserAgentHeaderProvider Serializable

- docs/src/main/asciidoc/parameter.adoc
Fixes https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3981
Parameter manager is GA since https://github.com/googleapis/googleapis/commit/592aef543abdb51885ff85570d126f7885cec443
```
$ gcloud parametermanager parameters --help | head -n 5
NAME
gcloud parametermanager parameters - manage Parameter Manager parameter
resources
```
> docs: remove beta subcommand for GA library "parameter manager"

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
spanner IT fails for `deleteAllById_doesNothingOnEmptyIds` test with error from Spanner:
`INVALID_ARGUMENT: Failed to initialize transaction due to invalid mutation key.`
**Trigger of this behavior change:**
spanner activated multiplexed sessions by default in [googleapis/java-spanner#3996](https://github.com/googleapis/java-spanner/pull/3996), which triggers this error. 
When issuing a write() with a Mutation that has an empty KeySet produces an exception in Multiplexed clients (see [pr](https://github.com/googleapis/java-spanner/pull/4023)), but does a no-op in non-multiplexed ones. Unlike Regular session, multiplex session needs a valid mutation to generate a precommit token.
Fixes #4046
> fix: check for empty before delete

- docs/src/main/asciidoc/index.adoc
> Include `parameter.adoc` in main documentation structure

- spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java
backport fix from #4047
spanner IT fails for `deleteAllById_doesNothingOnEmptyIds` test with error from Spanner: `INVALID_ARGUMENT: Failed to initialize transaction due to invalid mutation key.`
**Trigger of this behavior change:**
spanner activated multiplexed sessions by default in [googleapis/java-spanner#3996](https://github.com/googleapis/java-spanner/pull/3996), which triggers this error. When issuing a write() with a Mutation that has an empty KeySet produces an exception in Multiplexed clients (see [pr](https://github.com/googleapis/java-spanner/pull/4023)), but does a no-op in non-multiplexed ones. Unlike Regular session, multiplex session needs a valid mutation to generate a precommit token.
Fixes #4046
> fix(spanner): check for empty before delete (#4047)

- README.adoc
This is a temporary change to update the README to the latest available documentation as reported in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/4113
After the new latest version's documentation is published, I will update again to the latest version
> chore: Update docs to latest available

- docs/update_latest_versions_in_readme.sh
**Description**
This PR introduces a new script to automate the process of updating the version numbers in the README.adoc file.
**Problem**
The README.adoc file contains links to the documentation for different versions of the project. These version numbers are hardcoded and need to be updated manually for each new release. This is a tedious and error-prone process.
**Solution**
This PR adds a new shell script named `update_latest_versions_in_readme.sh` in the `docs/` folder. This script:
1. Fetches the latest version numbers for each major release line (6.x, 5.x, 4.x, 3.x) from the maven-metadata.xml file in the Maven Central repository.
2. Uses sed to directly update the hardcoded version numbers in the README.adoc file.
**How to use the script**
To update the versions in the …
> feat: add script to update versions in README.adoc
